// <auto-generated />  path: global.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using System.Numerics;

namespace global;


[Source("~/global.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct GlobalStruct (Vector3 vector1, Vector3 vector2)
{
    [FieldOffset(  0)]  public  Vector3 vector1 = vector1;
    [FieldOffset( 16)]  public  Vector3 vector2 = vector2;
}


