<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <GenerateProgramFile>true</GenerateProgramFile>

        <!-- packaging -->
        <PublishRepositoryUrl>false</PublishRepositoryUrl>
        <IsPackable>false</IsPackable>
        <LangVersion>14</LangVersion>
        <!-- packaging: end -->
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
      <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Friflo.Engine.ECS" Version="4.0.0-preview.2" />
        <!-- <ProjectReference Include="..\..\..\Friflo.Engine.ECS\src\ECS\Friflo.Engine.ECS.csproj" /> -->

        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="NUnit" Version="3.13.3" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Friflo.WGSL.Transpiler\Friflo.WGSL.Transpiler.csproj" />
      <ProjectReference Include="..\Vectorization.Attributes\Friflo.Vectorization.Attributes.csproj" />
      <ProjectReference Include="..\Vectorization.GPU\Friflo.Vectorization.GPU.csproj" />
      <ProjectReference Include="..\Vectorization.WebGPU\Friflo.Vectorization.WebGPU.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <EmbeddedResource Include="Shaders\**\*.wgsl" />
      <AdditionalFiles Include="Shaders\**\*.wgsl" />
    </ItemGroup>
    
    <ItemGroup>
      <None Remove="*.csproj.lscache" />
    </ItemGroup>

</Project>
