<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <GenerateProgramFile>true</GenerateProgramFile>

        <!-- packaging -->
        <PublishRepositoryUrl>false</PublishRepositoryUrl>
        <IsPackable>false</IsPackable>
        <LangVersion>14</LangVersion>
        <!-- packaging: end -->
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
      <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Friflo.Engine.ECS" Version="4.0.0-preview.2" />
        <!-- <ProjectReference Include="..\..\..\Friflo.Engine.ECS\src\ECS\Friflo.Engine.ECS.csproj" /> -->

        <PackageReference Include="Microsoft.NET.Test.Sdk" 	Version="17.12.0" />
        <PackageReference Include="NUnit" 					Version="3.13.3" />
        <PackageReference Include="NUnit3TestAdapter" 		Version="4.6.0" />
        <PackageReference Include="StbImageWriteSharp" 		Version="1.16.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Friflo.WGSL.Transpiler\Friflo.WGSL.Transpiler.csproj" />
      <ProjectReference Include="..\Vectorization.Attributes\Friflo.Vectorization.Attributes.csproj" />
      <ProjectReference Include="..\Friflo.GPU\Friflo.GPU.csproj" />
      <ProjectReference Include="..\Friflo.WGPU\Friflo.WGPU.csproj" />
      <ProjectReference Include="..\Friflo.TmGui\Friflo.TmGui.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <AssemblyMetadata Include="ProjectDir" Value="$(MSBuildProjectDirectory)" />
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Include="**\*.wgsl" />
      <!-- <AdditionalFiles  Include="**\*.wgsl" /> -->
    </ItemGroup>
    <PropertyGroup>
      <!-- workaround for: https://youtrack.jetbrains.com/issue/RIDER-141199 -->  
      <AdditionalFileItemNames>$(AdditionalFileItemNames);EmbeddedResource</AdditionalFileItemNames>
    </PropertyGroup>
    
    <ItemGroup>
      <Compile Remove ="shaders/tests/compilerErrors*.wgsl.cs" />
      <None    Include="shaders/tests/compilerErrors*.wgsl.cs" />
      <Compile Remove ="gen/vec3h_UniArr_4.wgsl.cs" />
      <None    Include="gen/vec3h_UniArr_4.wgsl.cs" />
    </ItemGroup>
    <ItemGroup>
      <None Remove="*.csproj.lscache" />
    </ItemGroup>

</Project>
