// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.InstancedCube;


[Source("~/shaders/instancedCube/instanced.storage.vert.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct Uniforms (
    Matrix4x4 modelViewProjectionMatrix)
{
    public Matrix4x4 modelViewProjectionMatrix = modelViewProjectionMatrix;
}


