// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.InstancedCube;


/// Skipped identical duplicate of  <see cref="Uniforms"/>
file partial class _info;


