// <auto-generated />  path: shaders/instancedCube/instanced.vert.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using System.Numerics;

namespace Shaders.InstancedCube;


[Source("~/shaders/instancedCube/instanced.vert.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 1024)]
public struct Uniforms (in Matrix4x4_Array_16 modelViewProjectionMatrix)
{
    [FieldOffset(  0)]  public  Matrix4x4_Array_16 modelViewProjectionMatrix = modelViewProjectionMatrix;
}


[DebuggerTypeProxy(typeof(FixedArrayDebugView<Matrix4x4>))]
[StructLayout(LayoutKind.Explicit, Size = 1024)]
public struct Matrix4x4_Array_16
{
    public int  Length => 16;
    [FieldOffset(0)]  private Matrix4x4 _element0;
    
    public ref Matrix4x4 this[int index] {
        [UnscopedRef] get {
            if ((uint)index >= 16) throw new IndexOutOfRangeException();
            return ref Unsafe.AddByteOffset(ref _element0, (nint)index * 64);
        }
    }
    
    [UnscopedRef] public FixedArrayEnumerator<Matrix4x4> GetEnumerator() => new(ref _element0, 64, 1024);
}


