//HintName: VerifyVectorize.MyExample/Multiply_Matrix4x4.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Multiply_Matrix4x4"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery Multiply_Matrix4x4Query(EntityStore _store, global::System.Numerics.Matrix4x4 transform, bool vectorized = true)
        {
            var _query = _Multiply_Matrix4x4_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.ArchetypeComponents.AsSpan();
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Multiply_Matrix4x4_Avx(_entities.Length, positionSpan, transform);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    Multiply_Matrix4x4(ref positionSpan[n], transform);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Multiply_Matrix4x4_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position3>
            _Multiply_Matrix4x4_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position3>)
                EntityStore.UserDataGet(_store, _Multiply_Matrix4x4_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position3>();

            EntityStore.UserDataSet(_store, _Multiply_Matrix4x4_Slot, _query);
            return _query;
        }

        // [Layout: Horizontal]    - lane-native speed + Deinterleave penalty
        [SkipLocalsInit]
        private static unsafe int _Multiply_Matrix4x4_Avx(int count,
            Span<global::VerifyVectorize.Position3> position,
            global::System.Numerics.Matrix4x4 transform)
        {
            int paddedCount = (count + 7) & ~7;
            int i = 0;
            if (position.Length < paddedCount) VectorUtils.ThrowBufferTooSmall(nameof(position));

            // --- Locals
            // Load Matrix columns into 256-bit registers (each column duplicated)
            float* transform_ptr = (float*)&transform;
            Vector256<float> transform_0 = Avx.BroadcastVector128ToVector256(transform_ptr + 0);
            Vector256<float> transform_1 = Avx.BroadcastVector128ToVector256(transform_ptr + 4);
            Vector256<float> transform_2 = Avx.BroadcastVector128ToVector256(transform_ptr + 8);
            Vector256<float> transform_3 = Avx.BroadcastVector128ToVector256(transform_ptr + 12);

            fixed (global::VerifyVectorize.Position3* position_first = position)
            {
                for (; i < paddedCount; i += 8)
                {
                    float* position_ptr = (float*)(position_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position3
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position3
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position3
                    (position_0, position_1, position_2) = AvxVector3.Deinterleave(position_0, position_1, position_2);

                    // --- 2. Compute
                    // position.value = Vector3.Transform(position.value, transform);
                    //   Transform arg[0]
                    Vector256<float> temp0_0 = position_0;
                    Vector256<float> temp0_1 = position_1;
                    Vector256<float> temp0_2 = position_2;

                    position_0 = AvxVector3.TransformMatrixSoA(temp0_0, temp0_1, temp0_2, Vector256.Create(transform.M11), Vector256.Create(transform.M21), Vector256.Create(transform.M31), Vector256.Create(transform.M41));
                    position_1 = AvxVector3.TransformMatrixSoA(temp0_0, temp0_1, temp0_2, Vector256.Create(transform.M12), Vector256.Create(transform.M22), Vector256.Create(transform.M32), Vector256.Create(transform.M42));
                    position_2 = AvxVector3.TransformMatrixSoA(temp0_0, temp0_1, temp0_2, Vector256.Create(transform.M13), Vector256.Create(transform.M23), Vector256.Create(transform.M33), Vector256.Create(transform.M43));

                    // --- 3. Store
                    (position_0, position_1, position_2) = AvxVector3.Interleave(position_0, position_1, position_2);
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                }
            }
            return i;
        }

    #endregion
    }
}
