//HintName: VerifyVectorize.MyExample/Normalize.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Normalize"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery NormalizeQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _Normalize_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.GetComponentSpan();
                var velocitySpan = chunk.Chunk2.GetComponentSpan();
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Normalize_Avx(_entities.Length, positionSpan, velocitySpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    Normalize(ref positionSpan[n], velocitySpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Normalize_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position3, global::VerifyVectorize.Velocity3>
            _Normalize_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position3, global::VerifyVectorize.Velocity3>)
                EntityStore.UserDataGet(_store, _Normalize_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position3, global::VerifyVectorize.Velocity3>();

            EntityStore.UserDataSet(_store, _Normalize_Slot, _query);
            return _query;
        }

        // [Layout: Horizontal]    - lane-native speed + Deinterleave penalty
        [SkipLocalsInit]
        private static unsafe int _Normalize_Avx(int count,
            Span<global::VerifyVectorize.Position3> position,
            ReadOnlySpan<global::VerifyVectorize.Velocity3> velocity)
        {
            int paddedCount = (count + 7) & ~7;
            int i = 0;
            if (position.Length < paddedCount) VectorUtils.ThrowBufferTooSmall(nameof(position));
            if (velocity.Length < paddedCount) VectorUtils.ThrowBufferTooSmall(nameof(velocity));

            fixed (global::VerifyVectorize.Position3* position_first = position)
            fixed (global::VerifyVectorize.Velocity3* velocity_first = velocity)
            {
                float* position_ptr = (float*)position_first;
                float* velocity_ptr = (float*)velocity_first;

                for (; i < paddedCount; i += 8)
                {
                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position3
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position3
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position3
                    (position_0, position_1, position_2) = AvxVector3.Deinterleave(position_0, position_1, position_2);

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr +  0);   // Velocity3
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8);   // Velocity3
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16);   // Velocity3
                    (velocity_0, velocity_1, velocity_2) = AvxVector3.Deinterleave(velocity_0, velocity_1, velocity_2);

                    // --- 2. Compute
                    // position.value = Vector3.Normalize(velocity.value);
                    var (temp0_0, temp0_1, temp0_2) = AvxVector3.Normalize(velocity_0, velocity_1, velocity_2);
                    position_0 = temp0_0;
                    position_1 = temp0_1;
                    position_2 = temp0_2;

                    // --- 3. Store
                    (position_0, position_1, position_2) = AvxVector3.Interleave(position_0, position_1, position_2);
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);

                    position_ptr += 24;
                    velocity_ptr += 24;
                }
            }
            return i;
        }

    #endregion
    }
}
