//HintName: VerifyVectorize/MyExample/Mixed_Vector3.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Mixed_Vector3"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public static ArchetypeQuery Mixed_Vector3Query(EntityStore _store, bool vectorized = true)
        {
            var _query = _Mixed_Vector3_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.GetComponentSpan();
                var velocitySpan = chunk.Chunk2.GetLanesSoA();
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Mixed_Vector3_Avx(_entities.Length, positionSpan, velocitySpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    var velocityAoS = chunk.Chunk2.GetAoSoA(n);
                    Mixed_Vector3(ref positionSpan[n], velocityAoS);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Mixed_Vector3_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position2, global::VerifyVectorize.Pos2SoA>
            _Mixed_Vector3_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position2, global::VerifyVectorize.Pos2SoA>)
                EntityStore.UserDataGet(_store, _Mixed_Vector3_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position2, global::VerifyVectorize.Pos2SoA>();

            EntityStore.UserDataSet(_store, _Mixed_Vector3_Slot, _query);
            return _query;
        }

        // [Layout: AoS-SoA-Mixed] - lane-native speed + Deinterleave penalty
        [SkipLocalsInit]
        private static unsafe int _Mixed_Vector3_Avx(int count,
            Span<global::VerifyVectorize.Position2> position,
            Span<float> velocity)
        {
            int paddedCount = (count + 15) & ~15;
            int i = 0;
            if (position.Length < paddedCount) VectorUtils.ThrowBufferTooSmall(nameof(position));
            if (velocity.Length < paddedCount) VectorUtils.ThrowBufferTooSmall(nameof(velocity));

            fixed (global::VerifyVectorize.Position2* position_first = position)
            fixed (float* velocity_first = velocity)
            {
                float* position_ptr = (float*)position_first;
                float* velocity_ptr = (float*)velocity_first;

                for (; i < paddedCount; i += 16)
                {
                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position2
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position2
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position2
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);   // Position2
                    (position_0, position_1) = AvxVector2.Deinterleave(position_0, position_1);
                    (position_2, position_3) = AvxVector2.Deinterleave(position_2, position_3);

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr);      // xxxxxxxx Pos2SoA
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8); // yyyyyyyy
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16); // xxxxxxxx
                    Vector256<float> velocity_3 = Avx.LoadVector256(velocity_ptr + 24); // yyyyyyyy

                    // --- 2. Compute
                    // position.value *= velocity.value;
                    position_0 = Avx.Multiply(position_0, velocity_0);
                    position_1 = Avx.Multiply(position_1, velocity_1);
                    position_2 = Avx.Multiply(position_2, velocity_2);
                    position_3 = Avx.Multiply(position_3, velocity_3);

                    // --- 3. Store
                    (position_0, position_1) = AvxVector2.Interleave(position_0, position_1);
                    (position_2, position_3) = AvxVector2.Interleave(position_2, position_3);
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);

                    position_ptr += 32;
                    velocity_ptr += 32;
                }
            }
            return i;
        }

    #endregion
    }
}
