//HintName: VerifyVectorize/MyExample/AssignVector.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="AssignVector"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery AssignVectorQuery(EntityStore _store, Vector2 vector, bool vectorized = true)
        {
            var _query = _AssignVector_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.GetComponentSpan();
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _AssignVector_Avx(_entities.Length, positionSpan, vector);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    AssignVector(ref positionSpan[n], vector);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _AssignVector_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position2>
            _AssignVector_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position2>)
                EntityStore.UserDataGet(_store, _AssignVector_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position2>();

            EntityStore.UserDataSet(_store, _AssignVector_Slot, _query);
            return _query;
        }

        // [Layout: AoS-Vertical]  - lane-native speed
        [SkipLocalsInit]
        private static unsafe int _AssignVector_Avx(int count,
            Span<global::VerifyVectorize.Position2> position,
            Vector2 vector)
        {
            int paddedCount = (count + 15) & ~15;
            int i = 0;
            if (position.Length < paddedCount) VectorUtils.ThrowBufferTooSmall(nameof(position));

            // --- Locals
            Vector128<float> vector_half = Vector128.Create(vector.X, vector.Y, vector.X, vector.Y);
            var vector_scalar = Avx.InsertVector128(vector_half.ToVector256(), vector_half, 1);

            fixed (global::VerifyVectorize.Position2* position_first = position)
            {
                float* position_ptr = (float*)position_first;

                for (; i < paddedCount; i += 16)
                {
                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position2
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position2
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position2
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);   // Position2

                    // --- 2. Compute
                    // position.value = vector;
                    position_0 = vector_scalar;
                    position_1 = vector_scalar;
                    position_2 = vector_scalar;
                    position_3 = vector_scalar;

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);

                    position_ptr += 32;
                }
            }
            return i;
        }

    #endregion
    }
}
