//HintName: VerifyVectorize.MyExample/Length_Vector3.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Length_Vector3"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public static ArchetypeQuery Length_Vector3Query(EntityStore _store, bool vectorized = true)
        {
            var _query = _Length_Vector3_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.ArchetypeComponents.AsSpan();
                var lengthSpan = chunk.Chunk2.ArchetypeComponents.AsSpan();
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Length_Vector3_Avx(_entities.Length, positionSpan, lengthSpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    Length_Vector3(positionSpan[n], ref lengthSpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Length_Vector3_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position3, global::VerifyVectorize.FloatComponent>
            _Length_Vector3_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position3, global::VerifyVectorize.FloatComponent>)
                EntityStore.UserDataGet(_store, _Length_Vector3_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position3, global::VerifyVectorize.FloatComponent>();

            EntityStore.UserDataSet(_store, _Length_Vector3_Slot, _query);
            return _query;
        }

        // [Layout: Horizontal]    - lane-native speed + Deinterleave penalty
        [SkipLocalsInit]
        private static unsafe int _Length_Vector3_Avx(int count,
            ReadOnlySpan<global::VerifyVectorize.Position3> position,
            Span<global::VerifyVectorize.FloatComponent> length)
        {
            int paddedCount = (count + 7) & ~7;
            int i = 0;
            if (position.Length < paddedCount) VectorUtils.ThrowBufferTooSmall(nameof(position));
            if (length.Length < paddedCount) VectorUtils.ThrowBufferTooSmall(nameof(length));

            // --- Locals
            Vector256<int> length_mask_0 = Vector256.Create(0, 0, 0, 1, 1, 1, 2, 2);
            Vector256<int> length_mask_1 = Vector256.Create(2, 3, 3, 3, 4, 4, 4, 5);
            Vector256<int> length_mask_2 = Vector256.Create(5, 5, 6, 6, 6, 7, 7, 7);

            fixed (global::VerifyVectorize.Position3* position_first = position)
            fixed (global::VerifyVectorize.FloatComponent* length_first = length)
            {
                float* position_ptr = (float*)position_first;
                float* length_ptr = (float*)length_first;

                for (; i < paddedCount; i += 8)
                {
                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position3
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position3
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position3
                    (position_0, position_1, position_2) = AvxVector3.Deinterleave(position_0, position_1, position_2);

                    Vector256<float> length_0;  // FloatComponent

                    // --- 2. Compute
                    // length.value = position.value.Length();
                    length_0 = AvxVector3.Length(position_0, position_1, position_2);

                    // --- 3. Store
                    Avx.Store(length_ptr +  0, length_0);

                    position_ptr += 24;
                    length_ptr += 8;
                }
            }
            return i;
        }

    #endregion
    }
}
