//HintName: VerifyVectorize.MyExample/Mixed_Vector3.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Mixed_Vector3"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public static ArchetypeQuery Mixed_Vector3Query(EntityStore _store, bool vectorized = true)
        {
            var _query = _Mixed_Vector3_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.GetLanesSoA();
                var velocitySpan = chunk.Chunk2.GetLanesSoA();
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Mixed_Vector3_Avx(_entities.Length, positionSpan, velocitySpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    var positionAoS = chunk.Chunk1.GetAoSoA(n);
                    var velocityAoS = chunk.Chunk2.GetAoSoA(n);
                    Mixed_Vector3(ref positionAoS, velocityAoS);
                    chunk.Chunk1.SetAoSoA(n, positionAoS);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Mixed_Vector3_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Pos2SoA, global::VerifyVectorize.Vel2SoA>
            _Mixed_Vector3_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Pos2SoA, global::VerifyVectorize.Vel2SoA>)
                EntityStore.UserDataGet(_store, _Mixed_Vector3_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Pos2SoA, global::VerifyVectorize.Vel2SoA>();

            EntityStore.UserDataSet(_store, _Mixed_Vector3_Slot, _query);
            return _query;
        }

        // [Layout: [SoA] All]     - lane-native speed
        [SkipLocalsInit]
        private static unsafe int _Mixed_Vector3_Avx(int count,
            Span<float> position,
            Span<float> velocity)
        {
            int paddedCount = (count + 15) & ~15;
            int i = 0;
            if (position.Length < paddedCount) VectorUtils.ThrowBufferTooSmall(nameof(position));
            if (velocity.Length < paddedCount) VectorUtils.ThrowBufferTooSmall(nameof(velocity));

            fixed (float* position_first = position)
            fixed (float* velocity_first = velocity)
            {
                for (; i < paddedCount; i += 16)
                {
                    float* position_ptr = (float*)(position_first + (i << 1));
                    float* velocity_ptr = (float*)(velocity_first + (i << 1));

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr);      // xxxxxxxx Pos2SoA
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8); // yyyyyyyy
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16); // xxxxxxxx
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24); // yyyyyyyy

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr);      // xxxxxxxx Vel2SoA
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8); // yyyyyyyy
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16); // xxxxxxxx
                    Vector256<float> velocity_3 = Avx.LoadVector256(velocity_ptr + 24); // yyyyyyyy

                    // --- 2. Compute
                    // position.value *= velocity.value;
                    position_0 = Avx.Multiply(position_0, velocity_0);
                    position_1 = Avx.Multiply(position_1, velocity_1);
                    position_2 = Avx.Multiply(position_2, velocity_2);
                    position_3 = Avx.Multiply(position_3, velocity_3);

                    // --- 3. Store
                    Avx.Store(position_ptr,      position_0); // xxxxxxxx
                    Avx.Store(position_ptr +  8, position_1); // yyyyyyyy
                    Avx.Store(position_ptr + 16, position_2); // xxxxxxxx
                    Avx.Store(position_ptr + 24, position_3); // yyyyyyyy
                }
            }
            return i;
        }

    #endregion
    }
}
