//HintName: VerifyVectorize.MyExample/Mixed_Vector3.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Mixed_Vector3"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public static ArchetypeQuery Mixed_Vector3Query(EntityStore _store, bool vectorized = true)
        {
            var _query = _Mixed_Vector3_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.GetLanesSoA();
                var velocitySpan = chunk.Chunk2.GetLanesSoA();
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Mixed_Vector3_Avx(_entities.Length, positionSpan, chunk.Chunk1.GetStrideSoA(), velocitySpan, chunk.Chunk2.GetStrideSoA());
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    var positionAoS = chunk.Chunk1.GetSoA(n);
                    var velocityAoS = chunk.Chunk2.GetSoA(n);
                    Mixed_Vector3(ref positionAoS, velocityAoS);
                    chunk.Chunk1.SetSoA(n, positionAoS);
                    chunk.Chunk2.SetSoA(n, velocityAoS);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Mixed_Vector3_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Pos3SoA, global::VerifyVectorize.Vel3SoA>
            _Mixed_Vector3_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Pos3SoA, global::VerifyVectorize.Vel3SoA>)
                EntityStore.UserDataGet(_store, _Mixed_Vector3_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Pos3SoA, global::VerifyVectorize.Vel3SoA>();

            EntityStore.UserDataSet(_store, _Mixed_Vector3_Slot, _query);
            return _query;
        }

        // [Layout: [SoA] All]     - lane-native speed
        [SkipLocalsInit]
        private static unsafe int _Mixed_Vector3_Avx(int count,
            Span<float> position,
            int position_stride,
            Span<float> velocity,
            int velocity_stride)
        {
            int i = 0;
            count -= 8;
            if (i > count) {
                return 0;
            }
            fixed (float* position_first = position)
            fixed (float* velocity_first = velocity)
            {
                for (; i <= count; i += 8)
                {
                    float* position_ptr = (float*)(position_first + i);
                    float* velocity_ptr = (float*)(velocity_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr + position_stride * 0);   // Pos3SoA
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr + position_stride * 1);   // Pos3SoA
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + position_stride * 2);   // Pos3SoA

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr + velocity_stride * 0);   // Vel3SoA
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr + velocity_stride * 1);   // Vel3SoA
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + velocity_stride * 2);   // Vel3SoA

                    // --- 2. Compute
                    // position.value *= velocity.value;
                    position_0 = Avx.Multiply(position_0, velocity_0);
                    position_1 = Avx.Multiply(position_1, velocity_1);
                    position_2 = Avx.Multiply(position_2, velocity_2);

                    // --- 3. Store
                    Avx.Store(position_ptr + position_stride * 0, position_0);
                    Avx.Store(position_ptr + position_stride * 1, position_1);
                    Avx.Store(position_ptr + position_stride * 2, position_2);
                }
            }
            return i;
        }

    #endregion
    }
}
