// Copyright (c) Ullrich Praetz - https://github.com/friflo. All rights reserved.
// See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;


// ReSharper disable LoopCanBeConvertedToQuery
// ReSharper disable ForeachCanBePartlyConvertedToQueryUsingAnotherGetEnumerator
// ReSharper disable UnusedMember.Local
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
namespace Friflo.WGSL.Transpiler.WGSL;


#if FILE_IO

public sealed partial class TypeGen
{
    private readonly    StringBuilder   fileBuilder             = new ();
    private readonly    StringBuilder   body                    = new();
    //
    

    private static void DebugInputs(WgslFile[] wgslFiles, string projDir)
    {
        var path = Path.Combine(projDir, "debug.txt");
        var sb = new StringBuilder();
        sb.Append($"projDir: {projDir}\n\n");
        
        foreach (var file in wgslFiles) {
            sb.Append($"{file.NormalizedPath}\n");
        }
        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
    }
    
    private static string PathToNamespace(string path)
    {
        var dir = Path.GetDirectoryName(path);
        if (string.IsNullOrEmpty(dir)) return "";

        var parts = dir.Split(['/', '\\', '-', '_'], StringSplitOptions.RemoveEmptyEntries);
        for (int i = 0; i < parts.Length; i++)
        {
            var p = parts[i];
            var rest = p.Length > 1 ? p.Substring(1) : "";
            parts[i] = (char.IsDigit(p[0]) ? "_" : "") + char.ToUpperInvariant(p[0]) + rest;
        }
        return $"{string.Join(".", parts)}";
    }
    
    public void EmitAllStructs(WgslFile[] wgslFiles, string projDir, TypeMapping[] mappings, ToolError[] errors)
    {
        wgslFiles = wgslFiles.ToArray();
        var errorFilePath = $"{projDir}/generator-error.cs";
        if (errors.Length == 0) {
            if (File.Exists(errorFilePath)) {
                File.Delete(errorFilePath);    
            }
        } else {
            var sb = new StringBuilder();
            foreach (var error in errors) {
                sb.Append($"#error {error}\n");
            }
            File.WriteAllText(errorFilePath, sb.ToString(), new UTF8Encoding(false));
        }
        TypeMap = TypeMapping.CreateTypeMap(mappings);
        
        for (int n = 0; n < wgslFiles.Length; n++) {
            var path =  wgslFiles[n].NormalizedPath.Substring(projDir.Length + 1);
            wgslFiles[n] = wgslFiles[n] with{ NormalizedPath =  path };
        }
        // DebugInputs(wgslFiles, projDir);
        
        // sort for deterministic generation
        WgslFile.Sort(wgslFiles);
        var files = new List<(string, string)>();
        foreach (var file in wgslFiles)
        {
            var content = EmitFile(file);
            if (content == null) continue;
            files.Add((file.NormalizedPath + ".cs", content));
        }
        EmitFixedSizeArrays(files);
        
        UpdateFiles(projDir, files);
    }

    private void EmitFixedSizeArrays(List<(string, string)> files)
    {
        foreach (var fixedSizedArrayType in globalFixedSizedArrayTypes)
        {
            var generatedType = fixedSizedArrayType.Value;
            var ns       = generatedType.Namespace;
            var fileName = ns == "" ? $"gen/{generatedType.Name}.wgsl.cs"
                                    : $"gen/{ns}/{generatedType.Name}.wgsl.cs";
            var nsDecl   = ns == "" ? "" : $"namespace {ns};";
            fileBuilder.Clear();
            EmitFileHeader(fileName);
            fileBuilder.Append( // language=csharp
                $"""
                
                {nsDecl}
                
                
                {fixedSizedArrayType.Value.source}
                """);
            files.Add((fileName, fileBuilder.ToString()));
        }
    }
    
    private static void UpdateFiles(string projDir, List<(string, string)> files)
    {
        var searchPath  = Path.GetFullPath(projDir);
        var currentFiles = new HashSet<string>();
        if (Directory.Exists(searchPath)) {
            var fullBaseDir = searchPath.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            foreach (var fullFilePath in Directory.EnumerateFiles(fullBaseDir, "*.wgsl.cs", SearchOption.AllDirectories))
            {
                var normalizedPath = fullFilePath.Substring(fullBaseDir.Length + 1).Replace('\\', '/');
                var expect = $"// <auto-generated />  path: {normalizedPath}";
                using var reader = new StreamReader(fullFilePath);
                var firstLine = reader.ReadLine();
                if (firstLine == expect) {
                    currentFiles.Add(normalizedPath);
                }
            }
        }
        foreach (var (path, content) in files) {
            var absPath = $"{projDir}/{path}";
            currentFiles.Remove(path);
            if (!File.Exists(absPath) || File.ReadAllText(absPath) != content) {
                Directory.CreateDirectory(Path.GetDirectoryName(absPath)!);
                File.WriteAllText(absPath, content, new UTF8Encoding(false));
            }
        }
        foreach (var path in currentFiles) {
            var absPath = $"{projDir}/{path}";
            File.Delete(absPath);
        }
    }
    
    private void EmitFileHeader(string path)
    {
        fileBuilder.Append( // language=csharp
            $"""
            // <auto-generated />  path: {path}
            using System;
            using System.Diagnostics;
            using System.Diagnostics.CodeAnalysis;
            using System.Runtime.CompilerServices;
            using System.Runtime.InteropServices;
            using Friflo.Vectorization.WebGPU;
            
            """);
    }
    
    private string? EmitFile(WgslFile file)
    {
        var normalizedPath = file.NormalizedPath;
        try {
            // --- clear state first!
            fileBuilder.Clear();
            body.Clear();
            localStructs.Clear();
            requiredStructs.Clear();
            emittedStructs.Clear();
            wgslStructs.Clear();
            localFixedSizedArrayTypes.Clear();
            additionalNamespaces.Clear();
            fileNamespace = PathToNamespace(normalizedPath);
            
            // --- process after
            EmitFileHeader(normalizedPath + ".cs");
            module = FastWgslParser.ParseWgsl(file.Content, normalizedPath);
            EmitStructs(body, normalizedPath);
            if (body.Length == 0 && localFixedSizedArrayTypes.Count == 0) {
                return null;
            }
            foreach (var ns in additionalNamespaces) {
                fileBuilder.Append($"using {ns};\n");
            }
            foreach (var fixedSizedArrayType in localFixedSizedArrayTypes) {
                body.Append(fixedSizedArrayType.Value.source);
            }
            var nsDecl   = fileNamespace == "" ? "" : $"namespace {fileNamespace};";
            fileBuilder.Append( // language=csharp
                $"""
                
                {nsDecl}
                
                
                {body}
                """);
        }
        catch (Exception exception) {
            fileBuilder.Append( // language=csharp
                $"""
                
                /* -------- Error parsing: {normalizedPath}
                {WgslUtils.GetExceptionAsString(exception)}
                */
                """);
        }
        return fileBuilder.ToString();
    }
}

#endif