// Copyright (c) Ullrich Praetz - https://github.com/friflo. All rights reserved.
// See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;


// ReSharper disable LoopCanBeConvertedToQuery
// ReSharper disable ForeachCanBePartlyConvertedToQueryUsingAnotherGetEnumerator
// ReSharper disable UnusedMember.Local
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
namespace Friflo.WGSL.Transpiler.WGSL;


public sealed class TypeGen
{
    private  readonly   StringBuilder   fileBuilder             = new ();
    private  readonly   StringBuilder   body                    = new();
    //
    internal readonly   List<string>                        newStructTypes          = [];
    internal readonly   StringBuilder                       newStructTypeBuilder    = new();
    internal readonly   Dictionary<string, FixedSizeArray>  fixedSizedArrayTypes    = new();
    private  readonly   HashSet<string>                     additionalNamespaces    = [];
    
    internal void AddNamespace(in CSharpType csharpType)
    {
        if (csharpType.identifier.Namespace == "" ||
            csharpType.identifier.Namespace == "System") {
            return;
        }
        additionalNamespaces.Add(csharpType.identifier.Namespace);
    }

#if FILE_IO

    private static void DebugInputs(WgslFile[] wgslFiles, string projDir)
    {
        var path = Path.Combine(projDir, "debug.txt");
        var sb = new StringBuilder();
        sb.Append($"projDir: {projDir}\n\n");
        
        foreach (var file in wgslFiles) {
            sb.Append($"{file.NormalizedPath}\n");
        }
        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
    }
    
    public void EmitAllStructs(WgslFile[] wgslFiles, string projDir, TypeMapping[] mappings, ToolError[] errors)
    {
        wgslFiles = wgslFiles.ToArray();
        var errorFilePath = $"{projDir}/generator-error.cs";
        if (errors.Length == 0) {
            if (File.Exists(errorFilePath)) {
                File.Delete(errorFilePath);    
            }
        } else {
            var sb = new StringBuilder();
            foreach (var error in errors) {
                sb.Append($"#error {error}\n");
            }
            File.WriteAllText(errorFilePath, sb.ToString(), new UTF8Encoding(false));
        }
        var typeMap = TypeMapping.CreateTypeMap(mappings);
        var typeBuilder = new TypeBuilder(typeMap, this);

        
        for (int n = 0; n < wgslFiles.Length; n++) {
            var path =  wgslFiles[n].NormalizedPath.Substring(projDir.Length + 1);
            wgslFiles[n] = wgslFiles[n] with{ NormalizedPath =  path };
        }
        // DebugInputs(wgslFiles, projDir);
        
        // sort for deterministic generation
        WgslFile.Sort(wgslFiles);
        var files = new List<(string, string)>();
        foreach (var file in wgslFiles)
        {
            var content = EmitFile(file, typeBuilder);
            if (content == null) continue;
            files.Add((file.NormalizedPath + ".cs", content));
        }
        EmitFixedSizeArrays(files);
        
        UpdateFiles(projDir, files);
    }

    private void EmitFixedSizeArrays(List<(string, string)> files)
    {
        foreach (var fixedSizedArrayType in fixedSizedArrayTypes)
        {
            var generatedType = fixedSizedArrayType.Value;
            if (generatedType.source == null) {
                continue;
            }
            var ns       = generatedType.Namespace;
            var fileName = ns == "" ? $"gen/{generatedType.Name}.wgsl.cs"
                                    : $"gen/{ns}/{generatedType.Name}.wgsl.cs";
            var nsDecl   = ns == "" ? "" : $"namespace {ns};";
            fileBuilder.Clear();
            EmitFileHeader(fileName);
            fileBuilder.Append( // language=csharp
                $"""
                
                {nsDecl}
                
                
                {generatedType.source}
                """);
            files.Add((fileName, fileBuilder.ToString()));
        }
    }
    
    private static void UpdateFiles(string projDir, List<(string, string)> files)
    {
        var searchPath  = Path.GetFullPath(projDir);
        var currentFiles = new HashSet<string>();
        if (Directory.Exists(searchPath)) {
            var fullBaseDir = searchPath.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            foreach (var fullFilePath in Directory.EnumerateFiles(fullBaseDir, "*.wgsl.cs", SearchOption.AllDirectories))
            {
                var normalizedPath = fullFilePath.Substring(fullBaseDir.Length + 1).Replace('\\', '/');
                var expect = $"// <auto-generated />  path: {normalizedPath}";
                using var reader = new StreamReader(fullFilePath);
                var firstLine = reader.ReadLine();
                if (firstLine == expect) {
                    currentFiles.Add(normalizedPath);
                }
            }
        }
        foreach (var (path, content) in files) {
            var absPath = $"{projDir}/{path}";
            currentFiles.Remove(path);
            if (!File.Exists(absPath) || File.ReadAllText(absPath) != content) {
                Directory.CreateDirectory(Path.GetDirectoryName(absPath)!);
                File.WriteAllText(absPath, content, new UTF8Encoding(false));
            }
        }
        foreach (var path in currentFiles) {
            var absPath = $"{projDir}/{path}";
            File.Delete(absPath);
        }
    }
    
    private void EmitFileHeader(string path)
    {
        fileBuilder.Append( // language=csharp
            $"""
            // <auto-generated />  path: {path}
            using System;
            using System.Diagnostics;
            using System.Diagnostics.CodeAnalysis;
            using System.Runtime.CompilerServices;
            using System.Runtime.InteropServices;
            using Friflo.WGPU;
            
            """);
    }
    
    private string? EmitFile(WgslFile file, TypeBuilder typeBuilder)
    {
        var normalizedPath = file.NormalizedPath;
        try {
            // --- clear state first!
            fileBuilder.Clear();
            body.Clear();
            newStructTypes.Clear();
            additionalNamespaces.Clear();
            
            // --- process after
            EmitFileHeader(normalizedPath + ".cs");
            var module = FastWgslParser.ParseWgsl(file.Content, normalizedPath);
            
            typeBuilder.CreateStructs(module, normalizedPath);
            typeBuilder.EmitStructs(body, normalizedPath);
            
            if (body.Length == 0 && newStructTypes.Count == 0) {
                return null;
            }
            foreach (var ns in additionalNamespaces) {
                fileBuilder.Append($"using {ns};\n");
            }
            foreach (var newStructType in newStructTypes) {
                body.Append(newStructType);
            }
            var fileNamespace   = typeBuilder.FileNamespace;
            var nsDecl          = fileNamespace == "" ? "" : $"namespace {fileNamespace};";
            fileBuilder.Append( // language=csharp
                $"""
                
                {nsDecl}
                
                
                {body}
                """);
        }
        catch (Exception exception) {
            fileBuilder.Append( // language=csharp
                $"""
                
                /* -------- Error parsing: {normalizedPath}
                {WgslUtils.GetExceptionAsString(exception)}
                */
                """);
        }
        return fileBuilder.ToString();
    }
    
    #endif
}

