// Copyright (c) Ullrich Praetz - https://github.com/friflo. All rights reserved.
// See LICENSE file in the project root for full license information.

using System.Text;
using Friflo.Vectorization.Generators;
using Microsoft.CodeAnalysis;

// ReSharper disable ConvertIfStatementToConditionalTernaryExpression
// ReSharper disable ForCanBeConvertedToForeach
// ReSharper disable once CheckNamespace
// Note: Used small namespace and class name to enable shorter path names in 'Generated' folders
namespace Friflo;

public partial class Gen
{
    private static string EmitKernelSource(Query query)
    {
        var vectorTypes = query.VectorTypes;
        var signature = new StringBuilder();
        var validate  = new StringBuilder();
        var gpuParams = new StringBuilder();
        var avxParams = new StringBuilder();
        
        for (int n = 0; n < vectorTypes.Length; n++)
        {
            var vectorType  = vectorTypes[n];
            var parameter   = vectorType.Parameter;
            var type        = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (vectorType.IsSpan) {
                // var span = parameter.RefKind == RefKind.Ref ? "Span" : "ReadOnlySpan";
                signature.Append($"\n            Buffer<{type}> {parameter.Name}, ");
                if (n == 0) {
                    validate.Append($"            GpuBuffers buffers = new({parameter.Name}, nameof({parameter.Name}));\n");
                } else {
                    validate.Append($"            buffers.Validate        ({parameter.Name}, nameof({parameter.Name}));\n");
                }
                gpuParams.Append($"{parameter.Name}.gpuBuffer, ");
                avxParams.Append($"{parameter.Name}.span, ");
                continue;
            }
            GeneratorUtils.AppendRefKind(signature, parameter.RefKind);
            signature.Append($"\n            {type} {parameter.Name}, ");
            gpuParams.Append($"{parameter.Name}, ");
            avxParams.Append($"{parameter.Name}, ");
        }
        signature.Length -= 2;
        gpuParams.Length -= 2;
        avxParams.Length -= 2;
        
        var blueprintMethod = query.BlueprintMethod;
        var methodName      = query.BlueprintMethod.Name;
        var hash            = query.Hash;
        
        var shadowMethodSource = $@"
        /// <summary>Kernel method generated by: <see cref=""{methodName}""/>.</summary>
        public {(blueprintMethod.IsStatic ? "static " : "")}GpuBuffer<float> {methodName}Kernel({signature})
        {{
{validate}
            if (!buffers.areSpans) {{
                // return {methodName}_GPU{hash}(buffers, {gpuParams});
            }}
            _{methodName}_Avx{hash}(buffers.count, {avxParams});
            return null;
        }}
";
        return shadowMethodSource;
    }
}