// Copyright (c) Ullrich Praetz - https://github.com/friflo. All rights reserved.
// See LICENSE file in the project root for full license information.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Friflo.Vectorization.Generators;

// ReSharper disable UseObjectOrCollectionInitializer
// ReSharper disable SuggestVarOrType_BuiltInTypes
// ReSharper disable InconsistentNaming
// ReSharper disable ConvertIfStatementToConditionalTernaryExpression
// ReSharper disable ForCanBeConvertedToForeach
// ReSharper disable once CheckNamespace
// Note: Used small namespace and class name to enable shorter path names in 'Generated' folders
namespace Friflo;

public sealed partial class Gen
{
    private static string EmitKernelSource(Query query)
    {
        var vectorTypes = query.VectorTypes;
        var firstVector = vectorTypes.FirstOrDefault(v => v.IsSpan);
        var outputType  = firstVector?.FullQualifiedName;
        var signature = new StringBuilder();
        var validate  = new StringBuilder();
        var gpuParams = new StringBuilder();
        var avxParams = new StringBuilder();
        
        for (int n = 0; n < vectorTypes.Length; n++)
        {
            var vectorType  = vectorTypes[n];
            var parameter   = vectorType.Parameter;
            var type        = vectorType.FullQualifiedName;
            if (vectorType.IsSpan) {
                signature.Append($"\n            Buffer<{type}> {parameter.Name},");
                if (n == 0) {
                    validate.Append($"            GpuBuffers buffers = new({parameter.Name}, nameof({parameter.Name}));\n");
                } else {
                    validate.Append($"            buffers.Validate        ({parameter.Name}, nameof({parameter.Name}));\n");
                }
                gpuParams.Append($"{parameter.Name}.gpuBuffer, ");
                avxParams.Append($"{parameter.Name}.span, ");
                continue;
            }
            GeneratorUtils.AppendRefKind(signature, parameter.RefKind);
            signature.Append($"\n            {type} {parameter.Name},");
            gpuParams.Append($"{parameter.Name}, ");
            avxParams.Append($"{parameter.Name}, ");
        }
        signature.Length -= 1;
        gpuParams.Length -= 2;
        avxParams.Length -= 2;
        
        var blueprintMethod = query.BlueprintMethod;
        var methodName      = query.BlueprintMethod.Name;
        var hash            = query.Hash;
        
        var shadowMethodSource = $@"
        /// <summary>Kernel method generated by: <see cref=""{methodName}""/>.</summary>
        public {(blueprintMethod.IsStatic ? "static " : "")}GpuBuffer<{outputType}> {methodName}Kernel({signature})
        {{
{validate}
            if (!buffers.areSpans) {{
                return _{methodName}_GPU{hash}(buffers, {gpuParams});
            }}
            {methodName}Vector({avxParams});
            return null;
        }}
";
        return shadowMethodSource;
    }
    
    private const ulong BindingStartHash    = 14695981039346656037UL;
    private const ulong UniformStartHash    = 11136453673324647311UL;
    private const ulong Prime               = 1099511628211UL;
    
    public enum BufferBindingType
    {
      BindingNotUsed    = 0,
      Undefined         = 1,
      Uniform           = 2,
      Storage           = 3,
      ReadOnlyStorage   = 4,
    }
    
    private static string EmitKernelPrivate(Query query)
    {
        var vectorTypes = query.VectorTypes;
        var firstVector = vectorTypes.FirstOrDefault(v => v.IsSpan);
        var outputType  = firstVector?.FullQualifiedName;
        
        // ----------------- buffers
        var signature           = new StringBuilder();
        var dependencies        = new StringBuilder();
        var bufferBindEntries   = new StringBuilder();
        var bufferLayoutEntries = new StringBuilder();
        var bindings            = new StringBuilder();
        var bindingHash         = BindingStartHash;
        int bufferCount = 0;
        var setTaskOnOutputs    = new StringBuilder();

        foreach (var vectorType in vectorTypes)
        {
            if (!vectorType.IsSpan) {
                continue;
            }
            var parameter   = vectorType.Parameter;
            var paramName   = parameter.Name;
            var type        = vectorType.FullQualifiedName;
            bool isOutput = query.dirtyVectorsSet.Contains(paramName);
            signature.Append($"\n        GpuBuffer<{type}> {paramName},");
            if (isOutput) {
                setTaskOnOutputs.Append($"\n        ((WgpuBuffer<{type}>){paramName}).SetLastWritingTask(task);");
            } else {
                dependencies.Append($"\n        if ({paramName}.LastWritingTask != null) task.AddDependency({paramName});");
            }
            bufferBindEntries.Append($"\n                entries[{bufferCount}] = WgpuBindGroup.From({bufferCount}, {paramName});");
            var storageMethod = isOutput ? "ReadWriteStorage" : "ReadOnlyStorage ";
            var storageWgsl   = isOutput ? "read_write"       : "read      ";
            var binding = $"var<storage, {storageWgsl}>  {paramName}_arr: array<f32>;";
            bindings.Append($"    @group(0) @binding({bufferCount}) {binding}\n");
            bufferLayoutEntries.Append($"\n            buffers[{bufferCount}] = WgpuLayoutEntry.{storageMethod}<{type}> ({bufferCount}); // {binding }");
            bindingHash ^= (ulong)bufferCount;                                                                  bindingHash *= Prime;
            bindingHash ^= (ulong)(isOutput ? BufferBindingType.Storage : BufferBindingType.ReadOnlyStorage);   bindingHash *= Prime;
            // Note: the data type in a buffer is not relevant for layout. Need to understand why.
            bufferCount++;
        }
        
        // ----------------- uniforms
        var uniformFields       = new List<UniformField>();
        var alignedSize         = UniformField.GetUniformFields(query, uniformFields);
        var uniformAssignments  = new StringBuilder();
        var structFields        = new StringBuilder();
        var wgslFields          = new StringBuilder();
        var uniformHash         = UniformStartHash;

        foreach (var field in uniformFields)
        {
            GeneratorUtils.AppendRefKind(signature, field.refKind);
            if (!field.isCount) {
                signature.Append($"\n        {field.type} {field.name},");
            }
            var right = field.isCount ? "buffers.count" : field.name;
            uniformAssignments.Append($"\n                {field.name} = {right},");
            structFields.Append($"\n        [FieldOffset({field.offset})]    public {field.type,-10} {field.name};");
            wgslFields.Append($"\n        {field.name,-10} : {field.wgslType},");
        }
        unchecked {
            // Simulate a Uniform-Binding on @binding(0) for whole uniform group
            uniformHash ^= 0;                                   uniformHash *= Prime;
            uniformHash ^= (ulong)BufferBindingType.Uniform;    uniformHash *= Prime;
            uniformHash ^= (ulong)alignedSize;                  uniformHash *= Prime;
        }
        signature.Length -= 1;
        
        var blueprintMethod     = query.BlueprintMethod;
        var hash                = query.Hash;
        var methodName          = query.BlueprintMethod.Name;
        var methodName_GPU      = $"_{methodName}_GPU{hash}";
        var wgslHelperMethods   = WgslHelper.GenerateWgslHelperMethods(query);
        
        // ----------------- generate method
        var shadowMethodSource =
$$""""

    [SkipLocalsInit]
    private {{(blueprintMethod.IsStatic ? "static " : "")}}GpuBuffer<{{outputType}}> {{methodName_GPU}}(
        in GpuBuffers buffers,{{signature}})
    {
        var device      = (WgpuDevice)buffers.GetDevice();
        // output ??= device.RentBuffer<{{outputType}}>(buffers.count);  TODO
        using var task  = device.RentTask();

        // Dependencies from inputs (out not Output!){{dependencies}}

        // Recording - task provides Encoder
        var encoder = task.GetEncoder("{{methodName}}"u8);
        using (var pass = encoder.BeginComputePass("{{methodName}}"u8))
        {
            var effect = device.GetEffect({{methodName_GPU}}_EffectSlot); // simple GpuEffect[] array lookup
            if (!effect.IsCreated) {
                effect = {{methodName_GPU}}_CreateEffect(device);
            }
            pass.SetPipeline(effect.pipeline);
            
            // Creation of buffer bind group is expensive. Try get from cache with two entries.
            var bufferGroup = effect.bufferCache.GetGroup(buffers.hash);
            if (!bufferGroup.IsCreated) {
                Span<BindGroupEntry> entries = stackalloc BindGroupEntry[{{bufferCount}}];{{bufferBindEntries}}
                bufferGroup = task.CreateBindGroup(effect.bufferLayout, entries, "{{methodName}}_buffers"u8);
                device.UpdateBufferCache({{methodName_GPU}}_EffectSlot, bufferGroup, buffers.hash);
            }
            pass.SetBindGroup(0, bufferGroup);
            
            var uniforms = new {{methodName_GPU}}_Uniforms {{{uniformAssignments}}
            };
            var entry = task.AsUniformEntry(0, uniforms);
            // Creation of uniform bind group is cheap => no caching.
            var uniformGroup = task.CreateBindGroup(effect.uniformLayout, entry, "{{methodName}}_uniforms"u8);
            pass.SetBindGroup(1, uniformGroup);
            
            pass.DispatchWorkgroups((buffers.count + 63) / 64, 1, 1);
            pass.End();
        }
        // connect task to output{{setTaskOnOutputs}}

        task.Finish(encoder, "{{methodName}}"u8);
        device.Enqueue(task); // queues CommandBuffer only. No Submit().

        // output.WaitInDebug();
        return null;
    }
    
    [StructLayout(LayoutKind.Explicit, Size = {{alignedSize}})]  // WGSL layout: std140/std430
    private struct {{methodName_GPU}}_Uniforms
    {{{structFields}}
    }
    
    private static readonly int {{methodName_GPU}}_EffectSlot         = WgpuDevice.NewEffectSlot();
    private const ulong         {{methodName_GPU}}_BufferLayoutKey    = 0x{{bindingHash:x}};
    private const ulong         {{methodName_GPU}}_UniformLayoutKey   = 0x{{uniformHash:x}};

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static WgpuEffect {{methodName_GPU}}_CreateEffect(WgpuDevice device)
    {
        // @group(0)
        var bufferLayout = device.GetBindGroupLayout({{methodName_GPU}}_BufferLayoutKey);
        if (!bufferLayout.IsCreated) {
            Span<WgpuLayoutEntry> buffers = stackalloc WgpuLayoutEntry[{{bufferCount}}];{{bufferLayoutEntries}}
            bufferLayout = device.CreateBindGroupLayout(buffers, {{methodName_GPU}}_BufferLayoutKey, "{{methodName}}_buffers"u8);
        }
        // @group(1)
        var uniformLayout = device.GetBindGroupLayout({{methodName_GPU}}_UniformLayoutKey);
        if (!uniformLayout.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0]    = WgpuLayoutEntry.Uniform<{{methodName_GPU}}_Uniforms> (0); // var<uniform>              uniforms
            uniformLayout = device.CreateBindGroupLayout(uniform, {{methodName_GPU}}_UniformLayoutKey, "{{methodName}}_uniforms"u8);
        }
        var shaderModule    = device.CreateShaderModule({{methodName_GPU}}_Shader(), "{{methodName}}"u8);
        var pipeline        = device.CreateComputePipeline(shaderModule, bufferLayout, uniformLayout, "{{methodName}}"u8);
        
        return device.CreateEffect({{methodName_GPU}}_EffectSlot, pipeline, bufferLayout, uniformLayout);
    }

    private static ReadOnlySpan<byte> {{methodName_GPU}}_Shader() =>
    """{{wgslHelperMethods}}
    struct {{methodName}}_Uniforms {{{wgslFields}}
    };
    
{{bindings}}
    @group(1) @binding(0) var<uniform>              uniforms: {{methodName}}_Uniforms;

    @compute @workgroup_size(64)
    fn {{methodName}}(@builtin(global_invocation_id) global_id: vec3<u32>)
    {
        let index = global_id.x;
        if (index >= uniforms.count) {
            return;
        }
{{query.wgslBody}}    }
    """u8;

"""";
        return shadowMethodSource;
    }
    

}
