// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.Tests;


[Source("~/shaders/tests/compilerErrors.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct HasMissingType (
    MissingType missingType)
{
    public  MissingType missingType = missingType;
}


[Source("~/shaders/tests/compilerErrors.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct HasInvalidPrimitve (
    vec3<i16> invalidVec3)
{
    public  vec3<i16> invalidVec3 = invalidVec3;
}


[Source("~/shaders/tests/compilerErrors.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct InconsistentStruct (
    int value1)
{
    public  int value1 = value1;
}


[Source("~/shaders/tests/compilerErrors.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct InconsistentStruct (
    int value1)
{
    public  int value1 = value1;
}


