// <auto-generated />  path: shaders/tests/complexStructs.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.WGPU;
using System.Numerics;

namespace Shaders.Tests;


[Source("~/shaders/tests/complexStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 160)]
public struct EdgeCaseUniform (uint header, in float_UniArr_3 scalars, in Vector2 padded_vec, in SubItem nested, uint tail_flag)
{
    [FieldOffset(  0)]  public  uint           header     = header;
    [FieldOffset( 16)]  public  float_UniArr_3 scalars    = scalars;
    [FieldOffset( 64)]  public  Vector2        padded_vec = padded_vec;
    [FieldOffset( 96)]  public  SubItem        nested     = nested;
    [FieldOffset(128)]  public  uint           tail_flag  = tail_flag;
}


[Source("~/shaders/tests/complexStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct SubItem (uint flag, Vector3 direction)
{
    [FieldOffset(  0)]  public  uint    flag      = flag;
    [FieldOffset( 16)]  public  Vector3 direction = direction;
}


[Source("~/shaders/tests/complexStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 64)]
public struct EdgeCaseStorage (uint packed_header, float_Array_3 packed_floats, Vector3 position, SmallData_Array_2 struct_array, uint end_marker)
{
    [FieldOffset(  0)]  public  uint              packed_header = packed_header;
    [FieldOffset(  4)]  public  float_Array_3     packed_floats = packed_floats;
    [FieldOffset( 16)]  public  Vector3           position      = position;
    [FieldOffset( 28)]  public  SmallData_Array_2 struct_array  = struct_array;
    [FieldOffset( 48)]  public  uint              end_marker    = end_marker;
}


[Source("~/shaders/tests/complexStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 8)]
public struct SmallData (uint id_and_pad, float value)
{
    [FieldOffset(  0)]  public  uint  id_and_pad = id_and_pad;
    [FieldOffset(  4)]  public  float value      = value;
}


[DebuggerTypeProxy(typeof(FixedArrayDebugView<SmallData>))]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct SmallData_Array_2
{
    public int  Length => 2;
    [FieldOffset(0)]  private SmallData _element0;
    
    public ref SmallData this[int index] {
        [UnscopedRef] get {
            if ((uint)index >= 2) throw new IndexOutOfRangeException();
            return ref Unsafe.AddByteOffset(ref _element0, (nint)index * 8);
        }
    }
    
    [UnscopedRef] public FixedArrayEnumerator<SmallData> GetEnumerator() => new(ref _element0, 8, 16);
}


