// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.Tests;


#error Struct 'EmptyStruct' must contain at least one member. Empty structs are not allowed in WGSL.
[Source("~/shaders/tests/compilerErrors.wgsl")]
file partial class _info;


[Source("~/shaders/tests/compilerErrors.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 0)]
public struct HasMissingType (MissingType missingType)
{
    [FieldOffset(  0)]  public  MissingType missingType = missingType;  // WGSL error - missing type: 'MissingType'
}


[Source("~/shaders/tests/compilerErrors.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 0)]
public struct HasInvalidPrimitive (vec3<i16> invalidVec3)
{
    [FieldOffset(  0)]  public  vec3<i16> invalidVec3 = invalidVec3;  // WGSL error - missing type: 'vec3<i16>'
}


[Source("~/shaders/tests/compilerErrors.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 4)]
public struct InconsistentStruct (int value1)
{
    [FieldOffset(  0)]  public  int value1 = value1;
}


#error Duplicate identifier 'InconsistentStruct'
[Source("~/shaders/tests/compilerErrors.wgsl")]
file partial class _info;


#error Unsupported Struct Layout in 'shaders/tests/compilerErrors.wgsl'
[Source("~/shaders/tests/compilerErrors.wgsl")]
/*
Struct 'DynamicSizedStruct' contains header fields alongside a dynamic array ('array<vec3f>').
Combining header data and dynamic arrays in a single Storage Buffer is intentionally restricted.

REASON:
- The legacy C89/C90 Struct Hack introduces complex byte-alignment and implicit padding issues between C# and WebGPU.
- Merging varying header data with static arrays degrades GPU cache performance.
- It makes usage of buffer header structs very complex and error prone.

RECOMMENDED FIX: Keep your struct as a clean Uniform Header with minimal changes:

1. Keep 'struct DynamicSizedStruct', but remove the dynamic array from it. Remove:
     triangles: array<vec3f>

2. Use 'DynamicSizedStruct' directly as a <uniform> binding for your header data:
     @group(0) @binding(4) var<uniform> trianglesDataUniform : DynamicSizedStruct;

3. Declare the dynamic array as its own standalone <storage> binding:
     @group(0) @binding(5) var<storage, read> trianglesData : array<vec3f>;

4. In your shader functions, replace 'trianglesData.triangles[i]' with 'trianglesData[i]'.
*/
file partial class _info;


[Source("~/shaders/tests/compilerErrors.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 8)]
public struct HasUnmappedType (vec3h unmappedType)
{
    [FieldOffset(  0)]  public  vec3h unmappedType = unmappedType;  // INFO: 'vec3h' requires mapping in 'wgsl-type-map.json'
}


