// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.Tests;


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 0)]
public struct EmptyStruct (
)
{
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 64)]
public struct StructWithStructs (
    ChildStruct child1,
    ChildStruct child2)
{
    [FieldOffset(  0)]  public  ChildStruct child1 = child1;
    [FieldOffset( 32)]  public  ChildStruct child2 = child2;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct ChildStruct (
    Vector3 vector1,
    Vector3 vector2)
{
    [FieldOffset(  0)]  public  Vector3 vector1 = vector1;
    [FieldOffset( 16)]  public  Vector3 vector2 = vector2;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct TestStruct (
    Vector3 vector1,
    Vector3 vector2)
{
    [FieldOffset(  0)]  public  Vector3 vector1 = vector1;
    [FieldOffset( 16)]  public  Vector3 vector2 = vector2;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct Inner (
    Vector3 a,
    float   b)
{
    [FieldOffset(  0)]  public  Vector3 a = a;
    [FieldOffset( 12)]  public  float   b = b;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 48)]
public struct Outer (
    Inner s1,
    float x,
    Inner s2)
{
    [FieldOffset(  0)]  public  Inner s1 = s1;
    [FieldOffset( 16)]  public  float x  = x;
    [FieldOffset( 32)]  public  Inner s2 = s2;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct FixeSizeArrayStruct1 (
    Vector3_Array_16 vectors)
{
    [FieldOffset(  0)]  public  Vector3_Array_16 vectors = vectors;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct FixeSizeArrayStruct2 (
    Vector3          value,
    Vector3_Array_16 vectors)
{
    [FieldOffset(  0)]  public  Vector3          value   = value;
    [FieldOffset( 16)]  public  Vector3_Array_16 vectors = vectors;
}


[InlineArray(16)]
public struct Vector3_Array_16
{
    private Vector3 _element0;
}


/// Skipped identical duplicate of  <see cref="Vector3_Array_16"/>
file partial class _info;


