// <auto-generated />  path: shaders/tests/testStructs2.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using CustomTypes;

namespace Shaders.Tests;


[Source("~/shaders/tests/testStructs2.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 256)]
public struct FixeSizeArray (in Vector2i_array_16_std140 vectors)
{
    [FieldOffset(  0)]  public  Vector2i_array_16_std140 vectors = vectors;
}


