// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.Tests;


[Source("~/shaders/tests/testTextureTypes.frag.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct VertexData (
    Vector3 vertices)
{
    public  Vector3 vertices = vertices;
}


/// Skipped identical duplicate of  <see cref="VertexData"/>
file partial class _info;


