// <auto-generated />
using System;
using System.Numerics;
using Friflo.Vectorization.WebGPU;

namespace Shaders.Tests;


[Source("~/shaders/tests/testParameterTypes.wgsl")]
public struct Uniforms (
    Matrix4x4 modelViewProjectionMatrix)
{
    public Matrix4x4 modelViewProjectionMatrix = modelViewProjectionMatrix;
}

/// Skipped identical duplicate of  <see cref="Uniforms"/>
file partial class _info;

