// <auto-generated />  path: shaders/tests/testStructs2.wgsl.cs
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using CustomTypes;

namespace Shaders.Tests;


[Source("~/shaders/tests/testStructs2.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 256)]
public struct FixeSizeArray (in Vector2i_Array_16 vectors)
{
    [FieldOffset(  0)]  public  Vector2i_Array_16 vectors = vectors;
}


[InlineArray(16)]
public struct Vector2i_Array_16
{
    private Vector2i _element0;
}


