// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.Tests;


[Source("~/shaders/tests/testTextureTypes.frag.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct VertexData (
    Vector3 vertices)
{
    [FieldOffset(  0)]  public  Vector3 vertices = vertices;
}


