// <auto-generated />  path: shaders/tests/testTypeSize.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using System.Numerics;

namespace Shaders.Tests;


/// Skipped identical duplicate of  <see cref="DirectUniform2"/>
file partial class _info;


/// Skipped identical duplicate of  <see cref="DirectUniform2_UniArr_8"/>
file partial class _info;


