// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.Tests;


[Source("~/shaders/tests/testEdgeCases.vert.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct EmptyStruct (
)
{
}


