// <auto-generated />  path: shaders/tests/testStructs.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using System.Numerics;
using CustomTypes;

namespace Shaders.Tests;


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 64)]
public struct StructWithStructs (in ChildStruct child1, in ChildStruct child2)
{
    [FieldOffset(  0)]  public  ChildStruct child1 = child1;
    [FieldOffset( 32)]  public  ChildStruct child2 = child2;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct ChildStruct (Vector3 vector1, Vector3 vector2)
{
    [FieldOffset(  0)]  public  Vector3 vector1 = vector1;
    [FieldOffset( 16)]  public  Vector3 vector2 = vector2;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct TestStruct (Vector3 vector1, Vector3 vector2)
{
    [FieldOffset(  0)]  public  Vector3 vector1 = vector1;
    [FieldOffset( 16)]  public  Vector3 vector2 = vector2;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct Inner (Vector3 a, float b)
{
    [FieldOffset(  0)]  public  Vector3 a = a;
    [FieldOffset( 12)]  public  float   b = b;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 48)]
public struct Outer (Inner s1, float x, Inner s2)
{
    [FieldOffset(  0)]  public  Inner s1 = s1;
    [FieldOffset( 16)]  public  float x  = x;
    [FieldOffset( 32)]  public  Inner s2 = s2;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 256)]
public struct FixeSizeArrayStruct1 (in Vector3_array_16 vectors)
{
    [FieldOffset(  0)]  public  Vector3_array_16 vectors = vectors;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 288)]
public struct FixeSizeArrayStruct2 (Vector3 value1, in Vector3_array_16 vectors, Vector3 value2)
{
    [FieldOffset(  0)]  public  Vector3          value1  = value1;
    [FieldOffset( 16)]  public  Vector3_array_16 vectors = vectors;
    [FieldOffset(272)]  public  Vector3          value2  = value2;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 80)]
public struct VectorInUniform (Vector2i uniform_vector2i, in Vector2i_array_8 uniform_vectors2i, Vector2<uint> uniform_vector2u)
{
    [FieldOffset(  0)]  public  Vector2i         uniform_vector2i  = uniform_vector2i;
    [FieldOffset(  8)]  public  Vector2i_array_8 uniform_vectors2i = uniform_vectors2i;
    [FieldOffset( 72)]  public  Vector2<uint>    uniform_vector2u  = uniform_vector2u;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 80)]
public struct VectorInStorage (Vector2i storage_vector2i, in Vector2i_array_8 storage_vectors2i, Vector2<uint> storage_vector2u)
{
    [FieldOffset(  0)]  public  Vector2i         storage_vector2i  = storage_vector2i;
    [FieldOffset(  8)]  public  Vector2i_array_8 storage_vectors2i = storage_vectors2i;
    [FieldOffset( 72)]  public  Vector2<uint>    storage_vector2u  = storage_vector2u;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 64)]
public struct Particle (uint a, uint flags, float speed, in uint id, uint count)
{
    [FieldOffset(  0)]  public  uint  a     = a;
    [FieldOffset( 16)]  public  uint  flags = flags;
    [FieldOffset( 20)]  public  float speed = speed;
    [FieldOffset( 24)]  public  uint  id    = id;
    [FieldOffset( 56)]  public  uint  count = count;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 4)]
public struct DirectUniform1 (float someValue)
{
    [FieldOffset(  0)]  public  float someValue = someValue;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 4)]
public struct DirectUniform2 (float someValue)
{
    [FieldOffset(  0)]  public  float someValue = someValue;
}


[Source("~/shaders/tests/testStructs.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 4)]
public struct DirectStorage (float someValue)
{
    [FieldOffset(  0)]  public  float someValue = someValue;
}


[DebuggerTypeProxy(typeof(FixedArrayDebugView<DirectUniform2>))]
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct DirectUniform2_array_8
{
    public int  Length => 8;
    [FieldOffset(0)]  private DirectUniform2 _element0;
    
    public ref DirectUniform2 this[int index] {
        [UnscopedRef] get {
            if ((uint)index >= 8) throw new IndexOutOfRangeException();
            return ref Unsafe.AddByteOffset(ref _element0, (nint)index * 4);
        }
    }
    
    [UnscopedRef] public FixedArrayEnumerator<DirectUniform2> GetEnumerator() => new(ref _element0, 4, 32);
}


