// <auto-generated />  path: shaders/tests/testTypeSize2.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using System.Numerics;

namespace Shaders.Tests;


[Source("~/shaders/tests/testTypeSize2.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct Point4f (Vector4 vector4)
{
    [FieldOffset(  0)]  public  Vector4 vector4 = vector4;
}


[Source("~/shaders/tests/testTypeSize2.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct Uniform2Fields (int field1, int field2)
{
    [FieldOffset(  0)]  public  int field1 = field1;
    [FieldOffset(  4)]  public  int field2 = field2;
}


