// <auto-generated />
using System;
using System.Numerics;
using Friflo.Vectorization.WebGPU;

namespace Shaders.Tests;


/// Skipped identical duplicate of  <see cref="Scene"/>
file partial class _info;

/// Skipped identical duplicate of  <see cref="Model"/>
file partial class _info;

[Source("~/shaders/tests/vertexShadowIndirect.wgsl")]
public struct Indirect (
    uint vertexCount,
    uint instanceCount,
    uint firstVertex,
    uint firstInstance)
{
    public uint vertexCount = vertexCount;
    public uint instanceCount = instanceCount;
    public uint firstVertex = firstVertex;
    public uint firstInstance = firstInstance;
}

