// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.Tests;


[Source("~/shaders/tests/vertexShadowIndexedIndirect.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct Scene (
    Matrix4x4 lightViewProjMatrix,
    Matrix4x4 cameraViewProjMatrix,
    Vector3   lightPos)
{
    public  Matrix4x4 lightViewProjMatrix  = lightViewProjMatrix;
    public  Matrix4x4 cameraViewProjMatrix = cameraViewProjMatrix;
    public  Vector3   lightPos             = lightPos;
}


[Source("~/shaders/tests/vertexShadowIndexedIndirect.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct Model (
    Matrix4x4 modelMatrix)
{
    public  Matrix4x4 modelMatrix = modelMatrix;
}


[Source("~/shaders/tests/vertexShadowIndexedIndirect.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct IndexedIndirect (
    uint indexCount,
    uint instanceCount,
    uint firstIndex,
    int  baseVertex,
    uint firstInstance)
{
    public  uint indexCount    = indexCount;
    public  uint instanceCount = instanceCount;
    public  uint firstIndex    = firstIndex;
    public  int  baseVertex    = baseVertex;
    public  uint firstInstance = firstInstance;
}


