// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.Tests;


[Source("~/shaders/tests/vertexShadowIndexedIndirect.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 144)]
public struct Scene (
    Matrix4x4 lightViewProjMatrix,
    Matrix4x4 cameraViewProjMatrix,
    Vector3   lightPos)
{
    [FieldOffset(  0)]  public  Matrix4x4 lightViewProjMatrix  = lightViewProjMatrix;
    [FieldOffset( 64)]  public  Matrix4x4 cameraViewProjMatrix = cameraViewProjMatrix;
    [FieldOffset(128)]  public  Vector3   lightPos             = lightPos;
}


[Source("~/shaders/tests/vertexShadowIndexedIndirect.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 64)]
public struct Model (
    Matrix4x4 modelMatrix)
{
    [FieldOffset(  0)]  public  Matrix4x4 modelMatrix = modelMatrix;
}


[Source("~/shaders/tests/vertexShadowIndexedIndirect.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 20)]
public struct IndexedIndirect (
    uint indexCount,
    uint instanceCount,
    uint firstIndex,
    int  baseVertex,
    uint firstInstance)
{
    [FieldOffset(  0)]  public  uint indexCount    = indexCount;
    [FieldOffset(  4)]  public  uint instanceCount = instanceCount;
    [FieldOffset(  8)]  public  uint firstIndex    = firstIndex;
    [FieldOffset( 12)]  public  int  baseVertex    = baseVertex;
    [FieldOffset( 16)]  public  uint firstInstance = firstInstance;
}


