// <auto-generated />  path: shaders/tests/vertexShadowIndirect.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using System.Numerics;

namespace Shaders.Tests;


/// Skipped identical duplicate of  <see cref="Scene"/>
file partial class _info;


/// Skipped identical duplicate of  <see cref="Model"/>
file partial class _info;


[Source("~/shaders/tests/vertexShadowIndirect.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct Indirect (uint vertexCount, uint instanceCount, uint firstVertex, uint firstInstance)
{
    [FieldOffset(  0)]  public  uint vertexCount   = vertexCount;
    [FieldOffset(  4)]  public  uint instanceCount = instanceCount;
    [FieldOffset(  8)]  public  uint firstVertex   = firstVertex;
    [FieldOffset( 12)]  public  uint firstInstance = firstInstance;
}


