// <auto-generated />  path: shaders/instancedCube/instanced.vert.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using System.Numerics;

namespace Shaders.InstancedCube;


[Source("~/shaders/instancedCube/instanced.vert.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 1024)]
public struct Uniforms (in Matrix4x4_array_16 modelViewProjectionMatrix)
{
    [FieldOffset(  0)]  public  Matrix4x4_array_16 modelViewProjectionMatrix = modelViewProjectionMatrix;
}


