// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.InstancedCube;


[Source("~/shaders/instancedCube/instanced.vert.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 64)]
public struct Uniforms (
    Matrix4x4 modelViewProjectionMatrix)
{
    [FieldOffset(  0)]  public  Matrix4x4 modelViewProjectionMatrix = modelViewProjectionMatrix;
}


