// <auto-generated />
using System;
using System.Numerics;
using Friflo.Vectorization.WebGPU;

namespace Shaders.InstancedCube;


[Source("~/shaders/instancedCube/instanced.vert.wgsl")]
public struct Uniforms (
    Matrix4x4 modelViewProjectionMatrix)
{
    public Matrix4x4 modelViewProjectionMatrix = modelViewProjectionMatrix;
}

