// <auto-generated />  path: wwwroot/draw2d.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.WGPU;
using System.Numerics;

namespace Wwwroot;


[Source("~/wwwroot/draw2d.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 64)]
public struct ImUniforms (in Matrix4x4 projection)
{
    [FieldOffset(  0)]  public  Matrix4x4 projection = projection;
}


