using System.Runtime.CompilerServices;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

// ReSharper disable InconsistentNaming
// ReSharper disable FieldCanBeMadeReadOnly.Global
namespace TestConsole;

public partial class RenderTest
{
    /// method generated by C# source generator
    public static partial void DrawTriangles(
        RenderPass              pass,
        RenderConfig            config,
        InBuffer<VertexData>    triangles,
        MyUniform               myUniform)
	{
        var buffers =
        GpuBuffers.Create(triangles, nameof(triangles));
        
        var pass_       = pass.Internal;
		var recorder	= pass_.Recorder;
		recorder.Init(Triangles_GPU_ShaderId, "Triangles_encoder"u8);
        
        recorder.RequireRead(triangles);

        ref readonly var pipelineCache = ref recorder.Device.GetPipelineCache(Triangles_GPU_ShaderId, config, Triangles_GPU_WgslHash); 
        if (!pipelineCache.IsCreated) {
            pipelineCache = ref Triangles_GPU_CreatePipelineCache(recorder.Device, config);
        }
        pass_.SetPipeline(pipelineCache.renderPipeline);
        
        var bindGroupCache = (Triangles_GPU_Cache)pipelineCache.bindGroupCache;
        
        var key_0 = triangles.Handle;
        if (!bindGroupCache.bindGroup0.TryGetValue(key_0, out var bindGroup0)) {
            recorder.BindGroupEntryBuffer(triangles.Buffer);
            bindGroup0 = recorder.CreateBindGroup(pipelineCache.layouts[0], "Triangles_bindGroup0"u8);
            bindGroupCache.bindGroup0.Add(key_0, bindGroup0);
        }
        pass_.SetBindGroup(0, bindGroup0);
        
        pass_.SetBindGroupUniform(1, ref bindGroupCache.bindGroup1, myUniform, pipelineCache,"Triangles_bindGroup1"u8);
        
        pass_.Draw(triangles.Length, 1, triangles.Offset, 0);
	}
    
    private sealed class Triangles_GPU_Cache : BindGroupCache
    {
        internal readonly   Dictionary<nint,    WgpuBindGroup>    bindGroup0 = new ();
        internal            WgpuBindGroup                         bindGroup1;
        
        protected override void Clear() {
            ReleaseBindGroups(bindGroup0);
            ReleaseBindGroup(ref bindGroup1);
        }
    }
    
    private static readonly int Triangles_GPU_ShaderId      =  ShaderRegistry.NewShaderId("TrianglesShader");
    private const  ulong        Triangles_GPU_layout_0_key  =  0x47;  // unique key set by Generator
    private const  ulong        Triangles_GPU_layout_1_key  =  0x11;  // unique key set by Generator
    private static ulong        Triangles_GPU_WgslHash      => 0x123; // support Hot-Relead
    
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref readonly PipelineCache Triangles_GPU_CreatePipelineCache(WgpuDevice device, RenderConfig config)
    {
        var layout_0 = device.GetBindGroupLayout(Triangles_GPU_layout_0_key);
        if (!layout_0.IsCreated) {
            device.BindGroupLayoutBuffer(BufferBindingType.ReadOnlyStorage);
            layout_0 = device.CreateBindGroupLayout(ShaderStage.Vertex, Triangles_GPU_layout_0_key, "Triangles_layout_0"u8);
        }
        var layout_1 = device.GetBindGroupLayout(Triangles_GPU_layout_1_key);
        if (!layout_1.IsCreated) {
            device.BindGroupLayoutUniform();
            layout_1 = device.CreateBindGroupLayout(ShaderStage.Vertex, Triangles_GPU_layout_1_key, "Triangles_layout_1"u8);
        }
        using var module = device.CreateShaderModule(Triangles_GPU_Shader(), "Triangles_shader"u8);
        
        Span<WgpuBindGroupLayout> layouts = stackalloc WgpuBindGroupLayout[2];
        layouts[0] = layout_0;
        layouts[1] = layout_1;

        var pipeline = device.CreateRenderPipeline(layouts, config, module, "vs_main"u8, module, "fs_main"u8, "Triangles_pipeline"u8);
        
        var bindGroupCache = new Triangles_GPU_Cache();
        
        return ref device.CreatePipelineCache(Triangles_GPU_ShaderId, config, Triangles_GPU_WgslHash, pipeline, layouts, bindGroupCache);
    }
    
    private static ReadOnlySpan<byte> Triangles_GPU_Shader() => WgpuResource.GetResource(typeof(RenderTest), "Tests-Console.shaders.triangle.wgsl");
}