using System.Runtime.CompilerServices;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

// ReSharper disable ConvertToConstant.Local
// ReSharper disable FieldCanBeMadeReadOnly.Local
// ReSharper disable InconsistentNaming
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable UnusedParameter.Local
// ReSharper disable UnusedMember.Local
// ReSharper disable FieldCanBeMadeReadOnly.Global
namespace TestConsole;

public partial class TextureTest
{
    private static bool enabled = false; // TODO remove
    
    /// method generated by C# source generator
    protected static partial void RenderSubmarine(
        RenderPass<MainWorld>   renderPass,
        InBuffer<float>         verticesBuffer,
        RenderConfig            vertexConfig,
        in Uniforms             uniforms,
        FilteringSampler        smoothFilter,
        texture_2d<float>       material)
	{
        if (!enabled) return;
        
        var buffers =
        GpuBuffers.Create(verticesBuffer, nameof(verticesBuffer));
        
        var pass        = renderPass.Value;
		var recorder	= pass.Recorder;
		var device		= recorder.Device;
		recorder.Init(TextureTest_GPU_ShaderId, "TextureTest"u8);
        
        recorder.RequireRead(verticesBuffer);

        ref var effect = ref device.GetShaderEffect(TextureTest_GPU_ShaderId, vertexConfig, TextureTest_GPU_WgslHash); // Each device has its own GpuEffect[] array
        if (!effect.IsCreated) {
            effect = ref TextureTest_GPU_CreateEffect(device, vertexConfig);
        }
        pass.SetPipeline(effect.renderPipeline);
        
        // Creation of a buffer bind group is expensive in wgpu. So we cache them. Cache has two entries.
        /*
        var bufferGroup = effect.bufferCache.GetGroup(buffers.hash);
        if (!bufferGroup.IsCreated) {
            Span<BindGroupEntry> entries = stackalloc BindGroupEntry[1];
            entries[0]  = WgpuBindGroup.From  (0, verticesBuffer.Buffer);
            bufferGroup = recorder.CreateBindGroup(effect.bufferLayout, entries, "TriangleStorage"u8);
            device.UpdateShaderCache(ref effect, bufferGroup, buffers.hash);
        }
        pass.SetBindGroup(0, bufferGroup, buffers.hash);                    // [BindVertex(0, x)]
        */
        pass.SetUniformBindGroup(0, ref effect, uniforms, "Uniforms"u8);
        
        pass.SetVertexBuffer(0, verticesBuffer);
        
        pass.Draw(buffers.length, 0, 0, 0);
	}
    
    private static readonly int TextureTest_GPU_ShaderId            =  ShaderRegistry.NewShaderId("TextureTestShader");
    private const  ulong        TextureTest_GPU_layout_0_Key        =  0x4755;  // unique key set by Generator
    private const  ulong        TextureTest_GPU_UniformLayoutKey    =  0x1155;  // unique key set by Generator
    private static ulong        TextureTest_GPU_WgslHash            => 0x1255;  // support Hot-Relead
    
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref WgpuShaderEffect TextureTest_GPU_CreateEffect(WgpuDevice device, RenderConfig config)
    {
        var layout_0 = device.GetBindGroupLayout(TextureTest_GPU_layout_0_Key);
        if (!layout_0.IsCreated) {
            Span<WgpuLayoutEntry> entries = stackalloc WgpuLayoutEntry[3];
            entries[0] = WgpuLayoutEntry.Uniform (0);
            entries[1] = WgpuLayoutEntry.Sampler (1, SamplerBindingType.Filtering);
            entries[2] = WgpuLayoutEntry.Texture (2, TextureSampleType.Float, TextureViewDimension.D2D, false);
            layout_0 = device.CreateBindGroupLayout(entries, ShaderStage.Vertex | ShaderStage.Fragment, false, TextureTest_GPU_layout_0_Key, "TextureTest_layout_0"u8);
        }
        var vsModule = device.CreateShaderModule(TextureTest_GPU_VertexShader(),   "TextureTest_VertexShader"u8);
        var fsModule = device.CreateShaderModule(TextureTest_GPU_FragmentShader(), "TextureTest_FragmentShader"u8);
        
        Span<WgpuBindGroupLayout> layouts = stackalloc WgpuBindGroupLayout[1];
        layouts[0] = layout_0;      // [BindVertex (0, x)]

        var pipeline = device.CreateRenderPipeline(layouts, config, vsModule, "main"u8, fsModule, "main"u8, "TextureTest"u8);

        var bufferLayout = new WgpuBindGroupLayout();      // TODO remove
        return ref device.CreateShaderEffect(TextureTest_GPU_ShaderId, config, TextureTest_GPU_WgslHash, pipeline, bufferLayout, layout_0);
    }
    
    private static ReadOnlySpan<byte> TextureTest_GPU_VertexShader()   => WgpuResource.GetResource(typeof(RenderTest).Assembly, "Tests-Console.shaders.basic.vert.wgsl");
    private static ReadOnlySpan<byte> TextureTest_GPU_FragmentShader() => WgpuResource.GetResource(typeof(RenderTest).Assembly, "Tests-Console.shaders.sampleTextureMixColor.frag.wgsl");
}