using System.Runtime.CompilerServices;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

// ReSharper disable InconsistentNaming
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable UnusedParameter.Local
// ReSharper disable UnusedMember.Local
// ReSharper disable FieldCanBeMadeReadOnly.Global
namespace TestConsole;

public partial class TextureTest
{
    /// method generated by C# source generator
    protected static partial void RenderSubmarine(
        RenderPass<MainWorld>   renderPass,
        in Uniforms             uniforms,
        FilteringSampler        smoothFilter,
        texture_2d<float>       material)
	{
        /*
        var buffers =
        GpuBuffers.Create(triangles, nameof(triangles));
        
        var pass        = renderPass.Value;
		var recorder	= pass.Recorder;
		var device		= recorder.Device;
		recorder.Init(TextureTest_GPU_ShaderId, "TextureTest"u8);
        
        recorder.RequireRead(triangles);

        ref var effect = ref device.GetShaderEffect(TextureTest_GPU_ShaderId, pass.Config, TextureTest_GPU_WgslHash); // Each device has its own GpuEffect[] array
        if (!effect.IsCreated) {
            effect = ref TextureTest_GPU_CreateEffect(device, pass.Config);
        }
        pass.SetPipeline(effect.renderPipeline);
        
        // Creation of a buffer bind group is expensive in wgpu. So we cache them. Cache has two entries.
        var bufferGroup = effect.bufferCache.GetGroup(buffers.hash);
        if (!bufferGroup.IsCreated) {
            Span<BindGroupEntry> entries = stackalloc BindGroupEntry[1];
            entries[0] = WgpuBindGroup.From  (0, triangles.Buffer);
            bufferGroup = recorder.CreateBindGroup(effect.bufferLayout, entries, "TriangleStorage"u8);
            device.UpdateShaderCache(ref effect, bufferGroup, buffers.hash);
        }
        pass.SetBindGroup(0, bufferGroup, buffers.hash);                    // [BindVertex(0, x)]
        
        pass.SetUniformBindGroup(1, ref effect, myUniform, "MyUniforms"u8); // [BindUniform(1, x)]
        
        pass.Draw(buffers.length, 1, triangles.Offset, 0);
        */
	}
    
    private static readonly int TextureTest_GPU_ShaderId            =  ShaderRegistry.NewShaderId("TextureTestShader");
    private const ulong         TextureTest_GPU_BufferLayoutKey     =  0x47;  // unique key set by Generator
    private const ulong         TextureTest_GPU_UniformLayoutKey    =  0x11;  // unique key set by Generator
    private static ulong        TextureTest_GPU_WgslHash            => 0x123; // support Hot-Relead
    
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref WgpuShaderEffect TextureTest_GPU_CreateEffect(WgpuDevice device, RenderConfig config)
    {
        var bufferLayout = device.GetBindGroupLayout(TextureTest_GPU_BufferLayoutKey);
        if (!bufferLayout.IsCreated) {
            Span<WgpuLayoutEntry> buffers = stackalloc WgpuLayoutEntry[1];
            buffers[0] = WgpuLayoutEntry.ReadOnlyStorage (0);   // [BindVertex(x, 0)] @group(0) @binding(0) var<storage, read> mesh_data: TriangleStorage;
            bufferLayout = device.CreateBindGroupLayout(buffers, ShaderStage.Vertex, false, TextureTest_GPU_BufferLayoutKey, "TriangleStorage"u8);
        }
        var uniformLayout = device.GetBindGroupLayout(TextureTest_GPU_UniformLayoutKey);
        if (!uniformLayout.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0] = WgpuLayoutEntry.Uniform(0);            // [BindUniform(x, 0)] @group(1) @binding(0) var<uniform>          myUniforms: MyUniforms;
            uniformLayout = device.CreateBindGroupLayout(uniform, ShaderStage.Vertex, true, TextureTest_GPU_UniformLayoutKey, "MyUniforms"u8);
        }
        var module = device.CreateShaderModule(TextureTest_GPU_Shader(), "TextureTest"u8);
        
        Span<WgpuBindGroupLayout> layouts = stackalloc WgpuBindGroupLayout[2];
        layouts[0] = bufferLayout;      // [BindVertex (0, x)]
        layouts[1] = uniformLayout;     // [BindUniform(1, x)]

        var pipeline = device.CreateRenderPipeline(layouts, config, module, "vs_main"u8, module, "fs_main"u8, "TextureTest"u8);
        
        return ref device.CreateShaderEffect(TextureTest_GPU_ShaderId, config, TextureTest_GPU_WgslHash, pipeline, bufferLayout, uniformLayout);
    }
    
    private static ReadOnlySpan<byte> TextureTest_GPU_Shader() => WgpuResource.GetResource(typeof(RenderTest).Assembly, "Tests-Console.shaders.triangle.wgsl");
}