using System.Runtime.CompilerServices;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

// ReSharper disable InconsistentNaming
namespace TestConsole;

public partial class TextureTest
{
    /// method generated by C# source generator
    protected static partial void RenderCube(
        RenderPass<MainWorld>   renderPass,
        RenderConfig            vertexConfig,
        InBuffer<float>         verticesBuffer,
        in Uniforms             uniforms,
        GpuSampler              smoothFilter,
        GpuTextureView          material)
	{
        var buffers =
        GpuBuffers.Create(verticesBuffer, nameof(verticesBuffer));
        
        var pass        = renderPass.Value;
		var recorder	= pass.Recorder;
		var device		= recorder.Device;
		recorder.Init(TextureTest_GPU_ShaderId, "TextureTest_encoder"u8);
        
        recorder.RequireRead(verticesBuffer);

        ref readonly var pipelineCache = ref device.GetPipelineCache(TextureTest_GPU_ShaderId, vertexConfig, TextureTest_GPU_WgslHash);
        if (!pipelineCache.IsCreated) {
            pipelineCache = ref TextureTest_GPU_CreatePipelineCache(device, vertexConfig);
        }
        
        pass.SetPipeline(pipelineCache.renderPipeline);
        
        var bindGroupCache = (TextureTest_GPU_Cache)pipelineCache.bindGroupCache;
        
        var key_0 = (smoothFilter.Handle, material.Handle);
        if (!bindGroupCache.bindGroup0.TryGetValue(key_0, out var bindGroup0)) {
            recorder.BindGroupEntryUniform<Uniforms>();
            recorder.BindGroupEntrySampler(smoothFilter);
            recorder.BindGroupEntryTexture(material.Handle);
            bindGroup0 = recorder.CreateBindGroup(pipelineCache.layouts[0], "TextureTest_bindGroup0"u8);
            bindGroupCache.bindGroup0.Add(key_0, bindGroup0);
        }
        pass.SetBindGroupUniform(0, bindGroup0, uniforms);
        
        int verticesBufferCount = pass.SetVertexBuffer(vertexConfig, 0, verticesBuffer); // slot: 0 - [VertexBuffer(0)]  references:  desc.VertexState.buffers[0]
   
        pass.Draw(verticesBufferCount, 1, 0, 0);
	}
    
    private sealed class TextureTest_GPU_Cache : BindGroupCache
    {
        internal readonly   Dictionary<(nint,nint), WgpuBindGroup>    bindGroup0 = new ();
        
        protected override void Clear() {
            ReleaseBindGroups(bindGroup0);
        }
    }
    
    private static readonly int TextureTest_GPU_ShaderId            =  ShaderRegistry.NewShaderId("TextureTestShader");
    private const  ulong        TextureTest_GPU_layout_0_Key        =  0x4755;  // unique key set by Generator
    private static ulong        TextureTest_GPU_WgslHash            => 0x1255;  // support Hot-Relead
    
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref readonly PipelineCache TextureTest_GPU_CreatePipelineCache(WgpuDevice device, RenderConfig config)
    {
        var layout_0 = device.GetBindGroupLayout(TextureTest_GPU_layout_0_Key);
        if (!layout_0.IsCreated) {
            device.BindGroupLayoutUniform();
            device.BindGroupLayoutSampler(SamplerBindingType.Filtering);
            device.BindGroupLayoutTexture(TextureSampleType.Float, TextureViewDimension.D2D, false);
            layout_0 = device.CreateBindGroupLayout(ShaderStage.Vertex | ShaderStage.Fragment, TextureTest_GPU_layout_0_Key, "TextureTest_layout_0"u8);
        }
        using var vsModule = device.CreateShaderModule(TextureTest_GPU_VertexShader(),   "TextureTest_VertexShader"u8);
        using var fsModule = device.CreateShaderModule(TextureTest_GPU_FragmentShader(), "TextureTest_FragmentShader"u8);
        
        Span<WgpuBindGroupLayout> layouts = stackalloc WgpuBindGroupLayout[1];
        layouts[0] = layout_0;

        var pipeline = device.CreateRenderPipeline(layouts, config, vsModule, "main"u8, fsModule, "main"u8, "TextureTest_pipeline"u8);

        var bindGroupCache = new TextureTest_GPU_Cache();
        return ref device.CreatePipelineCache(TextureTest_GPU_ShaderId, config, TextureTest_GPU_WgslHash, pipeline, layouts, bindGroupCache);
    }
    
    private static ReadOnlySpan<byte> TextureTest_GPU_VertexShader()   => WgpuResource.GetResource(typeof(RenderTest).Assembly, "Tests-Console.shaders.basic.vert.wgsl");
    private static ReadOnlySpan<byte> TextureTest_GPU_FragmentShader() => WgpuResource.GetResource(typeof(RenderTest).Assembly, "Tests-Console.shaders.sampleTextureMixColor.frag.wgsl");
}