using System.Runtime.CompilerServices;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

// ReSharper disable InconsistentNaming
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable UnusedParameter.Local
// ReSharper disable UnusedMember.Local
// ReSharper disable FieldCanBeMadeReadOnly.Global
namespace TestConsole;

public partial class RenderTest
{
    /// method generated by C# source generator
    public static partial void DrawTriangles(
        RenderPass<MainWorld>   renderPass,
        InBuffer<VertexData>    triangles,
        MyUniform               myUniform)
	{
        var buffers =
        GpuBuffers.Create(triangles, nameof(triangles));
        
        var pass        = renderPass.Value;
		var recorder	= pass.Recorder;
		var device		= recorder.Device;
		recorder.Init(Triangles_GPU_ShaderId, "Triangles"u8);
        
        recorder.RequireRead(triangles);

        ref var effect = ref device.GetShaderEffect(Triangles_GPU_ShaderId, pass.Config, Triangles_GPU_WgslHash); // Each device has its own GpuEffect[] array
        if (!effect.IsCreated) {
            effect = ref Triangles_GPU_CreateEffect(device, pass.Config);
        }
        pass.SetPipeline(effect.renderPipeline);
        
        // Creation of a buffer bind group is expensive in wgpu. So we cache them. Cache has two entries.
        var bufferGroup = effect.bufferCache.GetGroup(buffers.hash);
        if (!bufferGroup.IsCreated) {
            Span<BindGroupEntry> entries = stackalloc BindGroupEntry[1];
            entries[0] = WgpuBindGroup.From  (0, triangles.Buffer);
            bufferGroup = recorder.CreateBindGroup(effect.bufferLayout, entries, "TriangleStorage"u8);
            device.UpdateShaderCache(ref effect, bufferGroup, buffers.hash);
        }
        pass.SetBindGroup(0, bufferGroup, buffers.hash);
        
        pass.SetUniformBindGroup(1, ref effect, myUniform, "MyUniforms"u8);
        
        pass.Draw(buffers.length, 1, triangles.Offset, 0);
	}
    
    private static readonly int Triangles_GPU_ShaderId      =  ShaderRegistry.NewShaderId("TrianglesShader");
    private const  ulong        Triangles_GPU_layout_0_key  =  0x47;  // unique key set by Generator
    private const  ulong        Triangles_GPU_layout_1_key  =  0x11;  // unique key set by Generator
    private static ulong        Triangles_GPU_WgslHash      => 0x123; // support Hot-Relead
    
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref WgpuShaderEffect Triangles_GPU_CreateEffect(WgpuDevice device, RenderConfig config)
    {
        var layout_0 = device.GetBindGroupLayout(Triangles_GPU_layout_0_key);
        if (!layout_0.IsCreated) {
            Span<WgpuLayoutEntry> buffers = stackalloc WgpuLayoutEntry[1];
            buffers[0] = WgpuLayoutEntry.ReadOnlyStorage (0);
            layout_0 = device.CreateBindGroupLayout(buffers, ShaderStage.Vertex, false, Triangles_GPU_layout_0_key, "Triangles_layout_0"u8);
        }
        var layout_1 = device.GetBindGroupLayout(Triangles_GPU_layout_1_key);
        if (!layout_1.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0] = WgpuLayoutEntry.Uniform(0);
            layout_1 = device.CreateBindGroupLayout(uniform, ShaderStage.Vertex, true, Triangles_GPU_layout_1_key, "Triangles_layout_1"u8);
        }
        var module = device.CreateShaderModule(Triangles_GPU_Shader(), "Triangles_Shader"u8);
        
        Span<WgpuBindGroupLayout> layouts = stackalloc WgpuBindGroupLayout[2];
        layouts[0] = layout_0;
        layouts[1] = layout_1;

        var pipeline = device.CreateRenderPipeline(layouts, config, module, "vs_main"u8, module, "fs_main"u8, "Triangles_pipeline"u8);
        
        return ref device.CreateShaderEffect(Triangles_GPU_ShaderId, config, Triangles_GPU_WgslHash, pipeline, layout_0, layout_1);
    }
    
    private static ReadOnlySpan<byte> Triangles_GPU_Shader() => WgpuResource.GetResource(typeof(RenderTest).Assembly, "Tests-Console.shaders.triangle.wgsl");
}