using System.Runtime.CompilerServices;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

// ReSharper disable InconsistentNaming
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable UnusedParameter.Local
// ReSharper disable UnusedMember.Local
// ReSharper disable FieldCanBeMadeReadOnly.Global
namespace TestConsole;

public static partial class Wormhood
{
    /// method generated by C# source generator
    public static partial void RenderTunnel(
        RenderPass<MainWorld>   renderPass,
        ShadertoyUniforms       uniforms)
	{
        var pass        = renderPass.Value;
		var recorder	= pass.recorder;
		var device		= recorder.Device;
		recorder.Init(Wormhood_GPU_ShaderId, "Wormhood"u8);

        // TODO  use config in GetShaderEffect()
        ref var effect = ref device.GetShaderEffect(Wormhood_GPU_ShaderId, Wormhood_GPU_WgslHash); // Each device has its own GpuEffect[] array
        if (!effect.IsCreated) {
            effect = ref Wormhood_GPU_CreateEffect(device, pass.Config);
        }
        pass.SetPipeline(effect.renderPipeline);
        
        pass.SetUniformBindGroup(0, ref effect, uniforms, "MyUniforms"u8);
        
        pass.Draw(3, 1, 0, 0);
	}
    
    private static readonly int Wormhood_GPU_ShaderId            =  ShaderRegistry.NewShaderId("WormhoodShader");
    private const ulong         Wormhood_GPU_BufferLayoutKey     =  0x4744;  // unique key set by Generator
    private const ulong         Wormhood_GPU_UniformLayoutKey    =  0x1144;  // unique key set by Generator
    private static ulong        Wormhood_GPU_WgslHash            => 0x1244; // support Hot-Relead
    
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref WgpuShaderEffect Wormhood_GPU_CreateEffect(WgpuDevice device, RenderConfig config)
    {
        /* var bufferLayout = device.GetBindGroupLayout(Wormhood_GPU_BufferLayoutKey);
        if (!bufferLayout.IsCreated) {
            Span<WgpuLayoutEntry> buffers = stackalloc WgpuLayoutEntry[1];
            buffers[0] = WgpuLayoutEntry.ReadOnlyStorage (0);
            bufferLayout = device.CreateBindGroupLayout(buffers, ShaderStage.Vertex, false, Wormhood_GPU_BufferLayoutKey, "TriangleStorage"u8);
        } */
        var uniformLayout = device.GetBindGroupLayout(Wormhood_GPU_UniformLayoutKey);
        if (!uniformLayout.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0] = WgpuLayoutEntry.Uniform(0);            // [Binding(x, 0)] @group(1) @binding(0) var<uniform>          myUniforms: MyUniforms;
            uniformLayout = device.CreateBindGroupLayout(uniform, ShaderStage.Fragment, true, Wormhood_GPU_UniformLayoutKey, "MyUniforms"u8);
        }
        var shaderModule = device.CreateShaderModule(Wormhood_GPU_Shader(), "Wormhood"u8);
        
        Span<WgpuBindGroupLayout> layouts = stackalloc WgpuBindGroupLayout[1];
        layouts[0] = uniformLayout;     // [Binding(1, x)]

        var pipeline = device.CreateRenderPipeline(shaderModule, layouts, config, "vs_main"u8, "fs_main"u8, "Wormhood"u8);
        
        return ref device.CreateShaderEffect(Wormhood_GPU_ShaderId, Wormhood_GPU_WgslHash, pipeline, default, uniformLayout);
    }
    
    private static ReadOnlySpan<byte> Wormhood_GPU_Shader() => WgpuResource.GetResource(typeof(RenderTest).Assembly, "Tests-Console.Shaders.raymarcher_no_texture.wgsl");
}