using System.Runtime.CompilerServices;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

// ReSharper disable InconsistentNaming
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable UnusedParameter.Local
// ReSharper disable UnusedMember.Local
// ReSharper disable FieldCanBeMadeReadOnly.Global
namespace TestConsole;

public static partial class Wormhood
{
    /// method generated by C# source generator
    public static partial void RenderTunnel(
        RenderPass<MainWorld>   renderPass,
        Uniforms       			uniforms)
	{
        var pass        = renderPass.Value;
		var recorder	= pass.Recorder;
		var device		= recorder.Device;
		recorder.Init(Wormhood_GPU_ShaderId, "Wormhood"u8);

        ref var effect = ref device.GetShaderEffect(Wormhood_GPU_ShaderId, pass.Config, Wormhood_GPU_WgslHash); // Each device has its own GpuEffect[] array
        if (!effect.IsCreated) {
            effect = ref Wormhood_GPU_CreateEffect(device, pass.Config);
        }
        pass.SetPipeline(effect.renderPipeline);
        
        pass.SetUniformBindGroup(0, ref effect, uniforms, "MyUniforms"u8);  // [BindUniform(0, x)]
        
        pass.Draw(3, 1, 0, 0); // [DrawFullscreenTriangle] with out-of-bounds vertices, 0 overdraw
	}
    
    private static readonly int Wormhood_GPU_ShaderId       =  ShaderRegistry.NewShaderId("WormhoodShader");
    private const  ulong        Wormhood_GPU_layout_0_key   =  0x1144;  // unique key set by Generator
    private static ulong        Wormhood_GPU_WgslHash       => 0x1244; // support Hot-Relead
    
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref WgpuShaderEffect Wormhood_GPU_CreateEffect(WgpuDevice device, RenderConfig config)
    {
        var layout_0 = device.GetBindGroupLayout(Wormhood_GPU_layout_0_key);
        if (!layout_0.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0] = WgpuLayoutEntry.Uniform(0);
            layout_0 = device.CreateBindGroupLayout(uniform, ShaderStage.Fragment, true, Wormhood_GPU_layout_0_key, "Wormhood_layout_0"u8);
        }
        var module = device.CreateShaderModule(Wormhood_GPU_Shader(), "Wormhood_Shader"u8);
        
        Span<WgpuBindGroupLayout> layouts = stackalloc WgpuBindGroupLayout[1];
        layouts[0] = layout_0;

        var pipeline = device.CreateRenderPipeline(layouts, config, module, "vs_main"u8, module, "fs_main"u8, "Wormhood_pipeline"u8);
        
        return ref device.CreateShaderEffect(Wormhood_GPU_ShaderId, config, Wormhood_GPU_WgslHash, pipeline, default, layout_0);
    }
    
    private static ReadOnlySpan<byte> Wormhood_GPU_Shader() => WgpuResource.GetResource(typeof(RenderTest).Assembly, "Tests-Console.shaders.raymarcher_no_texture.wgsl");
}