//HintName: VerifyVectorize/Kernel_Sign_Example/KernelOnly.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Collections.Generic;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

namespace VerifyVectorize
{
    public partial class Kernel_Sign_Example
    {
        /// <summary>Kernel method generated by: <see cref="KernelOnly"/>.</summary>
        public void KernelOnlyKernel(
            InOutBuffer<float> position,
            float value,
            ComputeMode mode = ComputeMode.Device)
        {
            var buffers =
            GpuBuffers.Create(position, nameof(position), mode);

            if (buffers.ComputeGPU) {
                _KernelOnly_GPU(buffers, position, value);
                return;
            }
            KernelOnlyVector(position.Span, value, buffers.ComputeSIMD);
        }

        /// <summary>Vector method generated for: <see cref="KernelOnly"/>.</summary>
        public void KernelOnlyVector(Span<float> position, float value, bool vectorized = true)
        {
            int count = position.Length;
            for (int n = 0; n < count; n++) {
                KernelOnly(ref position[n], value);
            }
        }

    #region private members

    // Lock-free, zero-alloc GPU kernel with deferred, on-the-fly hazard-driven pass batching
    private void _KernelOnly_GPU(
        in GpuBuffers      buffers,
        in InOutBuffer<float> position,
        in float           value)
    {
        var device   = (WgpuDevice)buffers.device;
        var recorder = device.Recorder;
        recorder.InitKernel(_KernelOnly_GPU_KernelId, "KernelOnly"u8);

        recorder.RequireReadWrite(position);

        using var pass = recorder.BeginComputePass("KernelOnly"u8);
        
        ref readonly var pipelineCache = ref device.GetPipelineCache(_KernelOnly_GPU_KernelId, _KernelOnly_GPU_WgslHash);
        if (!pipelineCache.IsCreated) {
            pipelineCache = ref _KernelOnly_GPU_CreateComputeCache(device);
        }
        pass.SetPipeline(pipelineCache.computePipeline);

        var bindGroupCache = (_KernelOnly_GPU_Cache)pipelineCache.bindGroupCache;
        
        var key = position.Handle;
        if (!bindGroupCache.bufferGroup.TryGetValue(key, out var bufferGroup))
        {
            recorder.BindGroupEntryBuffer(0, position.Buffer);
            bufferGroup = recorder.CreateBindGroup(pipelineCache.layouts[0], "KernelOnly_buffers"u8);
            bindGroupCache.bufferGroup.Add(key, bufferGroup);
        }
        pass.SetBindGroup(0, bufferGroup);
        
        var uniforms = new _KernelOnly_GPU_Uniforms {
            count           = buffers.length,
            position_off    = position.Offset,
            value           = value,
        };
        pass.SetBindGroupUniform(1, 0, ref bindGroupCache.uniformGroup, uniforms, pipelineCache, "KernelOnly_uniforms"u8);
        
        pass.DispatchWorkgroups((buffers.length + 63) / 64, 1, 1);
    }

    private sealed class _KernelOnly_GPU_Cache : BindGroupCache
    {
        internal readonly   Dictionary<nint, WgpuBindGroup> bufferGroup = new ();
        internal            WgpuBindGroup uniformGroup;
        
        protected override void Clear() {
            ReleaseBindGroups(bufferGroup);
            ReleaseBindGroup(ref uniformGroup);
        }
    }
    
    [StructLayout(LayoutKind.Explicit, Size = 16)]  // WGSL layout: std140/std430
    private struct _KernelOnly_GPU_Uniforms
    {
        [FieldOffset( 0)]    public int        count;
        [FieldOffset( 4)]    public int        position_off;
        [FieldOffset( 8)]    public float      value;
    }
    
    private static readonly int _KernelOnly_GPU_KernelId           =  KernelRegistry.NewKernelId("KernelOnlyKernel");
    private const  ulong        _KernelOnly_GPU_BufferLayoutKey    =  0x8328507b4eb6ad4;
    private const  ulong        _KernelOnly_GPU_UniformLayoutKey   =  0xeab614e96837d407;
    private static ulong        _KernelOnly_GPU_WgslHash           => 0xa85ee513a18c92aa;

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref readonly ComputeCache _KernelOnly_GPU_CreateComputeCache(WgpuDevice device)
    {
        // @group(0)
        var bufferLayout = device.GetBindGroupLayout(_KernelOnly_GPU_BufferLayoutKey);
        if (!bufferLayout.IsCreated)
        {
            device.BindGroupLayoutBuffer(0, BufferBindingType.Storage);         // var<storage, read_write>  position_arr: array<f32>;
            bufferLayout = device.CreateBindGroupLayout(ShaderStage.Compute, _KernelOnly_GPU_BufferLayoutKey, "KernelOnly_buffers"u8);
        }
        // @group(1)
        var uniformLayout = device.GetBindGroupLayout(_KernelOnly_GPU_UniformLayoutKey);
        if (!uniformLayout.IsCreated) {
            device.BindGroupLayoutUniform(0);  // var<uniform>              uniforms
            uniformLayout = device.CreateBindGroupLayout(ShaderStage.Compute, _KernelOnly_GPU_UniformLayoutKey, "KernelOnly_uniforms"u8);
        }
        using var shaderModule  = device.CreateShaderModule(_KernelOnly_GPU_Shader(), "KernelOnly"u8);
        var pipeline            = device.CreateComputePipeline(shaderModule, bufferLayout, uniformLayout, "KernelOnly"u8);
        
        var bindGroupCache = new _KernelOnly_GPU_Cache();
        return ref device.CreateComputeCache(_KernelOnly_GPU_KernelId, _KernelOnly_GPU_WgslHash, pipeline, bufferLayout, uniformLayout, bindGroupCache);
    }

    private static ReadOnlySpan<byte> _KernelOnly_GPU_Shader() =>
    """
    struct KernelOnly_Uniforms {
        count           : u32,           // offset:  0 size:  4
        position_off    : u32,           // offset:  4 size:  4
        value           : f32,           // offset:  8 size:  4
    };                                   //            size: 16
    
    @group(0) @binding(0) var<storage, read_write>  position_arr: array<f32>;

    @group(1) @binding(0) var<uniform>              uniforms: KernelOnly_Uniforms;

    @compute @workgroup_size(64)
    fn KernelOnly(@builtin(global_invocation_id) global_id: vec3<u32>)
    {
        let index = global_id.x;
        if (index >= uniforms.count) {
            return;
        }
        var _position = position_arr[uniforms.position_off + index];
        var _value = uniforms.value;

        var _sign = sign(_value);
        _position = _sign;

        position_arr[uniforms.position_off + index] = _position;
    }
    """u8;

    #endregion
    }
}
