//HintName: VerifyVectorize/MyExample/MoveExample.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Kernel method generated by: <see cref="MoveExample"/>.</summary>
        public void MoveExampleKernel(
            InOutBuffer<float> position,
            float deltaTime,
            ComputeMode mode = ComputeMode.Device)
        {
            var buffers =
            GpuBuffers.Create(position, nameof(position), mode);

            if (buffers.ComputeGPU) {
                _MoveExample_GPU(buffers, position, deltaTime);
                return;
            }
            MoveExampleVector(position.Span, deltaTime, buffers.ComputeSIMD);
        }

        /// <summary>Vector method generated for: <see cref="MoveExample"/>.</summary>
        public void MoveExampleVector(Span<float> position, float deltaTime, bool vectorized = true)
        {
            int count = position.Length;
            int n = 0;
            if (vectorized) {
                if (Avx.IsSupported) {
                    n = _MoveExample_Avx(count, position, deltaTime);
                }
            }
            for (; n < count; n++) {
                MoveExample(ref position[n], deltaTime);
            }
        }

    #region private members

        // [Layout: AoS-Vertical]  - lane-native speed
        [SkipLocalsInit]
        private static unsafe int _MoveExample_Avx(int count,
            Span<float> position,
            float deltaTime)
        {
            int i = 0;
            count -= 32;
            if (i > count) {
                return 0;
            }
            if (position.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(position));

            // --- Locals
            var deltaTime_scalar = Vector256.Create(deltaTime);

            fixed (float* position_first = position)
            {
                float* position_ptr = (float*)position_first;

                for (; i <= count; i += 32)
                {
                    // --- 1. Load
                    Vector256<float> position_0;  // Single
                    Vector256<float> position_1;  // Single
                    Vector256<float> position_2;  // Single
                    Vector256<float> position_3;  // Single

                    // --- 2. Compute
                    // var local = deltaTime;
                    var local_0 = deltaTime_scalar;
                    var local_1 = deltaTime_scalar;
                    var local_2 = deltaTime_scalar;
                    var local_3 = deltaTime_scalar;

                    // position = local;
                    position_0 = local_0;
                    position_1 = local_1;
                    position_2 = local_2;
                    position_3 = local_3;

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);

                    position_ptr += 32;
                }
            }
            return i;
        }

    // Lock-free, zero-alloc GPU kernel with deferred, on-the-fly hazard-driven pass batching
    [SkipLocalsInit]
    private void _MoveExample_GPU(
        in GpuBuffers      buffers,
        in InOutBuffer<float> position,
        in float           deltaTime)
    {
        var device   = (WgpuDevice)buffers.device;
        var recorder = device.Recorder;
        recorder.Init(_MoveExample_GPU_KernelId);

        recorder.RequireReadWrite(position);

        using (var pass = recorder.BeginComputePass("ShadowMethod"u8))
        {
            ref var effect = ref device.GetEffect(_MoveExample_GPU_KernelId, _MoveExample_GPU_WgslHash);
            if (!effect.IsCreated) {
                effect = ref _MoveExample_GPU_CreateEffect(device);
            }
            pass.SetPipeline(effect.pipeline);
            
            // Creation of buffer bind group is expensive. Try get from cache with two entries.
            var bufferGroup = effect.bufferCache.GetGroup(buffers.hash);
            if (!bufferGroup.IsCreated) {
                Span<BindGroupEntry> entries = stackalloc BindGroupEntry[1];
                entries[0] = WgpuBindGroup.From(0, position.Buffer);
                bufferGroup = recorder.CreateBindGroup(effect.bufferLayout, entries, "MoveExample_buffers"u8);
                device.UpdateBufferCache(_MoveExample_GPU_KernelId, bufferGroup, buffers.hash);
            }
            pass.SetBindGroup0(bufferGroup, buffers.hash);
            
            var uniforms = new _MoveExample_GPU_Uniforms {
                count           = buffers.length,
                position_off    = position.Offset,
                deltaTime       = deltaTime,
            };
            var entry = recorder.AsUniformEntry(0, uniforms);
            // Creation of uniform bind group is cheap => no caching.
            var uniformGroup = recorder.CreateBindGroup(effect.uniformLayout, entry, "MoveExample_uniforms"u8);
            pass.SetBindGroup1(uniformGroup);
            
            pass.DispatchWorkgroups((buffers.length + 63) / 64, 1, 1);
        }
    }
    
    [StructLayout(LayoutKind.Explicit, Size = 16)]  // WGSL layout: std140/std430
    private struct _MoveExample_GPU_Uniforms
    {
        [FieldOffset( 0)]    public int        count;
        [FieldOffset( 4)]    public int        position_off;
        [FieldOffset( 8)]    public float      deltaTime;
    }
    
    private static readonly int _MoveExample_GPU_KernelId           =  KernelRegistry.NewKernelId("MoveExampleKernel");
    private const  ulong        _MoveExample_GPU_BufferLayoutKey    =  0x8328507b4eb6ad4;
    private const  ulong        _MoveExample_GPU_UniformLayoutKey   =  0xeab614e96837d407;
    private static ulong        _MoveExample_GPU_WgslHash           => 0xfa4d8aff78d1af3f;

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref WgpuEffect _MoveExample_GPU_CreateEffect(WgpuDevice device)
    {
        // @group(0)
        var bufferLayout = device.GetBindGroupLayout(_MoveExample_GPU_BufferLayoutKey);
        if (!bufferLayout.IsCreated) {
            Span<WgpuLayoutEntry> buffers = stackalloc WgpuLayoutEntry[1];
            buffers[0] = WgpuLayoutEntry.ReadWriteStorage(0); // var<storage, read_write>  position_arr: array<f32>;
            bufferLayout = device.CreateBindGroupLayout(buffers, _MoveExample_GPU_BufferLayoutKey, "MoveExample_buffers"u8);
        }
        // @group(1)
        var uniformLayout = device.GetBindGroupLayout(_MoveExample_GPU_UniformLayoutKey);
        if (!uniformLayout.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0]    = WgpuLayoutEntry.Uniform(0); // var<uniform>              uniforms
            uniformLayout = device.CreateBindGroupLayout(uniform, _MoveExample_GPU_UniformLayoutKey, "MoveExample_uniforms"u8);
        }
        var shaderModule    = device.CreateShaderModule(_MoveExample_GPU_Shader(), "MoveExample"u8);
        var pipeline        = device.CreateComputePipeline(shaderModule, bufferLayout, uniformLayout, "MoveExample"u8);
        
        return ref device.CreateEffect(_MoveExample_GPU_KernelId, _MoveExample_GPU_WgslHash, pipeline, bufferLayout, uniformLayout);
    }

    private static ReadOnlySpan<byte> _MoveExample_GPU_Shader() =>
    """
    struct MoveExample_Uniforms {
        count           : u32,           // offset:  0 size:  4
        position_off    : u32,           // offset:  4 size:  4
        deltaTime       : f32,           // offset:  8 size:  4
    };                                   //            size: 16
    
    @group(0) @binding(0) var<storage, read_write>  position_arr: array<f32>;

    @group(1) @binding(0) var<uniform>              uniforms: MoveExample_Uniforms;

    @compute @workgroup_size(64)
    fn MoveExample(@builtin(global_invocation_id) global_id: vec3<u32>)
    {
        let index = global_id.x;
        if (index >= uniforms.count) {
            return;
        }
        var _position = position_arr[uniforms.position_off + index];
        var _deltaTime = uniforms.deltaTime;

        var _local = _deltaTime;
        _position = _local;

        position_arr[uniforms.position_off + index] = _position;
    }
    """u8;

    #endregion
    }
}
