//HintName: VerifyVectorize/Kernel_Sign_Example/Kernel_Sign.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using System.Collections.Generic;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

namespace VerifyVectorize
{
    public partial class Kernel_Sign_Example
    {
        /// <summary>Kernel method generated by: <see cref="Kernel_Sign"/>.</summary>
        public void Kernel_SignKernel(
            InOutBuffer<float> position,
            float value,
            ComputeMode mode = ComputeMode.Device)
        {
            var buffers =
            GpuBuffers.Create(position, nameof(position), mode);

            if (buffers.ComputeGPU) {
                _Kernel_Sign_GPU(buffers, position, value);
                return;
            }
            Kernel_SignVector(position.Span, value, buffers.ComputeSIMD);
        }

        /// <summary>Vector method generated for: <see cref="Kernel_Sign"/>.</summary>
        public void Kernel_SignVector(Span<float> position, float value, bool vectorized = true)
        {
            int count = position.Length;
            int n = 0;
            if (vectorized) {
                if (Avx.IsSupported) {
                    n = _Kernel_Sign_Avx(count, position, value);
                }
            }
            for (; n < count; n++) {
                Kernel_Sign(ref position[n], value);
            }
        }

    #region private members

        // [Layout: AoS-Vertical]  - lane-native speed
        [SkipLocalsInit]
        private static unsafe int _Kernel_Sign_Avx(int count,
            Span<float> position,
            float value)
        {
            int i = 0;
            count -= 32;
            if (i > count) {
                return 0;
            }
            if (position.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(position));

            // --- Locals
            var value_scalar = Vector256.Create(value);

            fixed (float* position_first = position)
            {
                float* position_ptr = (float*)position_first;

                for (; i <= count; i += 32)
                {
                    // --- 1. Load
                    Vector256<float> position_0;  // Single
                    Vector256<float> position_1;  // Single
                    Vector256<float> position_2;  // Single
                    Vector256<float> position_3;  // Single

                    // --- 2. Compute
                    // var sign = MathF.Sign(value);
                    var sign_0 = MathUtils.SignMathF(value_scalar);
                    var sign_1 = MathUtils.SignMathF(value_scalar);
                    var sign_2 = MathUtils.SignMathF(value_scalar);
                    var sign_3 = MathUtils.SignMathF(value_scalar);

                    // position = sign;
                    position_0 = sign_0;
                    position_1 = sign_1;
                    position_2 = sign_2;
                    position_3 = sign_3;

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);

                    position_ptr += 32;
                }
            }
            return i;
        }

    // Lock-free, zero-alloc GPU kernel with deferred, on-the-fly hazard-driven pass batching
    private void _Kernel_Sign_GPU(
        in GpuBuffers      buffers,
        in InOutBuffer<float> position,
        in float           value)
    {
        var device   = (WgpuDevice)buffers.device;
        var recorder = device.Recorder;
        recorder.Init(_Kernel_Sign_GPU_KernelId, "Kernel_Sign"u8);

        recorder.RequireReadWrite(position);

        using var pass = recorder.BeginComputePass("Kernel_Sign"u8);
        
        ref var pipelineCache = ref device.GetPipelineCache(_Kernel_Sign_GPU_KernelId, _Kernel_Sign_GPU_WgslHash);
        if (!pipelineCache.IsCreated) {
            pipelineCache = ref _Kernel_Sign_GPU_CreateComputeCache(device);
        }
        pass.SetPipeline(pipelineCache.computePipeline);

        var bindGroupCache = (_Kernel_Sign_GPU_Cache)pipelineCache.bindGroupCache;
        
        var key = position.Handle;
        if (!bindGroupCache.bufferGroup.TryGetValue(key, out var bufferGroup)) {
            Span<BindGroupEntry> entries = stackalloc BindGroupEntry[1];
            entries[0] = WgpuBindGroup.From(0, position.Buffer);
            bufferGroup = recorder.CreateBindGroup(pipelineCache.bufferLayout, entries, "Kernel_Sign_buffers"u8);
            bindGroupCache.bufferGroup.Add(key, bufferGroup);
        }
        pass.SetBindGroup(0, bufferGroup);
        
        var uniforms = new _Kernel_Sign_GPU_Uniforms {
            count           = buffers.length,
            position_off    = position.Offset,
            value           = value,
        };
        pass.SetUniformBindGroup(1, pipelineCache, ref bindGroupCache.uniformGroup, uniforms, "Kernel_Sign_uniforms"u8);
        
        pass.DispatchWorkgroups((buffers.length + 63) / 64, 1, 1);
    }

    private sealed class _Kernel_Sign_GPU_Cache : BindGroupCache
    {
        internal readonly   Dictionary<nint, WgpuBindGroup> bufferGroup = new ();
        internal            WgpuBindGroup uniformGroup;
        
        protected override void Clear() {
            ReleaseBindGroups(bufferGroup);
            ReleaseBindGroup(ref uniformGroup);
        }
    }
    
    [StructLayout(LayoutKind.Explicit, Size = 16)]  // WGSL layout: std140/std430
    private struct _Kernel_Sign_GPU_Uniforms
    {
        [FieldOffset( 0)]    public int        count;
        [FieldOffset( 4)]    public int        position_off;
        [FieldOffset( 8)]    public float      value;
    }
    
    private static readonly int _Kernel_Sign_GPU_KernelId           =  KernelRegistry.NewKernelId("Kernel_SignKernel");
    private const  ulong        _Kernel_Sign_GPU_BufferLayoutKey    =  0x8328507b4eb6ad4;
    private const  ulong        _Kernel_Sign_GPU_UniformLayoutKey   =  0xeab614e96837d407;
    private static ulong        _Kernel_Sign_GPU_WgslHash           => 0xa85ee513a18c92aa;

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref ComputeCache _Kernel_Sign_GPU_CreateComputeCache(WgpuDevice device)
    {
        // @group(0)
        var bufferLayout = device.GetBindGroupLayout(_Kernel_Sign_GPU_BufferLayoutKey);
        if (!bufferLayout.IsCreated) {
            Span<WgpuLayoutEntry> buffers = stackalloc WgpuLayoutEntry[1];
            buffers[0] = WgpuLayoutEntry.ReadWriteStorage(0); // var<storage, read_write>  position_arr: array<f32>;
            bufferLayout = device.CreateBindGroupLayout(buffers, ShaderStage.Compute, false, _Kernel_Sign_GPU_BufferLayoutKey, "Kernel_Sign_buffers"u8);
        }
        // @group(1)
        var uniformLayout = device.GetBindGroupLayout(_Kernel_Sign_GPU_UniformLayoutKey);
        if (!uniformLayout.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0]    = WgpuLayoutEntry.Uniform(0); // var<uniform>              uniforms
            uniformLayout = device.CreateBindGroupLayout(uniform, ShaderStage.Compute, true, _Kernel_Sign_GPU_UniformLayoutKey, "Kernel_Sign_uniforms"u8);
        }
        var shaderModule    = device.CreateShaderModule(_Kernel_Sign_GPU_Shader(), "Kernel_Sign"u8);
        var pipeline        = device.CreateComputePipeline(shaderModule, bufferLayout, uniformLayout, "Kernel_Sign"u8);
        
        var bindGroupCache = new _Kernel_Sign_GPU_Cache();
        return ref device.CreatePipelineCache(_Kernel_Sign_GPU_KernelId, _Kernel_Sign_GPU_WgslHash, pipeline, bufferLayout, uniformLayout, bindGroupCache);
    }

    private static ReadOnlySpan<byte> _Kernel_Sign_GPU_Shader() =>
    """
    struct Kernel_Sign_Uniforms {
        count           : u32,           // offset:  0 size:  4
        position_off    : u32,           // offset:  4 size:  4
        value           : f32,           // offset:  8 size:  4
    };                                   //            size: 16
    
    @group(0) @binding(0) var<storage, read_write>  position_arr: array<f32>;

    @group(1) @binding(0) var<uniform>              uniforms: Kernel_Sign_Uniforms;

    @compute @workgroup_size(64)
    fn Kernel_Sign(@builtin(global_invocation_id) global_id: vec3<u32>)
    {
        let index = global_id.x;
        if (index >= uniforms.count) {
            return;
        }
        var _position = position_arr[uniforms.position_off + index];
        var _value = uniforms.value;

        var _sign = sign(_value);
        _position = _sign;

        position_arr[uniforms.position_off + index] = _position;
    }
    """u8;

    #endregion
    }
}
