//HintName: VerifyVectorize/MyExample/MoveExample.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;


namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Kernel method generated by: <see cref="MoveExample"/>.</summary>
        public GpuBuffer<Vector2> MoveExampleKernel(
            Buffer<Vector2> position,
          InBuffer<Vector2> velocity,
            float deltaTime,
            ComputeMode mode = ComputeMode.Device)
        {
            var buffers =
            GpuBuffers.Create(position, nameof(position), mode);
            buffers.Validate (velocity, nameof(velocity));

            if (buffers.ComputeGPU) {
                return _MoveExample_GPU(buffers, position, velocity, deltaTime);
            }
            MoveExampleVector(position.Span, velocity.Span, deltaTime, buffers.ComputeSIMD);
            return null;
        }

        /// <summary>Vector method generated for: <see cref="MoveExample"/>.</summary>
        public void MoveExampleVector(Span<Vector2> position, ReadOnlySpan<Vector2> velocity, float deltaTime, bool vectorized = true)
        {
            int count = position.Length;
            int n = 0;
            if (vectorized) {
                if (Avx.IsSupported) {
                    n = _MoveExample_Avx(count, position, velocity, deltaTime);
                }
            }
            for (; n < count; n++) {
                MoveExample(ref position[n], velocity[n], deltaTime);
            }
        }

    #region private members

        // [Layout: AoS-Vertical]  - lane-native speed
        [SkipLocalsInit]
        private static unsafe int _MoveExample_Avx(int count,
            Span<Vector2> position,
            ReadOnlySpan<Vector2> velocity,
            float deltaTime)
        {
            int i = 0;
            count -= 16;
            if (i > count) {
                return 0;
            }
            if (position.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(position));
            if (velocity.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(velocity));

            // --- Locals
            var deltaTime_scalar = Vector256.Create(deltaTime);

            fixed (Vector2* position_first = position)
            fixed (Vector2* velocity_first = velocity)
            {
                float* position_ptr = (float*)position_first;
                float* velocity_ptr = (float*)velocity_first;

                for (; i <= count; i += 16)
                {
                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Vector2
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Vector2
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Vector2
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);   // Vector2

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr +  0);   // Vector2
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8);   // Vector2
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16);   // Vector2
                    Vector256<float> velocity_3 = Avx.LoadVector256(velocity_ptr + 24);   // Vector2

                    // --- 2. Compute
                    // position += velocity * deltaTime;
                    position_0 = Fma.MultiplyAdd(velocity_0, deltaTime_scalar, position_0);
                    position_1 = Fma.MultiplyAdd(velocity_1, deltaTime_scalar, position_1);
                    position_2 = Fma.MultiplyAdd(velocity_2, deltaTime_scalar, position_2);
                    position_3 = Fma.MultiplyAdd(velocity_3, deltaTime_scalar, position_3);

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);

                    position_ptr += 32;
                    velocity_ptr += 32;
                }
            }
            return i;
        }

    [SkipLocalsInit]
    private GpuBuffer<Vector2> _MoveExample_GPU(
        in GpuBuffers      buffers,
        in Buffer  <Vector2> position_,
        in InBuffer<Vector2> velocity_,
        in float           deltaTime)
    {
        var device      = (WgpuDevice)buffers.device;
        var position    = position_.GpuBuffer;
        var velocity    = velocity_.GpuBuffer;
        
        // output ??= device.RentBuffer<Vector2>(buffers.length);  TODO
        using var task  = device.RentTask();

        // Dependencies from inputs (out not Output!)
        if (velocity.LastWritingTask != null) task.AddDependency(velocity);

        // Recording - task provides Encoder
        var encoder = task.GetEncoder("MoveExample"u8);
        using (var pass = encoder.BeginComputePass("MoveExample"u8))
        {
            var effect = device.GetEffect(_MoveExample_GPU_EffectSlot); // simple GpuEffect[] array lookup
            if (!effect.IsCreated) {
                effect = _MoveExample_GPU_CreateEffect(device);
            }
            pass.SetPipeline(effect.pipeline);
            
            // Creation of buffer bind group is expensive. Try get from cache with two entries.
            var bufferGroup = effect.bufferCache.GetGroup(buffers.hash);
            if (!bufferGroup.IsCreated) {
                Span<BindGroupEntry> entries = stackalloc BindGroupEntry[2];
                entries[0] = WgpuBindGroup.From(0, position);
                entries[1] = WgpuBindGroup.From(1, velocity);
                bufferGroup = task.CreateBindGroup(effect.bufferLayout, entries, "MoveExample_buffers"u8);
                device.UpdateBufferCache(_MoveExample_GPU_EffectSlot, bufferGroup, buffers.hash);
            }
            pass.SetBindGroup(0, bufferGroup);
            
            var uniforms = new _MoveExample_GPU_Uniforms {
                count           = buffers.length,
                position_off    = position_.Offset,
                velocity_off    = velocity_.Offset,
                deltaTime       = deltaTime,
            };
            var entry = task.AsUniformEntry(0, uniforms);
            // Creation of uniform bind group is cheap => no caching.
            var uniformGroup = task.CreateBindGroup(effect.uniformLayout, entry, "MoveExample_uniforms"u8);
            pass.SetBindGroup(1, uniformGroup);
            
            pass.DispatchWorkgroups((buffers.length + 63) / 64, 1, 1);
            pass.End();
        }
        // connect task to output
        ((WgpuBuffer<Vector2>)position).SetLastWritingTask(task);

        task.Finish(encoder, "MoveExample"u8);
        device.Enqueue(task); // queues CommandBuffer only. No Submit().

        // output.WaitInDebug();
        return null;
    }
    
    [StructLayout(LayoutKind.Explicit, Size = 16)]  // WGSL layout: std140/std430
    private struct _MoveExample_GPU_Uniforms
    {
        [FieldOffset( 0)]    public int        count;
        [FieldOffset( 4)]    public int        position_off;
        [FieldOffset( 8)]    public int        velocity_off;
        [FieldOffset(12)]    public float      deltaTime;
    }
    
    private static readonly int _MoveExample_GPU_EffectSlot         = WgpuDevice.NewEffectSlot();
    private const ulong         _MoveExample_GPU_BufferLayoutKey    = 0x332c677f8f18f451;
    private const ulong         _MoveExample_GPU_UniformLayoutKey   = 0xeab614e96837d407;

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static WgpuEffect _MoveExample_GPU_CreateEffect(WgpuDevice device)
    {
        // @group(0)
        var bufferLayout = device.GetBindGroupLayout(_MoveExample_GPU_BufferLayoutKey);
        if (!bufferLayout.IsCreated) {
            Span<WgpuLayoutEntry> buffers = stackalloc WgpuLayoutEntry[2];
            buffers[0] = WgpuLayoutEntry.ReadWriteStorage(0); // var<storage, read_write>  position_arr: array<vec2<f32>>;
            buffers[1] = WgpuLayoutEntry.ReadOnlyStorage (1); // var<storage, read      >  velocity_arr: array<vec2<f32>>;
            bufferLayout = device.CreateBindGroupLayout(buffers, _MoveExample_GPU_BufferLayoutKey, "MoveExample_buffers"u8);
        }
        // @group(1)
        var uniformLayout = device.GetBindGroupLayout(_MoveExample_GPU_UniformLayoutKey);
        if (!uniformLayout.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0]    = WgpuLayoutEntry.Uniform(0); // var<uniform>              uniforms
            uniformLayout = device.CreateBindGroupLayout(uniform, _MoveExample_GPU_UniformLayoutKey, "MoveExample_uniforms"u8);
        }
        var shaderModule    = device.CreateShaderModule(_MoveExample_GPU_Shader(), "MoveExample"u8);
        var pipeline        = device.CreateComputePipeline(shaderModule, bufferLayout, uniformLayout, "MoveExample"u8);
        
        return device.CreateEffect(_MoveExample_GPU_EffectSlot, pipeline, bufferLayout, uniformLayout);
    }

    private static ReadOnlySpan<byte> _MoveExample_GPU_Shader() =>
    """
    struct MoveExample_Uniforms {
        count           : u32,           // offset:  0 size:  4
        position_off    : u32,           // offset:  4 size:  4
        velocity_off    : u32,           // offset:  8 size:  4
        deltaTime       : f32,           // offset: 12 size:  4
    };                                   //            size: 16
    
    @group(0) @binding(0) var<storage, read_write>  position_arr: array<vec2<f32>>;
    @group(0) @binding(1) var<storage, read      >  velocity_arr: array<vec2<f32>>;

    @group(1) @binding(0) var<uniform>              uniforms: MoveExample_Uniforms;

    @compute @workgroup_size(64)
    fn MoveExample(@builtin(global_invocation_id) global_id: vec3<u32>)
    {
        let index = global_id.x;
        if (index >= uniforms.count) {
            return;
        }
        var _position = position_arr[uniforms.position_off + index];
        var _velocity = velocity_arr[uniforms.velocity_off + index];
        var _deltaTime = uniforms.deltaTime;

        _position += (_velocity * _deltaTime);

        position_arr[uniforms.position_off + index] = _position;
    }
    """u8;

    #endregion
    }
}
