//HintName: VerifyVectorize/Kernel_Sign_Example/Kernel_Sign.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;


namespace VerifyVectorize
{
    public partial class Kernel_Sign_Example
    {
        /// <summary>Kernel method generated by: <see cref="Kernel_Sign"/>.</summary>
        public GpuBuffer<float> Kernel_SignKernel(
            Buffer<float> position,
            float value,
            ComputeMode mode = ComputeMode.Device)
        {
            var buffers =
            GpuBuffers.Create(position, nameof(position), mode);

            if (buffers.ComputeGPU) {
                return _Kernel_Sign_GPU(buffers, position.gpuBuffer, value);
            }
            Kernel_SignVector(position.span, value, buffers.ComputeSIMD);
            return null;
        }

        /// <summary>Vector method generated for: <see cref="Kernel_Sign"/>.</summary>
        public void Kernel_SignVector(Span<float> position, float value, bool vectorized = true)
        {
            int count = position.Length;
            int n = 0;
            if (vectorized) {
                if (Avx.IsSupported) {
                    n = _Kernel_Sign_Avx(count, position, value);
                }
            }
            for (; n < count; n++) {
                Kernel_Sign(ref position[n], value);
            }
        }

    #region private members

        // [Layout: AoS-Vertical]  - lane-native speed
        [SkipLocalsInit]
        private static unsafe int _Kernel_Sign_Avx(int count,
            Span<float> position,
            float value)
        {
            int i = 0;
            count -= 32;
            if (i > count) {
                return 0;
            }
            if (position.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(position));

            // --- Locals
            var value_scalar = Vector256.Create(value);

            fixed (float* position_first = position)
            {
                float* position_ptr = (float*)position_first;

                for (; i <= count; i += 32)
                {
                    // --- 1. Load
                    Vector256<float> position_0;  // Single
                    Vector256<float> position_1;  // Single
                    Vector256<float> position_2;  // Single
                    Vector256<float> position_3;  // Single

                    // --- 2. Compute
                    // var sign = MathF.Sign(value);
                    var sign_0 = MathUtils.SignMathF(value_scalar);
                    var sign_1 = MathUtils.SignMathF(value_scalar);
                    var sign_2 = MathUtils.SignMathF(value_scalar);
                    var sign_3 = MathUtils.SignMathF(value_scalar);

                    // position = sign;
                    position_0 = sign_0;
                    position_1 = sign_1;
                    position_2 = sign_2;
                    position_3 = sign_3;

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);

                    position_ptr += 32;
                }
            }
            return i;
        }

    [SkipLocalsInit]
    private GpuBuffer<float> _Kernel_Sign_GPU(
        in GpuBuffers buffers,
        GpuBuffer<float> position,
        float value)
    {
        var device      = (WgpuDevice)buffers.device;
        // output ??= device.RentBuffer<float>(buffers.length);  TODO
        using var task  = device.RentTask();

        // Dependencies from inputs (out not Output!)

        // Recording - task provides Encoder
        var encoder = task.GetEncoder("Kernel_Sign"u8);
        using (var pass = encoder.BeginComputePass("Kernel_Sign"u8))
        {
            var effect = device.GetEffect(_Kernel_Sign_GPU_EffectSlot); // simple GpuEffect[] array lookup
            if (!effect.IsCreated) {
                effect = _Kernel_Sign_GPU_CreateEffect(device);
            }
            pass.SetPipeline(effect.pipeline);
            
            // Creation of buffer bind group is expensive. Try get from cache with two entries.
            var bufferGroup = effect.bufferCache.GetGroup(buffers.hash);
            if (!bufferGroup.IsCreated) {
                Span<BindGroupEntry> entries = stackalloc BindGroupEntry[1];
                entries[0] = WgpuBindGroup.From(0, position);
                bufferGroup = task.CreateBindGroup(effect.bufferLayout, entries, "Kernel_Sign_buffers"u8);
                device.UpdateBufferCache(_Kernel_Sign_GPU_EffectSlot, bufferGroup, buffers.hash);
            }
            pass.SetBindGroup(0, bufferGroup);
            
            var uniforms = new _Kernel_Sign_GPU_Uniforms {
                count = buffers.length,
                value = value,
            };
            var entry = task.AsUniformEntry(0, uniforms);
            // Creation of uniform bind group is cheap => no caching.
            var uniformGroup = task.CreateBindGroup(effect.uniformLayout, entry, "Kernel_Sign_uniforms"u8);
            pass.SetBindGroup(1, uniformGroup);
            
            pass.DispatchWorkgroups((buffers.length + 63) / 64, 1, 1);
            pass.End();
        }
        // connect task to output
        ((WgpuBuffer<float>)position).SetLastWritingTask(task);

        task.Finish(encoder, "Kernel_Sign"u8);
        device.Enqueue(task); // queues CommandBuffer only. No Submit().

        // output.WaitInDebug();
        return null;
    }
    
    [StructLayout(LayoutKind.Explicit, Size = 16)]  // WGSL layout: std140/std430
    private struct _Kernel_Sign_GPU_Uniforms
    {
        [FieldOffset(0)]    public int        count;
        [FieldOffset(4)]    public float      value;
    }
    
    private static readonly int _Kernel_Sign_GPU_EffectSlot         = WgpuDevice.NewEffectSlot();
    private const ulong         _Kernel_Sign_GPU_BufferLayoutKey    = 0x8328507b4eb6ad4;
    private const ulong         _Kernel_Sign_GPU_UniformLayoutKey   = 0xeab614e96837d407;

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static WgpuEffect _Kernel_Sign_GPU_CreateEffect(WgpuDevice device)
    {
        // @group(0)
        var bufferLayout = device.GetBindGroupLayout(_Kernel_Sign_GPU_BufferLayoutKey);
        if (!bufferLayout.IsCreated) {
            Span<WgpuLayoutEntry> buffers = stackalloc WgpuLayoutEntry[1];
            buffers[0] = WgpuLayoutEntry.ReadWriteStorage<float> (0); // var<storage, read_write>  position_arr: array<f32>;
            bufferLayout = device.CreateBindGroupLayout(buffers, _Kernel_Sign_GPU_BufferLayoutKey, "Kernel_Sign_buffers"u8);
        }
        // @group(1)
        var uniformLayout = device.GetBindGroupLayout(_Kernel_Sign_GPU_UniformLayoutKey);
        if (!uniformLayout.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0]    = WgpuLayoutEntry.Uniform<_Kernel_Sign_GPU_Uniforms> (0); // var<uniform>              uniforms
            uniformLayout = device.CreateBindGroupLayout(uniform, _Kernel_Sign_GPU_UniformLayoutKey, "Kernel_Sign_uniforms"u8);
        }
        var shaderModule    = device.CreateShaderModule(_Kernel_Sign_GPU_Shader(), "Kernel_Sign"u8);
        var pipeline        = device.CreateComputePipeline(shaderModule, bufferLayout, uniformLayout, "Kernel_Sign"u8);
        
        return device.CreateEffect(_Kernel_Sign_GPU_EffectSlot, pipeline, bufferLayout, uniformLayout);
    }

    private static ReadOnlySpan<byte> _Kernel_Sign_GPU_Shader() =>
    """
    struct Kernel_Sign_Uniforms {
        count      : u32,           // offset:  0 size:  4
        value      : f32,           // offset:  4 size:  4
    };                              //            size: 16
    
    @group(0) @binding(0) var<storage, read_write>  position_arr: array<f32>;

    @group(1) @binding(0) var<uniform>              uniforms: Kernel_Sign_Uniforms;

    @compute @workgroup_size(64)
    fn Kernel_Sign(@builtin(global_invocation_id) global_id: vec3<u32>)
    {
        let index = global_id.x;
        if (index >= uniforms.count) {
            return;
        }
        var _position = position_arr[index];
        var _value = uniforms.value;

        var _sign = sign(_value);
        _position = _sign;

        position_arr[index] = _position;
    }
    """u8;

    #endregion
    }
}
