//HintName: VerifyVectorize/MyExample/MoveExample.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;


namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Kernel method generated by: <see cref="MoveExample"/>.</summary>
        public GpuBuffer<float> MoveExampleKernel(
            Buffer<float> position,
            Buffer<float> velocity,
            float deltaTime)
        {
            GpuBuffers buffers = new(position, nameof(position));
            buffers.Validate        (velocity, nameof(velocity));

            if (!buffers.areSpans) {
                return _MoveExample_GPU(buffers, position.gpuBuffer, velocity.gpuBuffer, deltaTime);
            }
            MoveExampleVector(position.span, velocity.span, deltaTime);
            return null;
        }

        /// <summary>Vector method generated for: <see cref="MoveExample"/>.</summary>
        public void MoveExampleVector(Span<float> position, ReadOnlySpan<float> velocity, float deltaTime, bool vectorized = true)
        {
            int count = position.Length;
            int n = 0;
            if (vectorized) {
                if (Avx.IsSupported) {
                    n = _MoveExample_Avx(count, position, velocity, deltaTime);
                }
            }
            for (; n < count; n++) {
                MoveExample(ref position[n], velocity[n], deltaTime);
            }
        }

    #region private members

        // [Layout: AoS-Vertical]  - lane-native speed
        [SkipLocalsInit]
        private static unsafe int _MoveExample_Avx(int count,
            Span<float> position,
            ReadOnlySpan<float> velocity,
            float deltaTime)
        {
            int i = 0;
            count -= 32;
            if (i > count) {
                return 0;
            }
            if (position.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(position));
            if (velocity.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(velocity));

            // --- Locals
            var deltaTime_scalar = Vector256.Create(deltaTime);

            fixed (float* position_first = position)
            fixed (float* velocity_first = velocity)
            {
                float* position_ptr = (float*)position_first;
                float* velocity_ptr = (float*)velocity_first;

                for (; i <= count; i += 32)
                {
                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);  // Single
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);  // Single
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);  // Single
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);  // Single

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr +  0);  // Single
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8);  // Single
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16);  // Single
                    Vector256<float> velocity_3 = Avx.LoadVector256(velocity_ptr + 24);  // Single

                    // --- 2. Compute
                    // position += velocity * deltaTime;
                    position_0 = Fma.MultiplyAdd(velocity_0, deltaTime_scalar, position_0);
                    position_1 = Fma.MultiplyAdd(velocity_1, deltaTime_scalar, position_1);
                    position_2 = Fma.MultiplyAdd(velocity_2, deltaTime_scalar, position_2);
                    position_3 = Fma.MultiplyAdd(velocity_3, deltaTime_scalar, position_3);

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);

                    position_ptr += 32;
                    velocity_ptr += 32;
                }
            }
            return i;
        }

    [SkipLocalsInit]
    private GpuBuffer<float> _MoveExample_GPU(
        in GpuBuffers buffers,
            Buffer<float> position,
            Buffer<float> velocity,
            float deltaTime)
    {
        var device      = (WgpuDevice)buffers.GetDevice();
        // output ??= device.RentBuffer<float>(buffers.count);  TODO
        using var task  = device.RentTask();

        // Dependencies from inputs (out not Output!)
        if (velocity.LastWritingTask != null) task.AddDependency(velocity);

        // Recording (task provides Encoder)
        var encoder = task.GetEncoder("MoveExample"u8);
        using (var pass = encoder.BeginComputePass("MoveExample"u8))
        {
            var effect = device.GetEffect(_MoveExample_GPU_EffectSlot); // Each device has its own GpuEffect[] array
            if (!effect.IsCreated) {
                effect = _MoveExample_GPU_CreateEffect(device);
            }
            pass.SetPipeline(effect.pipeline);
            
            // Creation of a buffer bind group is expensive in wgpu. So we cache them. Cache has two entries.
            var bufferGroup = effect.bufferCache.GetGroup(buffers.hash);
            if (!bufferGroup.IsCreated) {
                Span<BindGroupEntry> entries = stackalloc BindGroupEntry[2];
                entries[0] = WgpuBindGroup.From(0, position);
                entries[1] = WgpuBindGroup.From(1, velocity);
                bufferGroup = task.CreateBindGroup(effect.bufferLayout, entries, "MoveExample_buffers"u8);
                device.UpdateBufferCache(_MoveExample_GPU_EffectSlot, bufferGroup, buffers.hash);
            }
            pass.SetBindGroup(0, bufferGroup);
            
            var uniforms = new _MoveExample_GPU_Uniforms {
                count = buffers.count,
                deltaTime = deltaTime,
            };
            var entry = task.AsUniformEntry(0, uniforms);
            // Creation of a uniform bind group is much cheaper than for a buffer in wgpu. So no caching.
            var uniformGroup = task.CreateBindGroup(effect.uniformLayout, entry, "MoveExample_uniforms"u8);
            pass.SetBindGroup(1, uniformGroup);
            
            pass.DispatchWorkgroups((buffers.count + 63) / 64, 1, 1);       // Execute ComputePass
            pass.End();                                                     // finish Pass (required by WebGPU State-Machine)
        }
        // connect task to output
        ((WgpuBuffer<float>)output).SetLastWritingTask(task);
        task.Finish(encoder, "MoveExample"u8); // extract CommandBuffer from Encoder
        device.Enqueue(task);                      // queues CommandBuffer only. No Submit().

        // output.WaitInDebug();
        return null;
    }
    
    private static readonly int _MoveExample_GPU_EffectSlot         = WgpuDevice.NewEffectSlot();
    private const ulong         _MoveExample_GPU_BufferLayoutKey    = 1234; // TODO calculated unique hash key
    private const ulong         _MoveExample_GPU_UniformLayoutKey   = 5678; // TODO calculated unique hash key

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static WgpuEffect _MoveExample_GPU_CreateEffect(WgpuDevice device)
    {
        var bufferLayout = device.GetBindGroupLayout(_MoveExample_GPU_BufferLayoutKey);
        if (!bufferLayout.IsCreated) {
            Span<WgpuLayoutEntry> buffers = stackalloc WgpuLayoutEntry[3];
            buffers[0] = WgpuLayoutEntry.ReadOnlyStorage<float> (0); // @group(0) @binding(0) var<storage, read>       weight
            buffers[1] = WgpuLayoutEntry.ReadOnlyStorage<float> (1); // @group(0) @binding(1) var<storage, read>       input
            buffers[2] = WgpuLayoutEntry.ReadWriteStorage<float>(2); // @group(0) @binding(2) var<storage, read_write> output
            bufferLayout = device.CreateBindGroupLayout(buffers, _MoveExample_GPU_BufferLayoutKey, "MoveExample_buffers"u8);
        }
        var uniformLayout = device.GetBindGroupLayout(_MoveExample_GPU_UniformLayoutKey);
        if (!uniformLayout.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0] = WgpuLayoutEntry.Uniform<float> (0);         // @group(1) @binding(0) var<uniform>             uniforms
            uniformLayout   = device.CreateBindGroupLayout(uniform, _MoveExample_GPU_UniformLayoutKey, "MoveExample_uniforms"u8);
        }
        var shaderModule    = device.CreateShaderModule(_MoveExample_GPU_Shader(), "MoveExample"u8);
        var pipeline        = device.CreateComputePipeline(shaderModule, bufferLayout, uniformLayout, "MoveExample"u8);
        
        return device.CreateEffect(_MoveExample_GPU_EffectSlot, pipeline, bufferLayout, uniformLayout);
    }

    // TODO in future the shader should be created at compile time. The binary will be "stored" as generated file (in memory)
    private static ReadOnlySpan<byte> _MoveExample_GPU_Shader() =>
    """
    struct MoveExample_Uniforms {
        bias    : f32,
        count   : u32
    };

    @group(0) @binding(0) var<storage, read>        weight_arr:     array<f32>;
    @group(0) @binding(1) var<storage, read>        input_arr:      array<f32>;
    @group(0) @binding(2) var<storage, read_write>  output_arr:     array<f32>;

    @group(1) @binding(0) var<uniform>              uniforms:   	MoveExample_Uniforms;

    @compute @workgroup_size(64)
    fn MoveExample(@builtin(global_invocation_id) global_id: vec3<u32>) {
        let index = global_id.x;
        if (index >= uniforms.count) {
            return;
        }
        let weight = weight_arr[index];
        let input  = input_arr[index];
        // shader body generated from Blueprint method body
        output_arr[index] = (input * weight) + uniforms.bias;
    }
    """u8;
        
    // struct for uniforms
    [StructLayout(LayoutKind.Explicit, Size = 16)]  // WGSL uses std140/std430 Layout
    private struct _MoveExample_GPU_Uniforms
    {
        [FieldOffset(0)]    public int      count;
        [FieldOffset(4)]    public float    deltaTime;
    }

    #endregion
    }
}
