// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.ShadowMapping;


[Source("~/shaders/shadowMapping/fragment.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct Scene (
    Matrix4x4 lightViewProjMatrix,
    Matrix4x4 cameraViewProjMatrix,
    Vector3   lightPos)
{
    public  Matrix4x4 lightViewProjMatrix  = lightViewProjMatrix;
    public  Matrix4x4 cameraViewProjMatrix = cameraViewProjMatrix;
    public  Vector3   lightPos             = lightPos;
}


