// <auto-generated />  path: shaders/shadowMapping/vertexShadow.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.WGPU;
using System.Numerics;

namespace Shaders.ShadowMapping;


/// Skipped identical duplicate of  <see cref="Scene"/>
file partial class _info;


/// Skipped identical duplicate of  <see cref="Model"/>
file partial class _info;


