// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.ShadowMapping;


/// Skipped identical duplicate of  <see cref="Scene"/>
file partial class _info;


[Source("~/shaders/shadowMapping/vertex.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 64)]
public struct Model (
    Matrix4x4 modelMatrix)
{
    [FieldOffset(  0)]  public  Matrix4x4 modelMatrix = modelMatrix;
}


