// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.ShadowMapping;


/// Skipped identical duplicate of  <see cref="Scene"/>
file partial class _info;


/// Skipped identical duplicate of  <see cref="Model"/>
file partial class _info;


