// Copyright (c) Ullrich Praetz - https://github.com/friflo. All rights reserved.
// See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;


// ReSharper disable ForeachCanBePartlyConvertedToQueryUsingAnotherGetEnumerator
// ReSharper disable UnusedMember.Local
// ReSharper disable InconsistentNaming
namespace Friflo.WGSL.Transpiler.WGSL;


internal struct StructCode {
    public string source;
    public bool   alreadyDeclared;
}


public struct CSharpField
{
    public required string      name;
    public required CSharpType  type;
    public          int         offset;

    public override string      ToString() => name;
}

public class CSharpStruct
{
    public required string          name;
    public required string          source;
    public required CSharpField[]   fields;
    public          int             size;
    
    public override string      ToString() => name;
}


public sealed class TypeEmitter
{
    private readonly    Dictionary<string, CSharpStruct>    structMap   = new();
    private readonly    List<StructCode>                    fileStructs = [];
    private             WgslModule                          module;
    private             string                              fileNamespace;
    
    private static void DebugInputs(WgslFile[] wgslFiles, string projDir)
    {
        var path = Path.Combine(projDir, "debug.txt");
        var sb = new StringBuilder();
        sb.Append($"projDir: {projDir}\n\n");
        
        foreach (var file in wgslFiles) {
            sb.Append($"{file.NormalizedPath}\n");
        }
        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
    }
    
    private static string PathToNamespace(string path, string root = "")
    {
        var dir = Path.GetDirectoryName(path);
        if (string.IsNullOrEmpty(dir)) return root;

        var parts = dir.Split(['/', '\\', '-', '_'], StringSplitOptions.RemoveEmptyEntries);
        for (int i = 0; i < parts.Length; i++)
        {
            var p = parts[i];
            var rest = p.Length > 1 ? p.Substring(1) : "";
            parts[i] = (char.IsDigit(p[0]) ? "_" : "") + char.ToUpperInvariant(p[0]) + rest;
        }
        return $"{root}{string.Join(".", parts)}";
    }
    
    public void EmitAllStructs(WgslFile[] wgslFiles, string projDir)
    {
        for (int n = 0; n < wgslFiles.Length; n++) {
            var path =  wgslFiles[n].NormalizedPath.Substring(projDir.Length + 1);
            wgslFiles[n] = wgslFiles[n] with{ NormalizedPath =  path };
        }
        // DebugInputs(wgslFiles, projDir);
        
        // sort for deterministic generation
        WgslFile.Sort(wgslFiles);
        
        var sb = new StringBuilder();
        
        foreach (var file in wgslFiles)
        {
            var normalizedPath = file.NormalizedPath;
            try {
                // --- clear state first!
                sb.Clear();
                fileStructs.Clear();
                fileNamespace = PathToNamespace(normalizedPath);
                
                // --- process after
                module = WgslParser.ParseWgsl(file.Content, normalizedPath);
                
                EmitModule();
                
                if (fileStructs.Count == 0) {
                    continue;
                }
                sb.Append("// <auto-generated />\n");
                sb.Append("using System;\n");
                sb.Append("using System.Numerics;\n");
                sb.Append("using System.Runtime.InteropServices;\n");
                sb.Append("using Friflo.Vectorization.WebGPU;\n");
                sb.Append("\n");
                // sb.Append("// ReSharper disable CheckNamespace\n");
                // sb.Append("// ReSharper disable InconsistentNaming\n");
                sb.Append($"namespace {fileNamespace};\n");
                sb.Append("\n\n");
                foreach (var structSource in fileStructs) {
                    if (!structSource.alreadyDeclared) {
                        sb.Append($"[Source(\"~/{normalizedPath}\")]\n");
                        sb.Append($"[StructLayout(LayoutKind.Sequential)]\n");
                    } 
                    sb.Append(structSource.source);
                }
            }
            catch (Exception exception) {
                sb.Append($"/* -------- Error parsing: {normalizedPath}\n");
                sb.Append(WgslUtils.GetExceptionAsString(exception));
                sb.Append("\n*/\n");
            }
            var source =  sb.ToString();
            var path = $"{projDir}/{file.NormalizedPath}.cs";

            File.WriteAllText(path, source, new UTF8Encoding(false));
        }
    }
        
    private void EmitModule()
    {
        var structs = module.Structs;
        var bindings = module.Bindings;
        if (bindings.Count == 0 || structs.Count == 0) {
            return;
        }
        foreach (var binding in bindings)
        {
            var typeName = binding.WgslType.Name;
            var wgslStruct = structs.FirstOrDefault(s => s.Name == typeName);
            if (wgslStruct == null) continue;
            if (typeName == "StructWithStructs") {
                int i = 1;
            }
            AddStruct(wgslStruct);
        }
    }
    
    private void AddStruct(WgslStruct wgslStruct)
    {
        var length = wgslStruct.Fields.Count;
        var fields = new CSharpField[length];
        var sb = new StringBuilder();
        sb.Clear();
        sb.Append($"public struct {wgslStruct.Name} (\n");
        
        var maxTypeWidth  = 0;
        var maxFieldWidth = 0;
        
        for (int n = 0; n < length; n++) {
            var field       = wgslStruct.Fields[n];
            var csharpType  = GetCSharpType(field.WgslType);
            fields[n] = new CSharpField { name = field.Name, type = csharpType };
            maxTypeWidth    = Math.Max(maxTypeWidth, csharpType.typeName.Length);
            maxFieldWidth   = Math.Max(maxFieldWidth, field.Name.Length);
        }
        foreach (var csharpField in fields) {
            var padParam   = maxTypeWidth  - csharpField.type.typeName.Length;
            sb.Append($"    {csharpField.type.typeName} ").Append(' ', padParam).Append($"{csharpField.name},\n");
        }
        if (length > 0) {
            sb.Length -= 2;
        }
        sb.Append(")\n");
        sb.Append("{\n");

        foreach (var field in fields) {
            var padName   = maxTypeWidth  - field.type.typeName.Length;
            var padAssign = maxFieldWidth - field.name.Length;
            sb.Append($"    public  {field.type.typeName} ").Append(' ', padName);
            sb.Append($"{field.name} ").Append(' ', padAssign).Append($"= {field.name};\n");
        }
        sb.Append("}\n\n\n");
        var source          = sb.ToString();
        var alreadyDeclared = false;
        var fullQualifiedName   = $"{fileNamespace}-{wgslStruct.Name}";
        
        if (structMap.TryGetValue(fullQualifiedName, out var curStruct)) {
            if (source == curStruct.source) {
                source = $"/// Skipped identical duplicate of  <see cref=\"{wgslStruct.Name}\"/>\nfile partial class _info;\n\n\n";
                alreadyDeclared = true;
            }
        } else {
            var csharpStruct = new CSharpStruct { name = wgslStruct.Name, source =  source, fields = fields };
            structMap.Add(fullQualifiedName, csharpStruct);
        }
        fileStructs.Add(new StructCode { source = source, alreadyDeclared = alreadyDeclared });
    }
    
    private CSharpType GetCSharpType(WgslType type)
    {
        var generics = type.Generics;
        var arg_0 = generics.Length > 0 ? generics[0].Name : "";
        
        var csharpType = CSharpType.GetCSharpType(type.Name, arg_0);
        
        var wgslStruct = module.Structs.FirstOrDefault(s => s.Name == csharpType.typeName);
        if (wgslStruct != null) {
            AddStruct(wgslStruct);
        }
        return csharpType;
    }
}