// Copyright (c) Ullrich Praetz - https://github.com/friflo. All rights reserved.
// See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;


// ReSharper disable ForeachCanBePartlyConvertedToQueryUsingAnotherGetEnumerator
// ReSharper disable UnusedMember.Local
// ReSharper disable InconsistentNaming
namespace Friflo.WGSL.Transpiler.WGSL;


internal struct StructCode {
    public string source;
    public bool   alreadyDeclared;
}

public sealed class TypeEmitter
{
    private readonly    Dictionary<string, string>  structMap   = new();
    private readonly    List<StructCode>            fileStructs = [];
    private             WgslModule                  module;
    private             string                      fileNamespace;
    
    private static void DebugInputs(WgslFile[] wgslFiles, string projDir)
    {
        var path = Path.Combine(projDir, "debug.txt");
        var sb = new StringBuilder();
        sb.Append($"projDir: {projDir}\n\n");
        
        foreach (var file in wgslFiles) {
            sb.Append($"{file.NormalizedPath}\n");
        }
        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
    }
    
    private static string PathToNamespace(string path, string root = "")
    {
        var dir = Path.GetDirectoryName(path);
        if (string.IsNullOrEmpty(dir)) return root;

        var parts = dir.Split(['/', '\\', '-', '_'], StringSplitOptions.RemoveEmptyEntries);
        for (int i = 0; i < parts.Length; i++)
        {
            var p = parts[i];
            var rest = p.Length > 1 ? p.Substring(1) : "";
            parts[i] = (char.IsDigit(p[0]) ? "_" : "") + char.ToUpperInvariant(p[0]) + rest;
        }
        return $"{root}{string.Join(".", parts)}";
    }
    
    public void EmitAllStructs(WgslFile[] wgslFiles, string projDir)
    {
        for (int n = 0; n < wgslFiles.Length; n++) {
            var path =  wgslFiles[n].NormalizedPath.Substring(projDir.Length + 1);
            wgslFiles[n] = wgslFiles[n] with{ NormalizedPath =  path };
        }
        // DebugInputs(wgslFiles, projDir);
        
        // sort for deterministic generation
        WgslFile.Sort(wgslFiles);
        
        var sb = new StringBuilder();
        
        foreach (var file in wgslFiles)
        {
            var normalizedPath = file.NormalizedPath;
            try {
                // --- clear state first!
                sb.Clear();
                fileStructs.Clear();
                fileNamespace = PathToNamespace(normalizedPath);
                
                // --- process after
                module = WgslParser.ParseWgsl(file.Content, normalizedPath);
                
                EmitModule();
                
                if (fileStructs.Count == 0) {
                    continue;
                }
                sb.Append("// <auto-generated />\n");
                sb.Append("using System;\n");
                sb.Append("using System.Numerics;\n");
                sb.Append("using System.Runtime.InteropServices;\n");
                sb.Append("using Friflo.Vectorization.WebGPU;\n");
                sb.Append("\n");
                // sb.Append("// ReSharper disable CheckNamespace\n");
                // sb.Append("// ReSharper disable InconsistentNaming\n");
                sb.Append($"namespace {fileNamespace};\n");
                sb.Append("\n\n");
                foreach (var structSource in fileStructs) {
                    if (!structSource.alreadyDeclared) {
                        sb.Append($"[Source(\"~/{normalizedPath}\")]\n");
                        sb.Append($"[StructLayout(LayoutKind.Sequential)]\n");
                    } 
                    sb.Append(structSource.source);
                }
            }
            catch (Exception exception) {
                sb.Append($"/* -------- Error parsing: {normalizedPath}\n");
                sb.Append(WgslUtils.GetExceptionAsString(exception));
                sb.Append("\n*/\n");
            }
            var source =  sb.ToString();
            var path = $"{projDir}/{file.NormalizedPath}.cs";

            File.WriteAllText(path, source, new UTF8Encoding(false));
        }
    }
        
    private void EmitModule()
    {
        var structs = module.Structs;
        var bindings = module.Bindings;
        if (bindings.Count == 0 || structs.Count == 0) {
            return;
        }
        foreach (var binding in bindings)
        {
            var typeName = binding.WgslType.Name;
            var wgslStruct = structs.FirstOrDefault(s => s.Name == typeName);
            if (wgslStruct == null) continue;
            AddStruct(wgslStruct);
        }
    }
    
    private void AddStruct(WgslStruct wgslStruct)
    {
        var sb = new StringBuilder();
        sb.Clear();
        sb.Append($"public struct {wgslStruct.Name} (\n");
        var csharpFields = new List<CSharpField>();
        
        foreach (var field in wgslStruct.Fields) {
            var csharpType = GetCSharpType(field.WgslType);
            csharpFields.Add(new CSharpField { Name = field.Name, Type = csharpType });
            sb.Append($"    {csharpType.typeName} {field.Name},\n");
        }
        if (csharpFields.Count > 0) {
            sb.Length -= 2;
        }
        sb.Append(")\n");
        sb.Append("{\n");

        foreach (var field in csharpFields) {
            sb.Append($"    public {field.Type.typeName} {field.Name} = {field.Name};\n");
        }
        sb.Append("}\n\n\n");
        var source          = sb.ToString();
        var alreadyDeclared = false;
        var fullQualifiedName   = $"{fileNamespace}-{wgslStruct.Name}";
        
        if (structMap.TryGetValue(fullQualifiedName, out var curSource)) {
            if (source == curSource) {
                source = $"/// Skipped identical duplicate of  <see cref=\"{wgslStruct.Name}\"/>\nfile partial class _info;\n\n\n";
                alreadyDeclared = true;
            }
        } else {
            structMap.Add(fullQualifiedName, source);
        }
        fileStructs.Add(new StructCode { source = source, alreadyDeclared = alreadyDeclared });
    }
    
    private CSharpType GetCSharpType(WgslType type)
    {
        var generics = type.Generics;
        var arg_0 = generics.Length > 0 ? generics[0].Name : "";
        
        var csharpType = CSharpType.GetCSharpType(type.Name, arg_0);
        
        var wgslStruct = module.Structs.FirstOrDefault(s => s.Name == csharpType.typeName);
        if (wgslStruct != null) {
            AddStruct(wgslStruct);
        }
        return csharpType;
    }
}