// <auto-generated />  path: shaders/particles/render.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.WGPU;
using System.Numerics;

namespace Shaders.Particles;


[Source("~/shaders/particles/render.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct Particle (Vector4 position, Vector4 velocity)
{
    [FieldOffset(  0)]  public  Vector4 position = position;
    [FieldOffset( 16)]  public  Vector4 velocity = velocity;
}


[Source("~/shaders/particles/render.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct FrameUniform (float time, float deltaTime, float padding0, float padding1)
{
    [FieldOffset(  0)]  public  float time      = time;
    [FieldOffset(  4)]  public  float deltaTime = deltaTime;
    [FieldOffset(  8)]  public  float padding0  = padding0;
    [FieldOffset( 12)]  public  float padding1  = padding1;
}


