// <auto-generated />  path: shaders/particles/update.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.WGPU;
using System.Numerics;

namespace Shaders.Particles;


/// Skipped identical duplicate of  <see cref="Particle"/>
file partial class _info;


/// Skipped identical duplicate of  <see cref="FrameUniform"/>
file partial class _info;


