using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

// ReSharper disable InconsistentNaming
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable UnusedParameter.Local
// ReSharper disable UnusedMember.Local
// ReSharper disable FieldCanBeMadeReadOnly.Global
namespace TestConsole;

public static partial class RenderTest
{
    /// generated by:  <see cref="Triangles"/>
    public static void DrawTriangles(RenderPass<MainWorld> renderPass, InBuffer<VertexData> triangles)
	{
        var buffers =
        GpuBuffers.Create(triangles, nameof(triangles));
        
        var pass        = renderPass.Value;
		var recorder	= pass.recorder;
		var device		= recorder.Device;
		recorder.Init(Triangles_GPU_KernelId, "Triangles"u8);
        
        recorder.RequireRead(triangles);
        
        ref var effect = ref device.GetEffect(Triangles_GPU_KernelId, Triangles_GPU_WgslHash); // Each device has its own GpuEffect[] array
        if (!effect.IsCreated) {
            effect = ref Triangles_GPU_CreateEffect(device);
        }
        pass.SetPipeline(effect.renderPipeline);
        
        // Creation of a buffer bind group is expensive in wgpu. So we cache them. Cache has two entries.
        var bufferGroup = effect.bufferCache.GetGroup(buffers.hash);
        if (!bufferGroup.IsCreated) {
            Span<BindGroupEntry> entries = stackalloc BindGroupEntry[1];
            entries[0] = WgpuBindGroup.From  (0, triangles.Buffer);
            bufferGroup = recorder.CreateBindGroup(effect.bufferLayout, entries, "Triangles_buffers"u8);
            device.UpdateBufferCache(Triangles_GPU_KernelId, bufferGroup, buffers.hash);
        }
        pass.SetBindGroup(0, bufferGroup, buffers.hash);
        
        var uniforms = new Triangles_GPU_Uniforms {
            count           = buffers.length,
            triangles_off   = triangles.Offset,
        };
        pass.SetUniformBindGroup(1, ref effect, uniforms, "Triangles_uniforms"u8);
        
        pass.Draw(buffers.length, 1, 0, 0);
	}
    
    [StructLayout(LayoutKind.Explicit, Size = 16)]  // WGSL uses std140/std430 Layout
    private struct Triangles_GPU_Uniforms
    {
        [FieldOffset( 0)]    public int      count;
        [FieldOffset( 4)]    public int      triangles_off;
    }
    
    private static readonly int Triangles_GPU_KernelId            =  KernelRegistry.NewKernelId("TrianglesShader");
    private const ulong         Triangles_GPU_BufferLayoutKey     =  0x47;  // unique key set by Generator
    private const ulong         Triangles_GPU_UniformLayoutKey    =  0x11;  // unique key set by Generator
    private static ulong        Triangles_GPU_WgslHash            => 0x123; // support Hot-Relead
    
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref WgpuEffect Triangles_GPU_CreateEffect(WgpuDevice device)
    {
        var bufferLayout = device.GetBindGroupLayout(Triangles_GPU_BufferLayoutKey);
        if (!bufferLayout.IsCreated) {
            Span<WgpuLayoutEntry> buffers = stackalloc WgpuLayoutEntry[3];
            buffers[0] = WgpuLayoutEntry.ReadOnlyStorage (0);   // var<storage, read>       weight_arr:     array<f32>;
            buffers[1] = WgpuLayoutEntry.ReadOnlyStorage (1);   // var<storage, read>       input_arr:      array<f32>;
            buffers[2] = WgpuLayoutEntry.ReadWriteStorage(2);   // var<storage, read_write> output_arr:     array<f32>;
            bufferLayout = device.CreateBindGroupLayout(buffers, false, Triangles_GPU_BufferLayoutKey, "Triangles_buffers"u8);
        }
        var uniformLayout = device.GetBindGroupLayout(Triangles_GPU_UniformLayoutKey);
        if (!uniformLayout.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0] = WgpuLayoutEntry.Uniform(0);            // var<uniform>              uniforms
            uniformLayout   = device.CreateBindGroupLayout(uniform, true, Triangles_GPU_UniformLayoutKey, "Triangles_uniforms"u8);
        }
        var shaderModule    = device.CreateShaderModule(Triangles_GPU_Shader(), "Triangles"u8);
        var pipeline        = device.CreateComputePipeline(shaderModule, bufferLayout, uniformLayout, "Triangles"u8);
        
        return ref device.CreateEffect(Triangles_GPU_KernelId, Triangles_GPU_WgslHash, pipeline, bufferLayout, uniformLayout);
    }
    
    private static ReadOnlySpan<byte> Triangles_GPU_Shader() => default;          // TODO return WGSL
}