using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.GPU;
using Friflo.Vectorization.GPU.Runtime;
using Friflo.Vectorization.WebGPU;
using Friflo.Vectorization.WebGPU.Runtime;

// ReSharper disable InconsistentNaming
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable UnusedParameter.Local
// ReSharper disable UnusedMember.Local
// ReSharper disable FieldCanBeMadeReadOnly.Global
namespace TestConsole;

public partial struct Renderer
{
    /// generated by:  <see cref="Triangles"/>
    public static void DrawTriangles(
        RenderPass<MainWorld>   renderPass,
        InBuffer<VertexData>    triangles,
        RenderPipelineConfig    config = default)
	{
        var buffers =
        GpuBuffers.Create(triangles, nameof(triangles));
        
        var pass        = renderPass.Value;
		var recorder	= pass.recorder;
		var device		= recorder.Device;
		recorder.Init(Triangles_GPU_ShaderId, "Triangles"u8);
        
        recorder.RequireRead(triangles);

        ref var effect = ref device.GetShaderEffect(Triangles_GPU_ShaderId, Triangles_GPU_WgslHash); // Each device has its own GpuEffect[] array
        if (!effect.IsCreated) {
            effect = ref Triangles_GPU_CreateEffect(device, config);
        }
        pass.SetPipeline(effect.renderPipeline);
        
        // Creation of a buffer bind group is expensive in wgpu. So we cache them. Cache has two entries.
        var bufferGroup = effect.bufferCache.GetGroup(buffers.hash);
        if (!bufferGroup.IsCreated) {
            Span<BindGroupEntry> entries = stackalloc BindGroupEntry[1];
            entries[0] = WgpuBindGroup.From  (0, triangles.Buffer);
            bufferGroup = recorder.CreateBindGroup(effect.bufferLayout, entries, "Triangles_buffers"u8);
            device.UpdateShaderCache(Triangles_GPU_ShaderId, bufferGroup, buffers.hash);
        }
        pass.SetBindGroup(0, bufferGroup, buffers.hash);
        
        /* var uniforms = new Triangles_GPU_Uniforms {
            count           = buffers.length,
            triangles_off   = triangles.Offset,
        };
        pass.SetUniformBindGroup(1, ref effect, uniforms, "Triangles_uniforms"u8); */
        
        pass.Draw(buffers.length, 1, 0, 0);
	}
    
    [StructLayout(LayoutKind.Explicit, Size = 16)]  // WGSL uses std140/std430 Layout
    private struct Triangles_GPU_Uniforms
    {
        [FieldOffset( 0)]    public int      count;
        [FieldOffset( 4)]    public int      triangles_off;
    }
    
    private static readonly int Triangles_GPU_ShaderId            =  ShaderRegistry.NewShaderId("TrianglesShader");
    private const ulong         Triangles_GPU_BufferLayoutKey     =  0x47;  // unique key set by Generator
    private const ulong         Triangles_GPU_UniformLayoutKey    =  0x11;  // unique key set by Generator
    private static ulong        Triangles_GPU_WgslHash            => 0x123; // support Hot-Relead
    
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref WgpuShaderEffect Triangles_GPU_CreateEffect(WgpuDevice device, RenderPipelineConfig config)
    {
        var bufferLayout = device.GetBindGroupLayout(Triangles_GPU_BufferLayoutKey);
        if (!bufferLayout.IsCreated) {
            Span<WgpuLayoutEntry> buffers = stackalloc WgpuLayoutEntry[1];
            buffers[0] = WgpuLayoutEntry.ReadOnlyStorage (0);   // @group(0) @binding(0) var<storage, read> mesh_data: TriangleStorage;
            bufferLayout = device.CreateBindGroupLayout(buffers, ShaderStage.Vertex, false, Triangles_GPU_BufferLayoutKey, "Triangles_buffers"u8);
        }
        WgpuBindGroupLayout uniformLayout = default;
        /* var uniformLayout = device.GetBindGroupLayout(Triangles_GPU_UniformLayoutKey);
        if (!uniformLayout.IsCreated) {
            Span<WgpuLayoutEntry> uniform = stackalloc WgpuLayoutEntry[1];
            uniform[0] = WgpuLayoutEntry.Uniform(0);            // var<uniform>              uniforms
            uniformLayout   = device.CreateBindGroupLayout(uniform, ShaderStage.Vertex, true, Triangles_GPU_UniformLayoutKey, "Triangles_uniforms"u8);
        } */
        var shaderModule = device.CreateShaderModule(Triangles_GPU_Shader(), "Triangles"u8);
        
        Span<WgpuBindGroupLayout> layouts = stackalloc WgpuBindGroupLayout[1];
        layouts[0] = bufferLayout;
        // layouts[1] = uniformLayout;

        var pipeline = device.CreateRenderPipeline(shaderModule, layouts, config, "vs_main"u8, "fs_main"u8, "Triangles"u8);
        
        return ref device.CreateShaderEffect(Triangles_GPU_ShaderId, Triangles_GPU_WgslHash, pipeline, bufferLayout, uniformLayout);
    }
    
    private static ReadOnlySpan<byte> Triangles_GPU_Shader() => WgpuResource.GetResource(typeof(Renderer).Assembly, "Tests-Console.Shaders.triangle.wgsl");
}