<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationIcon>Assets/friflo.ico</ApplicationIcon>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SDL3-CS"           Version="3.4.10.3" />
      <PackageReference Include="SDL3-CS.Windows"   Version="3.4.10.3" />
      <PackageReference Include="SDL3-CS.MacOS"     Version="3.4.10.3" />
      <PackageReference Include="StbImageSharp" Version="2.30.16" />
        
      <ProjectReference Include="..\Vectorization.Attributes\Friflo.Vectorization.Attributes.csproj" />
      <ProjectReference Include="..\Vectorization.WebGPU\Friflo.Vectorization.WebGPU.csproj" />
      <ProjectReference Include="..\Vectorization.Generators\Friflo.Vectorization.Generators.csproj"                     OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
      <ProjectReference Include="..\Vectorization.Generators.CodeFixes\Friflo.Vectorization.Generators.CodeFixes.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
      <ProjectReference Include="..\Friflo.WGPU.ImDraw\Friflo.WGPU.ImDraw.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <CompilerVisibleProperty Include="MSBuildProjectDirectory" />  
      <EmbeddedResource Include="shaders\**\*.wgsl" />
      <!-- <AdditionalFiles  Include="shaders\**\*.wgsl" /> -->
    </ItemGroup>
    <PropertyGroup>
      <!-- workaround for: https://youtrack.jetbrains.com/issue/RIDER-141199 -->  
      <AdditionalFileItemNames>$(AdditionalFileItemNames);EmbeddedResource</AdditionalFileItemNames>
    </PropertyGroup>
    
    <ItemGroup>
      <EmbeddedResource Include="Assets/img/*.png" />
      <EmbeddedResource Include="Assets/**/*.bin" />
    </ItemGroup>
    
    <ItemGroup>
      <EmbeddedResource Include="Assets/wgpu-transparent-light-128x128.bmp" />
      <EmbeddedResource Include="Assets/wgpu-transparent-dark-128x128.bmp" />
    </ItemGroup>
    
    
    <ItemGroup>
      <!-- 1. Ensures Transpiler is build first -->
      <ProjectReference Include="../Friflo.WGSL.Transpiler/Friflo.WGSL.Transpiler.csproj" ReferenceOutputAssembly="false" />
    </ItemGroup>
    
    <Target Name="RunTranspiler" BeforeTargets="BeforeBuild">
      <!-- Ensures Transpiler.dll exsists in bin folder for local development -->
      <MSBuild Projects="../Friflo.WGSL.Transpiler/Friflo.WGSL.Transpiler.csproj" Targets="Build" Properties="Configuration=$(Configuration);TargetFramework=net8.0" />
      
      <Exec Command="dotnet &quot;$(MSBuildThisFileDirectory)../Friflo.WGSL.Transpiler/bin/$(Configuration)/net8.0/Friflo.WGSL.Transpiler.dll&quot; &quot;$(MSBuildProjectDirectory)&quot;" />
    </Target>

</Project>
