// <auto-generated />  path: shaders/renderTest/deform.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using System.Numerics;

namespace Shaders.RenderTest;


[Source("~/shaders/renderTest/deform.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct VertexData (Vector4 position, Vector4 color)
{
    [FieldOffset(  0)]  public  Vector4 position = position;
    [FieldOffset( 16)]  public  Vector4 color    = color;
}


[Source("~/shaders/renderTest/deform.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct TimeUniform (float time)
{
    [FieldOffset(  0)]  public  float time = time;
}


