// <auto-generated />
using System;
using System.Numerics;
using Friflo.Vectorization.WebGPU;

namespace Shaders.RenderTest;


[Source("~/shaders/renderTest/raymarcher_no_texture.wgsl")]
public struct ShadertoyUniforms (
    Vector3 iResolution,
    float iTime)
{
    public Vector3 iResolution = iResolution;
    public float iTime = iTime;
}

