// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.RenderTest;


[Source("~/shaders/renderTest/triangle.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct VertexData (
    Vector4 position,
    Vector4 color)
{
    public  Vector4 position = position;
    public  Vector4 color    = color;
}


[Source("~/shaders/renderTest/triangle.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct TriangleStorage (
    VertexData triangles)
{
    public  VertexData triangles = triangles;
}


[Source("~/shaders/renderTest/triangle.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct MyUniforms (
    Vector4 tint_color)
{
    public  Vector4 tint_color = tint_color;
}


