// <auto-generated />  path: shaders/renderTest/triangle.wgsl.cs
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using System.Numerics;

namespace Shaders.RenderTest;


[Source("~/shaders/renderTest/triangle.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct VertexData (Vector4 position, Vector4 color)
{
    [FieldOffset(  0)]  public  Vector4 position = position;
    [FieldOffset( 16)]  public  Vector4 color    = color;
}


[Source("~/shaders/renderTest/triangle.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct MyUniforms (Vector4 tint_color)
{
    [FieldOffset(  0)]  public  Vector4 tint_color = tint_color;
}


