// <auto-generated />  path: shaders/renderTest/triangle.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.WGPU;
using System.Numerics;

namespace Shaders.RenderTest;


/// Skipped identical duplicate of  <see cref="VertexData"/>
file partial class _info;


[Source("~/shaders/renderTest/triangle.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct MyUniforms (Vector4 tint_color)
{
    [FieldOffset(  0)]  public  Vector4 tint_color = tint_color;
}


