<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <GenerateProgramFile>false</GenerateProgramFile>

        <!-- packaging -->
        <PublishRepositoryUrl>false</PublishRepositoryUrl>
        <IsPackable>false</IsPackable>
        <LangVersion>14</LangVersion>
        <!-- packaging: end -->
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <!-- <DefineConstants>$(DefineConstants);MKL</DefineConstants> -->
    </PropertyGroup>

    <ItemGroup>
        <!-- <PackageReference Include="intelmkl.redist.win-x64" Version="2026.0.0.901" Condition="$(DefineConstants.Contains('MKL'))"/> -->
        
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
        <PackageReference Include="System.Numerics.Tensors" Version="10.0.5" />
        <PackageReference Include="NUnit" Version="4.5.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        
        <!-- Not used anymore for testing
        <PackageReference Include="Silk.NET.WebGPU" Version="2.23.0" />
        <PackageReference Include="Silk.NET.WebGPU.Extensions.WGPU" Version="2.23.0" />
        <PackageReference Include="Silk.NET.WebGPU.Native.WGPU" Version="2.23.0" />
        -->
    </ItemGroup>
    
    <ItemGroup>
      <Compile Remove="Generators/Kernel/Lab/Patterns/SilkPattern.cs" />
      <Compile Remove="Generators/Kernel/Lab/SilkWebGPU/**" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Tests\Tests.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Vectorization.Generators\Friflo.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\Vectorization.Generators.CodeFixes\Friflo.Generators.CodeFixes.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
    
    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>
    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.g.cs" />
    </ItemGroup>
    
    <ItemGroup>
        <None Remove="*.csproj.lscache" />
    </ItemGroup>

</Project>
