//HintName: VerifyVectorize/MyExample/MoveExample.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;


namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Vector method generated for: <see cref="MoveExample"/>.</summary>
        public void MoveExampleVector(Span<float> position, ReadOnlySpan<float> velocity, float deltaTime, bool vectorized = true)
        {
            int count = position.Length;
            int n = 0;
            if (vectorized) {
                if (Avx.IsSupported) {
                    n = _MoveExample_Avx(count, position, velocity, deltaTime);
                }
            }
            for (; n < count; n++) {
                MoveExample(ref position[n], velocity[n], deltaTime);
            }
        }

    #region private members

        // [Layout: AoS-Vertical]  - lane-native speed
        [SkipLocalsInit]
        private static unsafe int _MoveExample_Avx(int count,
            Span<float> position,
            ReadOnlySpan<float> velocity,
            float deltaTime)
        {
            int i = 0;
            count -= 32;
            if (i > count) {
                return 0;
            }
            if (position.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(position));
            if (velocity.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(velocity));

            // --- Locals
            var deltaTime_scalar = Vector256.Create(deltaTime);

            fixed (float* position_first = position)
            fixed (float* velocity_first = velocity)
            {
                float* position_ptr = (float*)position_first;
                float* velocity_ptr = (float*)velocity_first;

                for (; i <= count; i += 32)
                {
                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);  // Single
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);  // Single
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);  // Single
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);  // Single

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr +  0);  // Single
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8);  // Single
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16);  // Single
                    Vector256<float> velocity_3 = Avx.LoadVector256(velocity_ptr + 24);  // Single

                    // --- 2. Compute
                    // position += velocity * deltaTime;
                    position_0 = Fma.MultiplyAdd(velocity_0, deltaTime_scalar, position_0);
                    position_1 = Fma.MultiplyAdd(velocity_1, deltaTime_scalar, position_1);
                    position_2 = Fma.MultiplyAdd(velocity_2, deltaTime_scalar, position_2);
                    position_3 = Fma.MultiplyAdd(velocity_3, deltaTime_scalar, position_3);

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);

                    position_ptr += 32;
                    velocity_ptr += 32;
                }
            }
            return i;
        }

    #endregion
    }
}
