//HintName: VerifyVectorize.MyExample/Vector3_Dot.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;


namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Vector method generated for: <see cref="Vector3_Dot"/>.</summary>
        public static void Vector3_DotVector(Span<float> result, ReadOnlySpan<global::System.Numerics.Vector3> vec1, ReadOnlySpan<global::System.Numerics.Vector3> vec2, bool vectorized = true)
        {
            int count = result.Length;
            int n = 0;
            if (vectorized) {
                if (Avx.IsSupported) {
                    n = _Vector3_Dot_Avx(count, result, vec1, vec2);
                }
            }
            for (; n < count; n++) {
                Vector3_Dot(ref result[n], vec1[n], vec2[n]);
            }
        }

    #region private members

        // [Layout: AoS-Vertical]  - lane-native speed
        [SkipLocalsInit]
        private static unsafe int _Vector3_Dot_Avx(int count,
            Span<float> result,
            ReadOnlySpan<global::System.Numerics.Vector3> vec1,
            ReadOnlySpan<global::System.Numerics.Vector3> vec2)
        {
            int i = 0;
            count -= 8;
            if (i > count) {
                return 0;
            }
            if (result.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(result));
            if (vec1.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(vec1));
            if (vec2.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(vec2));

            // --- Locals
            Vector256<int> result_mask_0 = Vector256.Create(0, 0, 0, 1, 1, 1, 2, 2);
            Vector256<int> result_mask_1 = Vector256.Create(2, 3, 3, 3, 4, 4, 4, 5);
            Vector256<int> result_mask_2 = Vector256.Create(5, 5, 6, 6, 6, 7, 7, 7);

            fixed (float* result_first = result)
            fixed (global::System.Numerics.Vector3* vec1_first = vec1)
            fixed (global::System.Numerics.Vector3* vec2_first = vec2)
            {
                for (; i <= count; i += 8)
                {
                    float* result_ptr = (float*)(result_first + i);
                    float* vec1_ptr = (float*)(vec1_first + i);
                    float* vec2_ptr = (float*)(vec2_first + i);

                    // --- 1. Load
                    Vector256<float> result_0 = Avx.LoadVector256(result_ptr);      // Single

                    Vector256<float> vec1_0 = Avx.LoadVector256(vec1_ptr +  0);   // Vector3
                    Vector256<float> vec1_1 = Avx.LoadVector256(vec1_ptr +  8);   // Vector3
                    Vector256<float> vec1_2 = Avx.LoadVector256(vec1_ptr + 16);   // Vector3

                    Vector256<float> vec2_0 = Avx.LoadVector256(vec2_ptr +  0);   // Vector3
                    Vector256<float> vec2_1 = Avx.LoadVector256(vec2_ptr +  8);   // Vector3
                    Vector256<float> vec2_2 = Avx.LoadVector256(vec2_ptr + 16);   // Vector3

                    // --- 2. Compute

                    // --- 3. Store
                }
            }
            return i;
        }

    #endregion
    }
}
