//HintName: VerifyVectorize.MyExample/MoveExample.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Vector method generated for: <see cref="MoveExample"/>.</summary>
        public void MoveExampleVector(Span<float> position, Span<float> velocity, bool vectorized = true)
        {
            int n = 0;
            if (vectorized) {
                if (Avx.IsSupported) {
                    n = _MoveExample_Avx(positionSpan, velocitySpan);
                }
            }
            for (; n < _entities.Length; n++) {
                MoveExample(ref position, velocity);
            }
        }

    #region private members

        [SkipLocalsInit]
        private static unsafe int _MoveExample_Avx(
            Span<float> position,
            Span<float> velocity)
        {
            int i = 0;
            var end = position.Length - 32;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            fixed (float* position_first = position)
            fixed (float* velocity_first = velocity)
            {
                for (; i <= end; i += 32)
                {
                    float* position_ptr = (float*)(position_first + i);
                    float* velocity_ptr = (float*)(velocity_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);  // Single
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);  // Single
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);  // Single
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);  // Single

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr +  0);  // Single
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8);  // Single
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16);  // Single
                    Vector256<float> velocity_3 = Avx.LoadVector256(velocity_ptr + 24);  // Single

                    // --- 2. Compute
                    // position *= velocity;
                    position_0 = Avx.Multiply(position_0, velocity_0);
                    position_1 = Avx.Multiply(position_1, velocity_1);
                    position_2 = Avx.Multiply(position_2, velocity_2);
                    position_3 = Avx.Multiply(position_3, velocity_3);

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);
                }
            }
            return i;
        }

    #endregion
    }
}
