//HintName: VerifyVectorize.MyExample/Vector4Cross.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;


namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Vector method generated for: <see cref="Vector4Cross"/>.</summary>
        public static void Vector4CrossVector(Span<global::System.Numerics.Vector4> result, ReadOnlySpan<global::System.Numerics.Vector4> vec1, ReadOnlySpan<global::System.Numerics.Vector4> vec2, bool vectorized = true)
        {
            int n = 0;
            if (vectorized) {
                if (Avx.IsSupported) {
                    n = _Vector4Cross_Avx(result, vec1, vec2);
                }
            }
            int len = result.Length;
            for (; n < len; n++) {
                Vector4Cross(ref result[n], vec1[n], vec2[n]);
            }
        }

    #region private members

        [SkipLocalsInit]
        private static unsafe int _Vector4Cross_Avx(
            Span<global::System.Numerics.Vector4> result,
            ReadOnlySpan<global::System.Numerics.Vector4> vec1,
            ReadOnlySpan<global::System.Numerics.Vector4> vec2)
        {
            int i = 0;
            var end = result.Length - 8;
            if (i > end) {
                return 0;
            }
            // [Layout: Horizontal]    - lane-native speed + Deinterleave penalty
            fixed (global::System.Numerics.Vector4* result_first = result)
            fixed (global::System.Numerics.Vector4* vec1_first = vec1)
            fixed (global::System.Numerics.Vector4* vec2_first = vec2)
            {
                for (; i <= end; i += 8)
                {
                    float* result_ptr = (float*)(result_first + i);
                    float* vec1_ptr = (float*)(vec1_first + i);
                    float* vec2_ptr = (float*)(vec2_first + i);

                    // --- 1. Load
                    Vector256<float> result_0 = Avx.LoadVector256(result_ptr +  0);   // Vector4
                    Vector256<float> result_1 = Avx.LoadVector256(result_ptr +  8);   // Vector4
                    Vector256<float> result_2 = Avx.LoadVector256(result_ptr + 16);   // Vector4
                    Vector256<float> result_3 = Avx.LoadVector256(result_ptr + 24);   // Vector4
                    (result_0, result_1, result_2, result_3) = AvxVector4.Deinterleave(result_0, result_1, result_2, result_3);

                    Vector256<float> vec1_0 = Avx.LoadVector256(vec1_ptr +  0);   // Vector4
                    Vector256<float> vec1_1 = Avx.LoadVector256(vec1_ptr +  8);   // Vector4
                    Vector256<float> vec1_2 = Avx.LoadVector256(vec1_ptr + 16);   // Vector4
                    Vector256<float> vec1_3 = Avx.LoadVector256(vec1_ptr + 24);   // Vector4
                    (vec1_0, vec1_1, vec1_2, vec1_3) = AvxVector4.Deinterleave(vec1_0, vec1_1, vec1_2, vec1_3);

                    Vector256<float> vec2_0 = Avx.LoadVector256(vec2_ptr +  0);   // Vector4
                    Vector256<float> vec2_1 = Avx.LoadVector256(vec2_ptr +  8);   // Vector4
                    Vector256<float> vec2_2 = Avx.LoadVector256(vec2_ptr + 16);   // Vector4
                    Vector256<float> vec2_3 = Avx.LoadVector256(vec2_ptr + 24);   // Vector4
                    (vec2_0, vec2_1, vec2_2, vec2_3) = AvxVector4.Deinterleave(vec2_0, vec2_1, vec2_2, vec2_3);

                    // --- 2. Compute
                    // result = Vector4.Cross(vec1, vec2);
                    //   Cross arg[0]
                    Vector256<float> temp0_0 = vec1_0;
                    Vector256<float> temp0_1 = vec1_1;
                    Vector256<float> temp0_2 = vec1_2;
                    Vector256<float> temp0_3 = vec1_3;

                    //   Cross arg[1]
                    Vector256<float> temp1_0 = vec2_0;
                    Vector256<float> temp1_1 = vec2_1;
                    Vector256<float> temp1_2 = vec2_2;
                    Vector256<float> temp1_3 = vec2_3;

                    result_0 = Fma.MultiplySubtract(temp0_1, temp1_2, Avx.Multiply(temp0_2, temp1_1));
                    result_1 = Fma.MultiplySubtract(temp0_2, temp1_0, Avx.Multiply(temp0_0, temp1_2));
                    result_2 = Fma.MultiplySubtract(temp0_0, temp1_1, Avx.Multiply(temp0_1, temp1_0));
                    result_3 = Avx.Multiply(temp0_3, temp1_3);

                    // --- 3. Store
                    (result_0, result_1, result_2, result_3) = AvxVector4.Interleave(result_0, result_1, result_2, result_3);
                    Avx.Store(result_ptr +  0, result_0);
                    Avx.Store(result_ptr +  8, result_1);
                    Avx.Store(result_ptr + 16, result_2);
                    Avx.Store(result_ptr + 24, result_3);
                }
            }
            return i;
        }

    #endregion
    }
}
