//HintName: VerifyVectorize/MyExample/InverseSqrt.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;


namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Vector method generated for: <see cref="InverseSqrt"/>.</summary>
        public static void InverseSqrtVector(Span<float> position, bool vectorized = true)
        {
            int count = position.Length;
            int n = 0;
            if (vectorized) {
                if (Avx.IsSupported) {
                    n = _InverseSqrt_Avx(count, position);
                }
            }
            for (; n < count; n++) {
                InverseSqrt(ref position[n]);
            }
        }

    #region private members

        // [Layout: AoS-Vertical]  - lane-native speed
        [SkipLocalsInit]
        private static unsafe int _InverseSqrt_Avx(int count,
            Span<float> position)
        {
            int i = 0;
            count -= 32;
            if (i > count) {
                return 0;
            }
            if (position.Length < count) VectorUtils.ThrowBufferTooSmall(nameof(position));

            // --- Locals
            var const0_scalar = Vector256.Create<float>(5); // literal

            fixed (float* position_first = position)
            {
                float* position_ptr = (float*)position_first;

                for (; i <= count; i += 32)
                {
                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);  // Single
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);  // Single
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);  // Single
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);  // Single

                    // --- 2. Compute
                    // position = 5 / MathF.Sqrt(position);
                    position_0 = Avx.Multiply(Avx.ReciprocalSqrt(position_0), const0_scalar);
                    position_1 = Avx.Multiply(Avx.ReciprocalSqrt(position_1), const0_scalar);
                    position_2 = Avx.Multiply(Avx.ReciprocalSqrt(position_2), const0_scalar);
                    position_3 = Avx.Multiply(Avx.ReciprocalSqrt(position_3), const0_scalar);

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);

                    position_ptr += 32;
                }
            }
            return i;
        }

    #endregion
    }
}
