//HintName: VerifyQuery/MyExample/NoComponentParameter.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using Friflo.Engine.ECS;

namespace VerifyQuery
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="NoComponentParameter"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public static ArchetypeQuery NoComponentParameterQuery(EntityStore _store)
        {
            var _query = _NoComponentParameter_GetQuery(_store);
            foreach (var entity in _query.Entities)
            {
                NoComponentParameter();
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _NoComponentParameter_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery
            _NoComponentParameter_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery)
                EntityStore.UserDataGet(_store, _NoComponentParameter_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query();

            EntityStore.UserDataSet(_store, _NoComponentParameter_Slot, _query);
            return _query;
        }

    #endregion
    }
}
