<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>

    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> <!-- required for Superpower.dll -->
    <IsRoslynComponent>true</IsRoslynComponent>
    <AnalyzerLanguage>cs</AnalyzerLanguage>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoPackageAnalysis>true</NoPackageAnalysis>
      
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Friflo.Generators</RootNamespace>
	<AssemblyName>Friflo.Generators</AssemblyName>
    <LangVersion>14.0</LangVersion>
      
    <!-- packaging -->
    <PackageVersion>0.0.0</PackageVersion>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
    <FileVersion>0.0.0.0</FileVersion>

    <Title>friflo ECS - Source Generator</Title>
    <Authors>Ullrich Praetz</Authors>
    <Description>Source Generator to generate Query methods for: friflo ECS</Description>
    <Copyright>Ullrich Praetz</Copyright>
    <PackageProjectUrl>https://github.com/friflo/Friflo.Vectorization</PackageProjectUrl>
    <RepositoryUrl>https://github.com/friflo/Friflo.Vectorization</RepositoryUrl>
    <PackageTags>ecs, entity-component-system, gamedev, game-engine, unity, godot, monogame, fna, stride, flax, dots, entt, flecs</PackageTags>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageIconUrl></PackageIconUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>package-icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>false</PublishRepositoryUrl>
    <!-- <IncludeSymbols>true</IncludeSymbols> -->
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedAllSources>true</EmbedAllSources>
    <PackageId>Friflo.Generators</PackageId>
    <!-- packaging: end -->
  </PropertyGroup>

  <!-- packaging -->
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="All" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Friflo.Generators.CodeFixes\Friflo.Generators.CodeFixes.csproj" PrivateAssets="all" />
    
    <!-- <ProjectReference Include="..\Friflo.WGSL.Transpiler\Friflo.WGSL.Transpiler.csproj" SetTargetFramework="TargetFramework=netstandard2.0" PrivateAssets="all" /> -->
    <!-- Add Transpiler via source files instead of ProjectReference to prevent:
         1. Error CS2012 : Cannot open 'Friflo.WGSL.Transpiler.dll' for writing - The process cannot access the file 'Friflo.WGSL.Transpiler.dll' because it is being used by another process. 
         2. The hassle involved deploying the additional Friflo.WGSL.Transpiler.dll "to analyzers/dotnet/cs" -->
    <Compile Include="../Friflo.WGSL.Transpiler/**/*.cs"
             Exclude="../Friflo.WGSL.Transpiler/obj/**/*.cs;../Friflo.WGSL.Transpiler/*.cs"
             LinkBase="Transpiler" />
  </ItemGroup>
  <PropertyGroup>
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
  </PropertyGroup>
  
  <Target Name="GetDependencyTargetPaths">
    <ItemGroup>
      <!-- <TargetPathWithTargetPlatformMoniker Include="$(TargetDir)Superpower.dll" IncludeRuntimeDependency="false" /> -->
      <TargetPathWithTargetPlatformMoniker Include="$(TargetDir)Friflo.WGSL.Transpiler.dll" IncludeRuntimeDependency="false" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <None Include="..\package-icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <PropertyGroup>
    <NoWarn>1591</NoWarn>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>
  <!-- packaging: end -->

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
     <!-- recommendation: use lowest version possible version.        "4.8.0" required for .NET 8 SDK / C# 12 - this SDK ships this version -->
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />
    
     <!-- recommendation: use latest version -->
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers"  Version="5.6.0"  PrivateAssets="all" />
  </ItemGroup>

  <Target Name="_AddAnalyzersToPackage" BeforeTargets="_GetPackageFiles">
    <ItemGroup >
      <None Include="$(OutputPath)\$(AssemblyName).dll"           Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
      <None Include="$(OutputPath)\$(AssemblyName).CodeFixes.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
      <None Include="$(OutputPath)\Friflo.WGSL.Transpiler.dll"    Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
      <!-- <None Include="$(OutputPath)\Superpower.dll"           Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" /> -->
      <!-- <None Include="$(OutputPath)\System.Text.Json.dll"     Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" /> -->
    </ItemGroup>
  </Target>
  
  <ItemGroup>
    <EmbeddedResource Include="..\Tests-Generators-Verify\Generators\Static\AvxVector2.cs">  <Link>Files\AvxVector2.g.cs</Link> </EmbeddedResource>
    <EmbeddedResource Include="..\Tests-Generators-Verify\Generators\Static\AvxVector3.cs">  <Link>Files\AvxVector3.g.cs</Link> </EmbeddedResource>
    <EmbeddedResource Include="..\Tests-Generators-Verify\Generators\Static\AvxVector4.cs">  <Link>Files\AvxVector4.g.cs</Link> </EmbeddedResource>
    <EmbeddedResource Include="..\Tests-Generators-Verify\Generators\Static\MathUtils.cs">   <Link>Files\MathUtils.g.cs</Link>  </EmbeddedResource>
    <EmbeddedResource Include="..\Tests-Generators-Verify\Generators\Static\VectorUtils.cs"> <Link>Files\VectorUtils.g.cs</Link></EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Remove="*.csproj.lscache" />
  </ItemGroup>
</Project>
