// <auto-generated />
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;

namespace Shaders.RenderTest;


[Source("~/shaders/renderTest/raymarcher_no_texture.wgsl")]
[StructLayout(LayoutKind.Sequential)]
public struct ShadertoyUniforms (
    Vector3 iResolution,
    float   _pad,
    float   iTime,
    Vector3 _pad2)
{
    public  Vector3 iResolution = iResolution;
    public  float   _pad        = _pad;
    public  float   iTime       = iTime;
    public  Vector3 _pad2       = _pad2;
}


