// <auto-generated />
using System;
using System.Numerics;
using Friflo.Vectorization.WebGPU;

namespace Shaders.RenderTest;


[Source("~/shaders/renderTest/triangle.wgsl")]
public struct VertexData (
    Vector4 position,
    Vector4 color)
{
    public Vector4 position = position;
    public Vector4 color = color;
}

/// Skipped identical duplicate of  <see cref="VertexData"/>
file partial class _info;

[Source("~/shaders/renderTest/triangle.wgsl")]
public struct TriangleStorage (
    VertexData triangles)
{
    public VertexData triangles = triangles;
}

[Source("~/shaders/renderTest/triangle.wgsl")]
public struct MyUniforms (
    Vector4 tint_color,
    Vector4 model_offset)
{
    public Vector4 tint_color = tint_color;
    public Vector4 model_offset = model_offset;
}

