// <auto-generated />  path: shaders/renderTest/triangle.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using System.Numerics;

namespace Shaders.RenderTest;


/// Skipped identical duplicate of  <see cref="VertexData"/>
file partial class _info;


[Source("~/shaders/renderTest/triangle.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 96)]
public struct MyUniforms (in Matrix4x4 modelViewProjectionMatrix, Vector4 tint_color, Vector4 model_offset)
{
    [FieldOffset(  0)]  public  Matrix4x4 modelViewProjectionMatrix = modelViewProjectionMatrix;
    [FieldOffset( 64)]  public  Vector4   tint_color                = tint_color;
    [FieldOffset( 80)]  public  Vector4   model_offset              = model_offset;
}


