name: Generators-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install & Setup Mesa (Headless GPU)
      run: |
        sudo apt-get update
        sudo apt-get install -y libvulkan1 mesa-vulkan-drivers libx11-6 libx11-xcb1 libxcb-dri3-0 libwayland-client0
        
        # ICD-Fix: locate driver and make available for Loader
        mkdir -p ./vulkan_icd
        ICD_PATH=$(find /usr/share/vulkan/icd.d/ -name "*lvp*.json" | head -n 1)
        cp "$ICD_PATH" ./vulkan_icd/lvp_icd.json
        chmod 644 ./vulkan_icd/lvp_icd.json

    - name: Restore dependencies
      working-directory: ./
      run: dotnet restore -r linux-x64

    - name: Build
      working-directory: ./
      run: |
        dotnet build src/Tests-Generators/Tests-Generators-Code.csproj          -r linux-x64 -c Debug -p:CopyLocalLockFileAssemblies=true
        dotnet build src/Tests-Generators-Verify/Tests-Generators-Verify.csproj -r linux-x64 -c Debug -p:CopyLocalLockFileAssemblies=true

    - name: Test
      env:
        WGPU_BACKEND: vulkan
        # we use relative path to our copy
        VK_ICD_FILENAMES: ${{ github.workspace }}/vulkan_icd/lvp_icd.json
        VK_LAVA_EXTERNAL_MEMORY_SUPPORT: "0"
        # VK_LOADER_DEBUG: all
      run: |
        dotnet test src/Tests-Generators/Tests-Generators-Code.csproj          -r linux-x64 -c Debug --no-build --verbosity normal
        dotnet test src/Tests-Generators-Verify/Tests-Generators-Verify.csproj -r linux-x64 -c Debug --no-build --verbosity normal

    