// <auto-generated />  path: shaders/basic.vert.wgsl.cs
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.Vectorization.WebGPU;
using System.Numerics;

namespace Shaders;


[Source("~/shaders/basic.vert.wgsl")]
[StructLayout(LayoutKind.Explicit, Size = 64)]
public struct Uniforms (in Matrix4x4 modelViewProjectionMatrix)
{
    [FieldOffset(  0)]  public  Matrix4x4 modelViewProjectionMatrix = modelViewProjectionMatrix;
}


