// <auto-generated />  path: shaders/parser-crash.vert.wgsl.cs
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Friflo.WGPU;

/* -------- Error parsing: shaders/parser-crash.vert.wgsl
System.Exception: Intentional !!CRASH!!
   at Friflo.WGSL.Transpiler.WGSL.FastWgslParser.ParseWgsl(String wgslCode, String sourcePath)
   at Friflo.WGSL.Transpiler.WGSL.TypeGen.EmitFile(WgslFile file, TypeBuilder typeBuilder)
*/