// <auto-generated />  path: shaders/parser-crash.vert.wgsl.cs
/* -------- Error parsing: shaders/parser-crash.vert.wgsl
System.Exception: Intentional !!CRASH!!
   at Friflo.WGSL.Transpiler.WGSL.FastWgslParser.ParseWgsl(String wgslCode, String sourcePath)
   at Friflo.WGSL.Transpiler.WGSL.TypeGen.EmitFile(WgslFile file)
*/